@extends('ClientPortal::layouts.application')

@section('title', 'Báo cáo đối tác')
@section('app-name', $applicationPresentation['name'] ?? $application['name'])
@section('app-subtitle', 'Đối tác · '.$partnerPeriod)
@section('app-dashboard-route', route('client.invoices.dashboard'))

@section('content')
@php
    $money = fn ($value) => number_format((float) $value, 0, ',', '.').' ₫';
    $netTotal = (float) ($partnerSummary['sold_total'] ?? 0) - (float) ($partnerSummary['purchase_total'] ?? 0);
    $vatTotal = (float) ($partnerSummary['sold_vat'] ?? 0) + (float) ($partnerSummary['purchase_vat'] ?? 0);
    $detailBaseQuery = collect($partnerFilters)->filter(fn ($value) => $value !== null && $value !== '')->all();
    $defaultPartnerSort = $partnerFilters['type'] === 'purchase' ? 'purchase_desc' : 'sold_desc';
    $hasPartnerFilters = (bool) ($partnerFilters['partner'] || $partnerFilters['type'] || $partnerFilters['sort'] !== $defaultPartnerSort || $partnerFilters['per_page'] !== 25);
@endphp

<div class="space-y-4 sm:space-y-5">
    <section class="overflow-hidden rounded-3xl bg-slate-950 px-4 py-5 text-white shadow-sm sm:px-6 sm:py-6 xl:rounded-[2rem] xl:px-7 xl:py-7">
        <div class="grid gap-4 xl:grid-cols-[1fr_auto] xl:items-end">
            <div>
                <div class="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[11px] font-semibold text-slate-200 sm:text-xs"><span class="h-2 w-2 rounded-full bg-sky-400"></span>{{ $partnerPeriod }}</div>
                <h1 class="mt-2 text-2xl font-bold tracking-tight sm:mt-3 sm:text-3xl xl:text-4xl">Tổng quan đối tác</h1>
                <p class="mt-1.5 max-w-3xl text-xs leading-5 text-slate-300 sm:mt-2 sm:text-sm sm:leading-6">Góc nhìn điều hành về khách hàng và nhà cung cấp: quy mô giao dịch, xếp hạng bán ra, mua vào, VAT và chênh lệch theo kỳ.</p>
            </div>
            <form method="GET" action="{{ route('client.invoices.partners') }}" class="grid grid-cols-2 gap-2 rounded-2xl bg-white/10 p-2.5 sm:gap-3 sm:rounded-3xl sm:p-3 xl:min-w-[520px]" data-partner-period-form>
                <label class="text-[10px] font-bold uppercase tracking-wider text-slate-300 sm:text-xs">Năm<select name="year" onchange="this.form.submit()" class="mt-1.5 min-h-10 w-full rounded-xl border-0 bg-white px-3 text-xs font-bold text-slate-950 shadow-sm sm:mt-2 sm:min-h-12 sm:rounded-2xl sm:px-4 sm:text-sm">@foreach($partnerYears as $year)<option value="{{ $year }}" @selected($partnerFilters['year'] === $year)>{{ $year }}</option>@endforeach</select></label>
                <label class="text-[10px] font-bold uppercase tracking-wider text-slate-300 sm:text-xs">Tháng<select name="month" onchange="this.form.submit()" class="mt-1.5 min-h-10 w-full rounded-xl border-0 bg-white px-3 text-xs font-bold text-slate-950 shadow-sm sm:mt-2 sm:min-h-12 sm:rounded-2xl sm:px-4 sm:text-sm"><option value="" @selected($partnerFilters['month'] === null)>Cả năm</option>@for($month = 1; $month <= 12; $month++)<option value="{{ $month }}" @selected($partnerFilters['month'] === $month)>Tháng {{ $month }}</option>@endfor</select></label>
                @if($partnerFilters['type'])<input type="hidden" name="type" value="{{ $partnerFilters['type'] }}">@endif
                @if($partnerFilters['partner'])<input type="hidden" name="partner" value="{{ $partnerFilters['partner'] }}">@endif
                <input type="hidden" name="sort" value="{{ $partnerFilters['sort'] }}"><input type="hidden" name="per_page" value="{{ $partnerFilters['per_page'] }}">
            </form>
        </div>
    </section>

    <section class="grid grid-cols-2 gap-2.5 sm:gap-3 lg:grid-cols-3 xl:grid-cols-5">
        <div class="rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm sm:rounded-3xl sm:p-5"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:text-xs">Đối tác trong kỳ</p><p class="mt-2 text-2xl font-black tracking-tight text-slate-950 sm:mt-3 sm:text-3xl">{{ number_format($partnerCount) }}</p><p class="mt-1 text-xs text-slate-500 sm:mt-2 sm:text-sm">{{ number_format($partnerSummary['invoice_count'] ?? 0) }} hóa đơn.</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm sm:rounded-3xl sm:p-5"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:text-xs">Bán ra</p><p class="mt-2 whitespace-nowrap text-base font-black tracking-tight text-slate-950 sm:mt-3 sm:text-xl">{{ $money($partnerSummary['sold_total'] ?? 0) }}</p><p class="mt-1 text-xs text-slate-500 sm:mt-2 sm:text-sm">{{ number_format($partnerSummary['sold_count'] ?? 0) }} hóa đơn.</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm sm:rounded-3xl sm:p-5"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:text-xs">Mua vào</p><p class="mt-2 whitespace-nowrap text-base font-black tracking-tight text-slate-950 sm:mt-3 sm:text-xl">{{ $money($partnerSummary['purchase_total'] ?? 0) }}</p><p class="mt-1 text-xs text-slate-500 sm:mt-2 sm:text-sm">{{ number_format($partnerSummary['purchase_count'] ?? 0) }} hóa đơn.</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm sm:rounded-3xl sm:p-5"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:text-xs">Chênh lệch</p><p class="mt-2 whitespace-nowrap text-base font-black tracking-tight sm:mt-3 sm:text-xl {{ $netTotal >= 0 ? 'text-emerald-700' : 'text-rose-700' }}">{{ $money($netTotal) }}</p><p class="mt-1 text-xs text-slate-500 sm:mt-2 sm:text-sm">Bán ra trừ mua vào.</p></div>
        <div class="col-span-2 rounded-2xl border border-slate-200 bg-white p-3.5 shadow-sm sm:rounded-3xl sm:p-5 lg:col-span-1"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:text-xs">VAT</p><p class="mt-2 whitespace-nowrap text-base font-black tracking-tight text-slate-950 sm:mt-3 sm:text-xl">{{ $money($vatTotal) }}</p><p class="mt-1 text-xs text-slate-500 sm:mt-2 sm:text-sm">VAT bán ra + mua vào.</p></div>
    </section>

    <section class="grid gap-3 sm:gap-4 lg:grid-cols-2">
        @foreach([['label' => 'Khách hàng', 'title' => 'Top bán ra', 'rows' => $partnerTopSold, 'amount' => 'sold_total', 'count' => 'sold_count', 'dark' => true], ['label' => 'Nhà cung cấp', 'title' => 'Top mua vào', 'rows' => $partnerTopPurchase, 'amount' => 'purchase_total', 'count' => 'purchase_count', 'dark' => false]] as $ranking)
            <div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:rounded-3xl sm:p-5 xl:p-6">
                <div class="flex items-end justify-between gap-3"><div><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400 sm:text-xs">{{ $ranking['label'] }}</p><h2 class="mt-1 text-lg font-black text-slate-950 sm:text-xl">{{ $ranking['title'] }}</h2></div><span class="text-[11px] font-semibold text-slate-400 sm:text-xs">Top 5</span></div>
                <div class="mt-3 space-y-2 sm:mt-5 sm:space-y-3">
                    @forelse($ranking['rows'] as $row)
                        <a href="{{ route('client.invoices.partners', array_merge($detailBaseQuery, ['detail_name' => $row->partner_name, 'detail_tax_code' => $row->partner_tax_code])) }}" class="grid grid-cols-[auto_minmax(0,1fr)] items-center gap-x-2.5 gap-y-1 rounded-xl bg-slate-50 p-2.5 transition hover:bg-slate-100 sm:gap-x-3 sm:rounded-2xl sm:p-3 xl:grid-cols-[auto_minmax(0,1fr)_auto]">
                            <span class="row-span-2 flex h-8 w-8 shrink-0 items-center justify-center rounded-full {{ $ranking['dark'] ? 'bg-slate-950 text-white' : 'bg-slate-200 text-slate-700' }} text-xs font-black sm:h-9 sm:w-9 sm:text-sm xl:row-span-1">{{ $loop->iteration }}</span>
                            <span class="min-w-0"><strong class="block truncate text-xs text-slate-950 sm:text-sm">{{ $row->partner_name }}</strong><span class="block truncate text-[10px] text-slate-500 sm:text-xs">MST {{ $row->partner_tax_code }} · {{ number_format($row->{$ranking['count']}) }} HĐ</span></span>
                            <strong class="col-start-2 whitespace-nowrap text-left text-xs font-black text-slate-950 sm:text-sm xl:col-start-3 xl:row-start-1 xl:text-right">{{ $money($row->{$ranking['amount']}) }}</strong>
                        </a>
                    @empty
                        <p class="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Chưa có dữ liệu trong kỳ.</p>
                    @endforelse
                </div>
            </div>
        @endforeach
    </section>

    @if($partnerDetail)
        <section class="rounded-2xl border border-sky-200 bg-sky-50/70 p-4 shadow-sm sm:rounded-3xl sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div class="min-w-0"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-sky-700 sm:text-xs">Chi tiết đối tác</p><h2 class="mt-1 text-lg font-black text-slate-950 sm:text-xl">{{ $partnerDetail['partner_name'] }}</h2><p class="mt-1 text-xs text-slate-500 sm:text-sm">MST {{ $partnerDetail['partner_tax_code'] }} · {{ $partnerPeriod }}</p></div><a href="{{ route('client.invoices.partners', $detailBaseQuery) }}" class="inline-flex min-h-10 items-center justify-center rounded-xl bg-white px-4 text-xs font-bold text-slate-700 shadow-sm ring-1 ring-slate-200 sm:min-h-11 sm:rounded-2xl sm:text-sm">Đóng chi tiết</a></div><div class="mt-4 grid grid-cols-2 gap-2.5 sm:mt-5 sm:gap-3 xl:grid-cols-4"><div class="rounded-xl bg-white p-3 sm:rounded-2xl sm:p-4"><span class="text-[10px] font-semibold text-slate-500 sm:text-xs">Tổng hóa đơn</span><strong class="mt-1 block text-lg text-slate-950 sm:text-xl">{{ number_format($partnerDetail['invoice_count']) }}</strong></div>@foreach([['Bán ra','sold_total'],['Mua vào','purchase_total'],['Chênh lệch','total_difference']] as [$label,$key])<div class="rounded-xl bg-white p-3 sm:rounded-2xl sm:p-4"><span class="text-[10px] font-semibold text-slate-500 sm:text-xs">{{ $label }}</span><strong class="mt-1 block whitespace-nowrap text-sm sm:text-lg {{ $key === 'total_difference' ? (($partnerDetail[$key] >= 0) ? 'text-emerald-700' : 'text-rose-700') : 'text-slate-950' }}">{{ $money($partnerDetail[$key]) }}</strong></div>@endforeach</div></section>
    @endif

    <section class="rounded-2xl border {{ $hasPartnerFilters ? 'border-sky-300 bg-sky-50/40 ring-1 ring-sky-100' : 'border-slate-200 bg-white' }} shadow-sm sm:rounded-3xl">
        <details class="group xl:hidden" @if($hasPartnerFilters) open @endif>
            <summary class="cursor-pointer list-none px-4 py-3.5 [&::-webkit-details-marker]:hidden">
                <div class="flex items-center justify-between gap-3">
                    <span class="flex min-w-0 items-center gap-3">
                        <span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl {{ $hasPartnerFilters ? 'bg-sky-600 text-white' : 'bg-sky-50 text-sky-700' }} shadow-sm" aria-hidden="true">⌕</span>
                        <span class="min-w-0">
                            <span class="flex items-center gap-2 text-sm font-black text-slate-950">Bộ lọc đối tác @if($hasPartnerFilters)<span class="rounded-full bg-sky-600 px-2 py-0.5 text-[9px] font-black uppercase tracking-wide text-white">Đang lọc</span>@endif</span>
                            <span class="mt-0.5 block truncate text-[11px] font-medium text-slate-500">{{ $partnerFilters['partner'] ? 'Đang tìm: '.$partnerFilters['partner'] : 'Lọc theo tên, MST, quan hệ và thứ tự hiển thị' }}</span>
                        </span>
                    </span>
                    <span class="shrink-0 rounded-full bg-slate-950 px-3 py-1.5 text-[11px] font-bold text-white group-open:hidden">Mở bộ lọc</span>
                    <span class="hidden shrink-0 rounded-full bg-white px-3 py-1.5 text-[11px] font-bold text-slate-600 ring-1 ring-slate-200 group-open:inline">Thu gọn</span>
                </div>
            </summary>
            @if($hasPartnerFilters)
                <div class="border-t border-sky-100 px-4 py-2.5">
                    <div class="flex flex-wrap items-center gap-2 text-[11px]">
                        @if($partnerFilters['partner'])<span class="max-w-full truncate rounded-full bg-white px-3 py-1.5 font-bold text-sky-800 ring-1 ring-sky-200">Đang lọc: {{ $partnerFilters['partner'] }}</span>@endif
                        @if($partnerFilters['type'])<span class="rounded-full bg-white px-3 py-1.5 font-semibold text-slate-600 ring-1 ring-slate-200">{{ $partnerFilters['type'] === 'sold' ? 'Khách hàng' : 'Nhà cung cấp' }}</span>@endif
                        <a href="{{ route('client.invoices.partners', ['year' => $partnerFilters['year'], 'month' => $partnerFilters['month']]) }}" class="rounded-full bg-slate-950 px-3 py-1.5 font-bold text-white">× Xóa lọc</a>
                    </div>
                </div>
            @endif
            <div class="border-t {{ $hasPartnerFilters ? 'border-sky-100' : 'border-slate-100' }} bg-white p-4"><form method="GET" action="{{ route('client.invoices.partners') }}" class="grid gap-3 sm:grid-cols-2"><input type="hidden" name="year" value="{{ $partnerFilters['year'] }}">@if($partnerFilters['month'])<input type="hidden" name="month" value="{{ $partnerFilters['month'] }}">@endif
                <label class="sm:col-span-2"><span class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:text-xs">Đối tác</span><x-search name="partner" :value="$partnerFilters['partner']" list="invoice-partner-report-options-compact" placeholder="Tìm tên hoặc MST đối tác..." autocomplete="off" input-class="min-h-11 rounded-xl border-slate-200 bg-white px-4 text-sm text-slate-900 focus:border-slate-400 focus:ring-2 focus:ring-slate-100" /><datalist id="invoice-partner-report-options-compact">@foreach($partnerOptions as $partner)<option value="{{ $partner }}"></option>@endforeach</datalist></label>
                <label><span class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:text-xs">Quan hệ</span><select name="type" onchange="const sort=this.form.elements.sort;if(this.value==='purchase'){sort.value='purchase_desc'}else if(this.value==='sold'){sort.value='sold_desc'};this.form.submit()" class="min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"><option value="" @selected($partnerFilters['type'] === null)>Tất cả</option><option value="sold" @selected($partnerFilters['type'] === 'sold')>Khách hàng</option><option value="purchase" @selected($partnerFilters['type'] === 'purchase')>Nhà cung cấp</option></select></label>
                <label><span class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:text-xs">Sắp xếp</span><select name="sort" onchange="this.form.submit()" class="min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"><option value="sold_desc" @selected($partnerFilters['sort'] === 'sold_desc')>Bán ra cao nhất</option><option value="purchase_desc" @selected($partnerFilters['sort'] === 'purchase_desc')>Mua vào cao nhất</option><option value="invoice_desc" @selected($partnerFilters['sort'] === 'invoice_desc')>Nhiều hóa đơn nhất</option><option value="vat_desc" @selected($partnerFilters['sort'] === 'vat_desc')>VAT cao nhất</option><option value="net_desc" @selected($partnerFilters['sort'] === 'net_desc')>Chênh lệch cao nhất</option><option value="partner_asc" @selected($partnerFilters['sort'] === 'partner_asc')>Tên A → Z</option></select></label>
                <label><span class="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400 sm:text-xs">Hiển thị</span><select name="per_page" onchange="this.form.submit()" class="min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($partnerFilters['per_page'] === $size)>{{ $size }}</option>@endforeach</select></label><div class="flex items-end"><a href="{{ route('client.invoices.partners', ['year' => $partnerFilters['year'], 'month' => $partnerFilters['month']]) }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-slate-100 px-4 text-sm font-bold text-slate-600">Xóa lọc</a></div>
            </form></div>
        </details>

        <div class="hidden border-b border-slate-100 p-5 xl:block"><form method="GET" action="{{ route('client.invoices.partners') }}" class="grid grid-cols-12 gap-3"><input type="hidden" name="year" value="{{ $partnerFilters['year'] }}">@if($partnerFilters['month'])<input type="hidden" name="month" value="{{ $partnerFilters['month'] }}">@endif
            <label class="col-span-4"><span class="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-400">Đối tác</span><x-search name="partner" :value="$partnerFilters['partner']" list="invoice-partner-report-options" placeholder="Tìm tên hoặc MST đối tác..." autocomplete="off" input-class="min-h-11 rounded-2xl border-slate-200 bg-white px-4 text-sm text-slate-900 focus:border-slate-400 focus:ring-2 focus:ring-slate-100" /><datalist id="invoice-partner-report-options">@foreach($partnerOptions as $partner)<option value="{{ $partner }}"></option>@endforeach</datalist></label>
            <label class="col-span-2"><span class="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-400">Quan hệ</span><select name="type" onchange="const sort=this.form.elements.sort;if(this.value==='purchase'){sort.value='purchase_desc'}else if(this.value==='sold'){sort.value='sold_desc'};this.form.submit()" class="min-h-11 w-full rounded-2xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"><option value="" @selected($partnerFilters['type'] === null)>Tất cả</option><option value="sold" @selected($partnerFilters['type'] === 'sold')>Khách hàng</option><option value="purchase" @selected($partnerFilters['type'] === 'purchase')>Nhà cung cấp</option></select></label>
            <label class="col-span-3"><span class="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-400">Sắp xếp</span><select name="sort" onchange="this.form.submit()" class="min-h-11 w-full rounded-2xl border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-700"><option value="sold_desc" @selected($partnerFilters['sort'] === 'sold_desc')>Bán ra cao nhất</option><option value="purchase_desc" @selected($partnerFilters['sort'] === 'purchase_desc')>Mua vào cao nhất</option><option value="invoice_desc" @selected($partnerFilters['sort'] === 'invoice_desc')>Nhiều hóa đơn nhất</option><option value="vat_desc" @selected($partnerFilters['sort'] === 'vat_desc')>VAT cao nhất</option><option value="net_desc" @selected($partnerFilters['sort'] === 'net_desc')>Chênh lệch cao nhất</option><option value="partner_asc" @selected($partnerFilters['sort'] === 'partner_asc')>Tên A → Z</option></select></label>
            <label class="col-span-1"><span class="mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-400">Hiển thị</span><select name="per_page" onchange="this.form.submit()" class="min-h-11 w-full rounded-2xl border border-slate-200 bg-white px-2 text-sm font-semibold text-slate-700">@foreach([10,25,50,100] as $size)<option value="{{ $size }}" @selected($partnerFilters['per_page'] === $size)>{{ $size }}</option>@endforeach</select></label><div class="col-span-2 flex items-end"><a href="{{ route('client.invoices.partners', ['year' => $partnerFilters['year'], 'month' => $partnerFilters['month']]) }}" class="inline-flex min-h-11 w-full items-center justify-center rounded-2xl bg-slate-100 px-4 text-sm font-bold text-slate-600">Xóa lọc</a></div>
        </form></div>

        <div class="grid gap-3 p-3 sm:grid-cols-2 sm:p-4 xl:hidden">@forelse($partners as $row)@php $difference = (float) $row->sold_total - (float) $row->purchase_total; @endphp<a href="{{ route('client.invoices.partners', array_merge($detailBaseQuery, ['detail_name' => $row->partner_name, 'detail_tax_code' => $row->partner_tax_code])) }}" class="block rounded-2xl border border-slate-200 p-3.5 transition hover:bg-slate-50 sm:p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><strong class="block text-sm leading-5 text-slate-950">{{ $row->partner_name }}</strong><span class="mt-1 block text-[11px] text-slate-500 sm:text-xs">MST {{ $row->partner_tax_code }}</span></div><span class="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600 sm:text-xs">{{ number_format($row->invoice_count) }} HĐ</span></div><div class="mt-3 grid grid-cols-2 gap-x-4 gap-y-2 border-t border-slate-100 pt-3 text-xs sm:text-sm"><div><span class="block text-[10px] text-slate-400 sm:text-xs">Bán ra</span><strong class="mt-0.5 block whitespace-nowrap text-slate-950">{{ $money($row->sold_total) }}</strong></div><div class="text-right"><span class="block text-[10px] text-slate-400 sm:text-xs">Mua vào</span><strong class="mt-0.5 block whitespace-nowrap text-slate-950">{{ $money($row->purchase_total) }}</strong></div><div><span class="block text-[10px] text-slate-400 sm:text-xs">VAT</span><strong class="mt-0.5 block whitespace-nowrap font-medium text-slate-600">{{ $money($row->vat_total) }}</strong></div><div class="text-right"><span class="block text-[10px] text-slate-400 sm:text-xs">Chênh lệch</span><strong class="mt-0.5 block whitespace-nowrap {{ $difference >= 0 ? 'text-emerald-700' : 'text-rose-700' }}">{{ $money($difference) }}</strong></div></div></a>@empty<p class="rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500 sm:col-span-2">Không có đối tác phù hợp bộ lọc.</p>@endforelse</div>

        <div class="hidden overflow-x-auto xl:block"><table class="w-full min-w-[1100px] table-auto text-sm"><thead class="bg-slate-50 text-left text-xs font-bold uppercase tracking-wider text-slate-400"><tr><th class="min-w-[300px] px-5 py-3">Đối tác</th><th class="w-px whitespace-nowrap px-4 py-3 text-right">Hóa đơn</th><th class="w-px whitespace-nowrap px-4 py-3 text-right">Bán ra</th><th class="w-px whitespace-nowrap px-4 py-3 text-right">Mua vào</th><th class="w-px whitespace-nowrap px-4 py-3 text-right">VAT</th><th class="w-px whitespace-nowrap px-5 py-3 text-right">Chênh lệch</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($partners as $row)@php $difference = (float) $row->sold_total - (float) $row->purchase_total; @endphp<tr class="transition hover:bg-slate-50"><td class="min-w-[300px] px-5 py-4"><a href="{{ route('client.invoices.partners', array_merge($detailBaseQuery, ['detail_name' => $row->partner_name, 'detail_tax_code' => $row->partner_tax_code])) }}" class="font-bold text-slate-950 hover:underline">{{ $row->partner_name }}</a><span class="mt-1 block text-xs text-slate-500">MST {{ $row->partner_tax_code }}</span></td><td class="w-px whitespace-nowrap px-4 py-4 text-right font-semibold text-slate-700">{{ number_format($row->invoice_count) }}</td><td class="w-px whitespace-nowrap px-4 py-4 text-right font-semibold text-slate-950">{{ $money($row->sold_total) }}</td><td class="w-px whitespace-nowrap px-4 py-4 text-right font-semibold text-slate-950">{{ $money($row->purchase_total) }}</td><td class="w-px whitespace-nowrap px-4 py-4 text-right text-slate-600">{{ $money($row->vat_total) }}</td><td class="w-px whitespace-nowrap px-5 py-4 text-right font-bold {{ $difference >= 0 ? 'text-emerald-700' : 'text-rose-700' }}">{{ $money($difference) }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">Không có đối tác phù hợp bộ lọc.</td></tr>@endforelse</tbody></table></div>
        @if($partners->hasPages())<div class="border-t border-slate-100 px-4 py-4 sm:px-5">{{ $partners->links() }}</div>@endif
    </section>
</div>
@endsection