<div class="space-y-6" x-data="{ open:@entangle('isModalOpen'), dragItem:null, dropBefore(targetId,parentId,list){if(!this.dragItem)return;let ids=Array.from(list.querySelectorAll(':scope > li[data-id]')).map(el=>Number(el.dataset.id)).filter(id=>id!==Number(this.dragItem.id));const i=ids.indexOf(Number(targetId));i>=0?ids.splice(i,0,Number(this.dragItem.id)):ids.push(Number(this.dragItem.id));$wire.moveItemByDrag(Number(this.dragItem.id),parentId===null?null:Number(parentId),ids);this.dragItem=null}, dropEnd(parentId,list){if(!this.dragItem)return;let ids=Array.from(list.querySelectorAll(':scope > li[data-id]')).map(el=>Number(el.dataset.id)).filter(id=>id!==Number(this.dragItem.id));ids.push(Number(this.dragItem.id));$wire.moveItemByDrag(Number(this.dragItem.id),parentId===null?null:Number(parentId),ids);this.dragItem=null} }">
    @php($fieldClass='mt-1 block w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-900 shadow-sm transition placeholder:text-gray-400 hover:border-gray-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100')

    @include('Website::livewire.admin.header.partials.system-actions')

    <div class="flex flex-col gap-4 rounded-xl border border-gray-200 bg-white p-4 shadow-sm sm:flex-row sm:items-end sm:justify-between">
        <div class="w-full sm:max-w-md"><label class="block text-sm font-semibold text-gray-700">Vị trí Menu</label><select wire:model.live="location" class="{{ $fieldClass }}">@foreach($menuLocations as $key=>$name)<option value="{{ $key }}">{{ $name }}</option>@endforeach</select><p class="mt-1 text-xs text-gray-500">Location lấy từ cấu hình Header, không hardcode trong Livewire.</p></div>
        <button type="button" wire:click="openModal" class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-blue-700">+ Thêm mục mới</button>
    </div>

    @error('menu')<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $message }}</div>@enderror

    <div class="rounded-xl border border-gray-200 bg-white shadow-sm">
        <div class="border-b border-gray-100 px-5 py-4"><h3 class="font-bold text-gray-900">Menu điều hướng</h3><p class="mt-1 text-sm text-gray-500">Kéo ⋮⋮ để đổi thứ tự, đưa item vào menu con hoặc trở lại cấp gốc.</p></div>
        @if($menuTree->isEmpty())
            <div class="m-5 rounded-lg border border-dashed border-gray-300 bg-gray-50 p-8 text-center text-sm text-gray-500">Chưa có menu ở vị trí này. Database chỉ được tạo khi bạn lưu item mới.</div>
        @else
            <ul class="space-y-3 p-5" data-menu-list="root">
                @foreach($menuTree as $item)
                    <li data-id="{{ $item->id }}" wire:key="header-menu-root-{{ $item->id }}" draggable="true" @dragstart.stop="dragItem={id:{{ $item->id }}}" @dragend="dragItem=null" @dragover.prevent @drop.stop.prevent="dropBefore({{ $item->id }},null,$el.parentElement)" class="rounded-xl border border-gray-200 bg-gray-50 p-4">
                        <div class="flex items-start justify-between gap-4"><div class="flex min-w-0 items-start gap-3"><span class="cursor-grab select-none text-gray-400">⋮⋮</span><div><div class="flex flex-wrap items-center gap-2"><strong class="text-gray-900">{{ $item->title }}</strong><span class="rounded bg-white px-2 py-0.5 text-xs text-gray-500 ring-1 ring-gray-200">{{ $item->url ?: '#' }}</span>@if(!$item->is_active)<span class="rounded bg-red-50 px-2 py-0.5 text-xs font-semibold text-red-600">Đang ẩn</span>@endif</div></div></div><div class="flex gap-2"><button type="button" wire:click="openModal({{ $item->id }})" class="rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-semibold text-blue-600">Sửa</button><button type="button" wire:confirm="Xóa mục này và toàn bộ con?" wire:click="delete({{ $item->id }})" class="rounded-lg border border-red-200 bg-white px-3 py-1.5 text-xs font-semibold text-red-600">Xóa</button></div></div>
                        <div class="mt-4 rounded-lg border border-dashed border-gray-200 bg-white p-3"><div class="mb-2 text-[11px] font-semibold uppercase tracking-wide text-gray-400">Menu con</div><ul class="space-y-2" data-menu-list="children-{{ $item->id }}">
                            @foreach($item->children as $child)<li data-id="{{ $child->id }}" wire:key="header-menu-child-{{ $child->id }}" draggable="true" @dragstart.stop="dragItem={id:{{ $child->id }}}" @dragend="dragItem=null" @dragover.prevent @drop.stop.prevent="dropBefore({{ $child->id }},{{ $item->id }},$el.parentElement)" class="flex items-center justify-between gap-3 rounded-lg border border-gray-100 bg-gray-50 px-3 py-2.5"><div class="flex min-w-0 items-center gap-2"><span class="cursor-grab text-gray-400">⋮⋮</span><span class="truncate text-sm font-semibold text-gray-800">{{ $child->title }}</span><span class="truncate text-xs text-gray-400">{{ $child->url }}</span>@if(!$child->is_active)<span class="text-xs font-semibold text-red-500">Ẩn</span>@endif</div><div class="flex gap-2"><button type="button" wire:click="openModal({{ $child->id }})" class="text-xs font-semibold text-blue-600">Sửa</button><button type="button" wire:confirm="Xóa?" wire:click="delete({{ $child->id }})" class="text-xs font-semibold text-red-600">Xóa</button></div></li>@endforeach
                            <li @dragover.prevent @drop.stop.prevent="dropEnd({{ $item->id }},$el.parentElement)" class="rounded-lg border border-dashed border-gray-200 px-3 py-2 text-center text-xs text-gray-400" :class="dragItem?'border-blue-300 bg-blue-50 text-blue-600':''">Thả vào cuối menu con</li>
                        </ul></div>
                    </li>
                @endforeach
                <li @dragover.prevent @drop.stop.prevent="dropEnd(null,$el.parentElement)" class="rounded-lg border border-dashed border-gray-300 px-3 py-3 text-center text-xs text-gray-400" :class="dragItem?'border-blue-400 bg-blue-50 text-blue-600':''">Thả vào cuối menu cấp gốc</li>
            </ul>
        @endif
    </div>

    @teleport('body')<div x-show="open" x-cloak class="fixed inset-0 z-[9999] overflow-y-auto"><div class="fixed inset-0 bg-gray-900/70" @click="open=false"></div><div class="flex min-h-full items-center justify-center p-4"><div class="relative w-full max-w-lg rounded-xl bg-white shadow-xl"><form wire:submit.prevent="save" class="p-6"><div class="flex items-center justify-between border-b pb-3"><div><h3 class="text-lg font-bold">{{ $editingId?'Cập nhật Menu':'Thêm Menu Mới' }}</h3><p class="text-xs text-gray-500">Item chỉ lưu vào location đang chọn.</p></div><button type="button" @click="open=false" class="text-2xl text-gray-400">&times;</button></div><div class="mt-5 space-y-5">
        <div><label class="block text-sm font-semibold">Tiêu đề *</label><input type="text" wire:model="title" class="{{ $fieldClass }}">@error('title')<span class="text-xs text-red-500">{{ $message }}</span>@enderror</div>
        <div><label class="block text-sm font-semibold">Đường dẫn (URL)</label><input type="text" wire:model="url" placeholder="/gioi-thieu" class="{{ $fieldClass }}"></div>
        <div><label class="block text-sm font-semibold">Menu Cha</label><select wire:model="parent_id" class="{{ $fieldClass }}"><option value="">-- Là mục gốc --</option>@foreach($flatItems as $pItem)@if($pItem->id!=$editingId)<option value="{{ $pItem->id }}">{{ $pItem->title }}</option>@endif @endforeach</select></div>
        <div class="grid gap-4 sm:grid-cols-2"><div><label class="block text-sm font-semibold">Thứ tự</label><input type="number" wire:model="sort_order" class="{{ $fieldClass }}"></div><label class="flex items-center gap-3 rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 text-sm font-semibold sm:self-end"><input type="checkbox" wire:model="is_active" class="h-4 w-4 rounded border-gray-300 text-blue-600"> Hiển thị</label></div>
    </div><div class="mt-6 flex justify-end gap-3 border-t pt-4"><button type="button" @click="open=false" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold">Hủy</button><button type="submit" class="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Lưu lại</button></div></form></div></div></div>@endteleport
</div>
