@extends('Admin::layouts.master')
@section('title','Sửa đơn hàng thầu')
@section('admin_container','full')
@section('content')
<div class="mx-auto w-full max-w-[1480px] space-y-5">
 <header><a href="{{ route('admin.pharma.inventory.issues.show',$issue) }}" class="text-sm font-semibold text-indigo-700">← {{ $issue->number }}</a><div class="mt-2 flex flex-wrap items-center gap-2"><h1 class="text-2xl font-bold text-slate-950">Sửa đơn hàng thầu</h1><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">NHÁP</span></div><p class="mt-1 text-sm text-slate-500">Giữ nguyên nguồn phân bổ và đơn giá trúng thầu. Chỉ điều chỉnh ngày xuất, số lượng và ghi chú; chưa chọn lô ở bước này.</p></header>
 @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif
 <form method="POST" action="{{ route('admin.pharma.inventory.issues.bid-sales.update',$issue) }}" class="space-y-5">@csrf @method('PUT')
  <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 lg:grid-cols-4">
   <label class="text-sm font-semibold">Ngày xuất<input type="date" name="issue_date" value="{{ old('issue_date',$issue->issue_date->format('Y-m-d')) }}" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
   <div><p class="text-sm font-semibold">Chủ đầu tư</p><div class="mt-1 min-h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold">{{ $issue->bid_investor_name ?: $issue->bid_investor_code }}</div></div>
   <div><p class="text-sm font-semibold">Khách hàng / Bệnh viện</p><div class="mt-1 min-h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold">{{ $issue->recipient_name }}</div></div>
   <div><p class="text-sm font-semibold">Người phụ trách</p><div class="mt-1 min-h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold">{{ $rows->pluck('manager_names')->filter()->unique()->implode(', ') ?: 'Chưa phân công' }}</div></div>
  </div></section>
  <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Hàng hóa trúng thầu</h2><p class="mt-1 text-xs text-slate-500">Tồn khả dụng là tổng tồn các lô còn hạn trong kho; lô thực xuất chỉ chọn khi Ghi sổ.</p></div><div class="overflow-auto"><table class="min-w-[1180px] w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3 text-left">Mã / Thuốc</th><th class="px-4 py-3 text-center">ĐVT</th><th class="px-4 py-3 text-right">Phân bổ</th><th class="px-4 py-3 text-right">Đã xuất</th><th class="px-4 py-3 text-right">Còn lại</th><th class="px-4 py-3 text-right">Tồn khả dụng</th><th class="px-4 py-3 text-right">Đơn giá trúng thầu</th><th class="px-4 py-3 text-center">Hiệu lực đến</th><th class="w-40 px-4 py-3">SL xuất</th></tr></thead><tbody class="divide-y divide-slate-100">
   @foreach($rows as $row)<tr><td class="px-4 py-3"><div class="font-mono text-xs font-bold text-indigo-700">{{ $row['medicine_code'] }}</div><div class="font-semibold">{{ $row['medicine_name'] }}</div></td><td class="px-4 py-3 text-center">{{ $row['unit'] ?: '—' }}</td><td class="px-4 py-3 text-right">{{ number_format($row['allocated_quantity'],0,',','.') }}</td><td class="px-4 py-3 text-right">{{ number_format($row['issued_quantity'],0,',','.') }}</td><td class="px-4 py-3 text-right font-bold text-emerald-700">{{ number_format($row['remaining_quantity'],0,',','.') }}</td><td class="px-4 py-3 text-right font-bold {{ $row['available_stock'] < $row['quantity'] ? 'text-rose-600' : 'text-slate-900' }}">{{ number_format($row['available_stock'],0,',','.') }}</td><td class="px-4 py-3 text-right font-semibold">{{ number_format($row['winning_price'],0,',','.') }} đ</td><td class="px-4 py-3 text-center">{{ $row['effective_until'] ? \Carbon\Carbon::parse($row['effective_until'])->format('d/m/Y') : 'Không giới hạn' }}</td><td class="px-4 py-3"><input type="number" min="0" max="{{ $row['remaining_quantity'] }}" step="0.001" name="quantities[{{ $row['item_id'] }}]" value="{{ old('quantities.'.$row['item_id'],$row['quantity']) }}" class="w-full rounded-lg border border-slate-300 px-3 py-2"></td></tr>@endforeach
   </tbody></table></div></section>
  <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label class="text-sm font-semibold">Ghi chú<textarea name="notes" rows="3" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('notes',$issue->notes) }}</textarea></label><div class="mt-4 flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm text-slate-500"><b>Chưa trừ tồn kho.</b> Lô/HSD được chọn tại bước Ghi sổ.</p><div class="flex gap-2"><a href="{{ route('admin.pharma.inventory.issues.show',$issue) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Hủy</a><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white">Lưu đơn hàng thầu</button></div></div></section>
 </form>
</div>
@endsection
