@extends('Admin::layouts.master')
@section('title','Xuất bán hàng thầu')
@section('admin_container','full')
@section('content')
<div class="mx-auto w-full max-w-[1580px] space-y-5">
 <header><a href="{{ route('admin.pharma.inventory.issues.index') }}" class="text-sm font-semibold text-indigo-700">← Phiếu xuất kho</a><h1 class="mt-2 text-2xl font-bold text-slate-950">Xuất bán hàng thầu</h1><p class="mt-1 text-sm text-slate-500">Lập đơn từ hạn mức đã phân bổ và đơn giá trúng thầu. Phiếu được lưu nháp; chưa trừ tồn kho.</p></header>
 @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{{ $errors->first() }}</div>@endif
 <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid gap-4 lg:grid-cols-3">
  <label class="text-sm font-semibold">Ngày xuất<input id="issue-date" type="date" value="{{ old('issue_date',now()->format('Y-m-d')) }}" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
  <label class="text-sm font-semibold">Chủ đầu tư *<x-select-search id="investor" placeholder="Tìm tên / mã chủ đầu tư..."><option value="">— Chọn chủ đầu tư —</option>@foreach($investors as $investor)@php($key=$investor->investor_code ?: $investor->investor_name)<option value="{{ $key }}">{{ $investor->investor_name }}@if($investor->investor_code) · {{ $investor->investor_code }}@endif</option>@endforeach</x-select-search></label>
  <label class="text-sm font-semibold">Khách hàng / Bệnh viện *<x-select-search id="partner" placeholder="Tìm khách hàng / bệnh viện..."><option value="">— Chọn chủ đầu tư trước —</option></x-select-search></label>
 </div></section>
 <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label class="text-sm font-semibold">Tìm nhanh sản phẩm trúng thầu<x-select-search id="product-search" placeholder="Tìm theo mã thuốc, tên thuốc, hoạt chất..."><option value="">— Tất cả sản phẩm —</option></x-select-search></label></section>
 <section id="summary" class="hidden grid gap-3 rounded-2xl border border-indigo-100 bg-indigo-50/50 p-4 sm:grid-cols-4"><div class="sm:col-span-1"><p class="text-xs font-bold uppercase text-slate-500">Khách hàng</p><p id="summary-partner" class="mt-1 font-bold text-slate-900">—</p></div><div><p class="text-xs font-bold uppercase text-slate-500">Đã chọn</p><p id="summary-products" class="mt-1 font-bold">0 sản phẩm</p></div><div><p class="text-xs font-bold uppercase text-slate-500">Tổng SL xuất</p><p id="summary-qty" class="mt-1 font-bold">0</p></div><div><p class="text-xs font-bold uppercase text-slate-500">Giá trị dự kiến</p><p id="summary-value" class="mt-1 font-bold text-indigo-700">0 đ</p></div></section>
 <form id="bid-sale-form" method="POST" action="{{ route('admin.pharma.inventory.issues.bid-sales.store') }}" class="space-y-5">@csrf<input type="hidden" name="issue_date" id="form-date">
  <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-auto"><table class="min-w-[1250px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-600"><tr><th class="px-4 py-3">Mã hàng / Thuốc</th><th class="px-4 py-3">ĐVT</th><th class="px-4 py-3 text-right">SL phân bổ</th><th class="px-4 py-3 text-right">Đã xuất</th><th class="px-4 py-3 text-right">Còn lại</th><th class="px-4 py-3 text-right">Đơn giá trúng thầu</th><th class="w-[190px] px-4 py-3">Hiệu lực</th><th class="w-[150px] px-4 py-3">SL xuất</th></tr></thead><tbody id="rows"><tr><td colspan="8" class="px-6 py-12 text-center text-slate-500">Chọn chủ đầu tư và bệnh viện để tải danh sách phân bổ.</td></tr></tbody></table></div></section>
  <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label class="text-sm font-semibold">Ghi chú<textarea name="notes" rows="2" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('notes') }}</textarea></label><div class="mt-4 flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><p class="text-sm text-slate-500"><b class="text-slate-700">Phiếu nháp:</b> chưa trừ tồn kho. Lô thực xuất sẽ được chọn khi Ghi sổ.</p><button id="submit-button" class="min-h-11 rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50" disabled>Tạo phiếu nháp</button></div></section>
 </form>
</div>
<script>
const investor=document.getElementById('investor'),partner=document.getElementById('partner'),product=document.getElementById('product-search'),rows=document.getElementById('rows'),form=document.getElementById('bid-sale-form'),submitButton=document.getElementById('submit-button');
let allRows=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:4}).format(Number(n||0));
const ts=(el)=>el.tomselect;
function replaceOptions(el,options,placeholder){const control=ts(el);if(!control)return;control.clear(true);control.clearOptions();control.addOption({value:'',text:placeholder});options.forEach(o=>control.addOption(o));control.refreshOptions(false);}
function effectiveness(r){if(r.days_remaining===null)return '<span class="text-slate-500">Không giới hạn</span>';const d=Number(r.days_remaining),cls=d<=7?'bg-rose-50 text-rose-700':d<=30?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700';return `<span class="inline-flex rounded-full px-2 py-1 text-xs font-bold ${cls}">Còn ${fmt(d)} ngày</span><div class="mt-1 text-xs text-slate-500">${esc(r.effective_from||'—')} → ${esc(r.effective_until||'—')}</div>`;}
async function loadInvestor(){
 const key=investor.value;allRows=[];replaceOptions(partner,[],'— Chọn chủ đầu tư trước —');replaceOptions(product,[],'— Tất cả sản phẩm —');render([]);
 if(!key)return;
 const url=new URL(@json(route('admin.pharma.inventory.issues.bid-sales.allocations')),location.origin);url.searchParams.set('investor',key);
 const res=await fetch(url,{headers:{Accept:'application/json'}});const json=await res.json();allRows=json.data||[];
 const partners=[...new Map(allRows.map(r=>[String(r.partner_id),r.partner_name])).entries()].map(([value,text])=>({value,text}));
 replaceOptions(partner,partners,'— Chọn bệnh viện —');
}
function choosePartner(){
 const data=allRows.filter(r=>String(r.partner_id)===partner.value);
 replaceOptions(product,data.map(r=>({value:String(r.allocation_id),text:`${r.medicine_code} · ${r.medicine_name}${r.active_ingredient?' · '+r.active_ingredient:''}`})),'— Tất cả sản phẩm —');
 render(data);document.getElementById('summary').classList.toggle('hidden',!partner.value);document.getElementById('summary-partner').textContent=ts(partner)?.options[partner.value]?.text||'—';updateSummary();
}
function render(data){rows.innerHTML=data.length?data.map(r=>`<tr id="allocation-${r.allocation_id}" class="border-t border-slate-100" data-price="${r.winning_price}"><td class="px-4 py-3"><div class="font-mono text-xs font-bold text-indigo-700">${esc(r.medicine_code)}</div><div class="font-semibold">${esc(r.medicine_name)}</div>${r.active_ingredient?`<div class="text-xs text-slate-500">${esc(r.active_ingredient)}</div>`:''}</td><td class="px-4 py-3">${esc(r.unit||'—')}</td><td class="px-4 py-3 text-right">${fmt(r.allocated_quantity)}</td><td class="px-4 py-3 text-right">${fmt(r.issued_quantity)}</td><td class="px-4 py-3 text-right font-bold text-emerald-700">${fmt(r.remaining_quantity)}</td><td class="px-4 py-3 text-right font-semibold">${fmt(r.winning_price)}</td><td class="px-4 py-3">${effectiveness(r)}</td><td class="px-4 py-3"><div class="flex items-center gap-2"><input type="number" min="0" max="${r.remaining_quantity}" step="0.001" name="quantities[${r.allocation_id}]" data-allocation="${r.allocation_id}" class="qty-input w-full rounded-lg border border-slate-300 px-2 py-2" placeholder="0"><button type="button" data-max="${r.remaining_quantity}" class="max-btn text-xs font-bold text-indigo-700">Tối đa</button></div><p class="qty-error mt-1 hidden text-xs font-semibold text-rose-600"></p></td></tr>`).join(''):'<tr><td colspan="8" class="px-6 py-12 text-center text-slate-500">Không còn phân bổ hợp lệ cho lựa chọn này.</td></tr>';bindRows();updateSummary();}
function bindRows(){document.querySelectorAll('.qty-input').forEach(input=>input.addEventListener('input',()=>{validateInput(input);updateSummary()}));document.querySelectorAll('.max-btn').forEach(btn=>btn.addEventListener('click',()=>{const input=btn.parentElement.querySelector('.qty-input');input.value=btn.dataset.max;validateInput(input);updateSummary()}));}
function validateInput(input){const max=Number(input.max),value=Number(input.value||0),error=input.closest('td').querySelector('.qty-error');const invalid=value>max;input.classList.toggle('border-rose-400',invalid);error.classList.toggle('hidden',!invalid);error.textContent=invalid?`Vượt phân bổ còn lại ${fmt(value-max)}`:'';return !invalid;}
function updateSummary(){let count=0,qty=0,value=0,valid=true;document.querySelectorAll('.qty-input').forEach(input=>{const q=Number(input.value||0);if(q>0){count++;qty+=q;value+=q*Number(input.closest('tr').dataset.price||0)}valid=validateInput(input)&&valid});document.getElementById('summary-products').textContent=`${count} sản phẩm`;document.getElementById('summary-qty').textContent=fmt(qty);document.getElementById('summary-value').textContent=fmt(value)+' đ';submitButton.disabled=count===0||!valid;}
investor.addEventListener('change',loadInvestor);partner.addEventListener('change',choosePartner);product.addEventListener('change',()=>{if(!product.value)return;const row=document.getElementById('allocation-'+product.value);row?.scrollIntoView({behavior:'smooth',block:'center'});row?.classList.add('bg-indigo-50');setTimeout(()=>row?.classList.remove('bg-indigo-50'),1600);row?.querySelector('.qty-input')?.focus();});
form.addEventListener('submit',e=>{document.getElementById('form-date').value=document.getElementById('issue-date').value;if(submitButton.disabled)e.preventDefault();});
</script>
@endsection
