@extends('Admin::layouts.master')
@section('title','Trung tâm hoa hồng')
@section('admin_container','full')
@section('content')
<style>@media (min-width:1280px){.commission-filter-grid{display:grid;grid-template-columns:210px minmax(280px,1fr) 230px 165px 165px 145px;gap:12px;align-items:start}.commission-filter-grid>label{min-width:0}.commission-filter-grid select,.commission-filter-grid input{width:100%;min-width:0}}</style>
<div class="w-full space-y-5 px-2 xl:px-3">
 <header><a href="{{ route('admin.pharma.dashboard') }}" class="text-sm font-semibold text-indigo-700 hover:text-indigo-900">← Trung tâm điều hành Pharma</a><h1 class="mt-2 text-2xl font-bold text-slate-950">Trung tâm hoa hồng</h1><p class="mt-1 text-sm text-slate-500">Tổng hợp hoa hồng từ mọi phiếu xuất đã ghi sổ. Dữ liệu chính sách được snapshot tại thời điểm ghi sổ.</p></header>
 <form method="GET" id="commission-filter-form" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm space-y-4">
  <div><p class="text-xs font-bold uppercase tracking-wide text-indigo-600">1 · Nguồn tính hoa hồng</p><div class="mt-2 flex flex-wrap gap-2">
   @foreach(['all'=>'Tất cả','price_list'=>'Theo bảng giá','bid'=>'Hàng thầu'] as $key=>$label)<label class="cursor-pointer"><input type="radio" name="source" value="{{ $key }}" class="peer sr-only" @checked($source===$key) onchange="this.form.submit()"><span class="inline-flex min-h-10 items-center rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700 peer-checked:border-indigo-600 peer-checked:bg-indigo-50 peer-checked:text-indigo-700">{{ $label }}</span></label>@endforeach
  </div></div>
  <div class="border-t border-slate-100 pt-4"><p class="text-xs font-bold uppercase tracking-wide text-indigo-600">2 · Phạm vi phát sinh</p>
   <div class="commission-filter-grid mt-2 grid gap-3 md:grid-cols-2">
    <label class="text-sm font-semibold text-slate-700">Người phụ trách<x-select-search id="commission-user-filter" name="user_id" placeholder="Tìm người phụ trách..."><option value="">Tất cả User</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((int)$userId===$user->id)>{{ $user->name }}</option>@endforeach</x-select-search></label>
    <label class="text-sm font-semibold text-slate-700">Khách hàng / Bệnh viện<x-select-search id="commission-partner-filter" name="partner_id" placeholder="Tìm khách hàng / bệnh viện..."><option value="">Tất cả khách hàng</option>@foreach($partners as $partner)<option value="{{ $partner->id }}" @selected((int)$partnerId===$partner->id)>{{ $partner->name }}</option>@endforeach</x-select-search></label>
    <label class="text-sm font-semibold text-slate-700">Sản phẩm<x-select-search id="commission-medicine-filter" name="medicine_id" placeholder="Tìm sản phẩm..."><option value="">Tất cả sản phẩm</option>@foreach($medicines as $medicine)<option value="{{ $medicine->id }}" @selected((int)$medicineId===$medicine->id)>{{ $medicine->name }} · {{ $medicine->medicine_code }}</option>@endforeach</x-select-search></label>
    <label class="text-sm font-semibold text-slate-700">Từ ngày<input type="date" name="from" value="{{ $from->format('Y-m-d') }}" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="text-sm font-semibold text-slate-700">Đến ngày<input type="date" name="to" value="{{ $to->format('Y-m-d') }}" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label>
    <label class="text-sm font-semibold text-slate-700">Hiển thị<select id="commission-per-page-top" name="per_page" onchange="this.form.submit()" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm font-bold">@foreach([25,50,100] as $size)<option value="{{ $size }}" @selected($rows->perPage()===$size)>{{ $size }} / trang</option>@endforeach</select></label>
   </div>
   <div class="mt-3 flex flex-wrap items-center justify-end gap-2">@if(request()->query())<a href="{{ route('admin.pharma.inventory.commissions.index') }}" class="inline-flex min-h-10 items-center rounded-xl border border-slate-300 px-4 text-sm font-semibold">Xóa bộ lọc</a>@endif<button class="min-h-10 rounded-xl bg-indigo-600 px-5 text-sm font-semibold text-white">Áp dụng ngày</button></div>
  </div>
 </form>
 <div class="grid gap-3 md:grid-cols-4">
  <div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-bold uppercase text-slate-500">Giá trị bán</p><p class="mt-2 text-2xl font-bold">{{ number_format((float)$totals->revenue,0,',','.') }} đ</p></div>
  <div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-bold uppercase text-slate-500">Giá trị thu · bảng giá</p><p class="mt-2 text-2xl font-bold">{{ number_format((float)$receivableTotal,0,',','.') }} đ</p></div>
  <div class="rounded-2xl border border-emerald-200 bg-emerald-50/50 p-5"><p class="text-xs font-bold uppercase text-emerald-700">Hoa hồng phát sinh</p><p class="mt-2 text-2xl font-bold text-emerald-800">{{ number_format((float)$totals->commission,0,',','.') }} đ</p></div>
  <div class="rounded-2xl border {{ $unresolved ? 'border-amber-300 bg-amber-50' : 'border-slate-200 bg-white' }} p-5"><p class="text-xs font-bold uppercase text-slate-500">Chưa đủ dữ liệu</p><p class="mt-2 text-2xl font-bold">{{ $unresolved }}</p></div>
 </div>
 <div class="flex flex-wrap items-center justify-between gap-3"><button type="button" id="commission-excel-config-open" class="inline-flex min-h-10 items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold">⚙ Cấu hình Excel</button><div id="commission-selection-toolbar" class="hidden items-center gap-3 text-sm"><span class="font-semibold text-slate-700"><span id="commission-selected-count">0</span> dòng đã chọn</span><button type="button" id="commission-clear-selection" class="font-semibold text-slate-500 hover:text-slate-900">Bỏ chọn</button><button type="submit" form="commission-selected-export" class="inline-flex min-h-10 items-center rounded-xl border border-indigo-300 bg-indigo-50 px-4 text-sm font-semibold text-indigo-700">Export Excel đã chọn</button></div><a id="commission-filter-export" href="{{ route('admin.pharma.inventory.commissions.export',request()->only(['source','from','to','user_id','partner_id','medicine_id'])) }}" class="ml-auto inline-flex min-h-10 items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold">Xuất Excel theo bộ lọc</a></div>
 <div id="commission-excel-config" class="fixed inset-0 z-[100] hidden items-center justify-center bg-slate-950/40 p-4"><div class="w-full max-w-3xl rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b px-5 py-4"><div><h3 class="font-bold">Cấu hình Excel hoa hồng</h3><p class="text-xs text-slate-500">Thiết lập được ghi nhớ trên trình duyệt này.</p></div><button type="button" id="commission-excel-config-close" class="h-9 w-9 rounded-lg border">×</button></div><div class="max-h-[65vh] overflow-auto p-5"><p class="mb-3 text-xs font-bold uppercase text-indigo-600">Cột xuất Excel</p><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach(['date'=>'Ngày ghi sổ','issue'=>'Số phiếu','source'=>'Nguồn','customer'=>'Khách hàng / Bệnh viện','manager'=>'Người phụ trách','medicine_code'=>'Mã sản phẩm','medicine'=>'Sản phẩm','quantity'=>'SL thực xuất','unit_price'=>'Giá bán / Trúng thầu','receivable'=>'Giá thu','revenue'=>'Doanh thu','percentage'=>'CK / Chính sách (%)','commission'=>'Hoa hồng','status'=>'Trạng thái'] as $key=>$label)<label class="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm"><input type="checkbox" class="commission-excel-column h-4 w-4" value="{{ $key }}" checked><span>{{ $label }}</span></label>@endforeach</div><div class="mt-5 grid gap-3 sm:grid-cols-3"><label class="flex items-center gap-2 text-sm font-semibold"><input id="commission-excel-autowidth" type="checkbox" checked> Auto width</label><label class="flex items-center gap-2 text-sm font-semibold"><input id="commission-excel-wrap" type="checkbox" checked> Auto height / Wrap</label><label class="text-sm font-semibold">Khổ in<select id="commission-excel-orientation" class="mt-1 h-10 w-full rounded-xl border border-slate-300 px-3"><option value="landscape">A4 ngang</option><option value="portrait">A4 dọc</option></select></label></div></div><div class="flex justify-end gap-2 border-t px-5 py-4"><button type="button" id="commission-excel-config-reset" class="h-10 rounded-xl border px-4 text-sm font-semibold">Mặc định</button><button type="button" id="commission-excel-config-save" class="h-10 rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white">Lưu cấu hình</button></div></div></div>
 <form id="commission-selected-export" method="GET" action="{{ route('admin.pharma.inventory.commissions.export') }}">@foreach(request()->only(['source','from','to','user_id','partner_id','medicine_id']) as $key=>$value)@if(filled($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<div id="commission-selected-inputs"></div></form>
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
  <div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Chi tiết phát sinh</h2><p class="mt-1 text-xs text-slate-500">Mỗi dòng là một phiếu xuất đã ghi sổ, đồng bộ cách trình bày với PWA. Bấm mã phiếu để xem chi tiết.</p></div>
  <div class="overflow-x-auto"><table class="w-full min-w-[1040px] table-fixed text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="w-10 p-2 text-center"><input id="commission-select-all" type="checkbox" class="h-4 w-4 rounded border-slate-300"></th><th class="w-[130px] p-3 text-left">Ngày xuất</th><th class="w-[210px] p-3 text-left">Mã phiếu</th><th class="w-[30%] p-3 text-left">Khách hàng</th><th class="w-[22%] p-3 text-left">Người phụ trách</th><th class="w-[150px] p-3 text-right">Tổng giá trị</th><th class="w-[160px] p-3 text-right">Tổng hoa hồng</th></tr></thead>
  <tbody class="divide-y divide-slate-100">@forelse($rows as $row)@php($issue=$row->issue)<tr class="hover:bg-slate-50/60">
   <td class="w-10 p-2 text-center"><input type="checkbox" class="commission-row-checkbox h-4 w-4 rounded border-slate-300" value="{{ $row->issue_id }}"></td>
   <td class="p-3 font-semibold">{{ $issue?->issue_date?->format('d/m/Y') ?: $row->calculated_at?->format('d/m/Y') }}</td>
   <td class="p-3"><a class="font-mono font-bold text-indigo-700 hover:underline" href="{{ route('admin.pharma.inventory.commissions.show',$row->issue_id) }}">{{ $issue?->number }}</a><div class="mt-1"><span class="rounded-lg px-2 py-0.5 text-[10px] font-bold {{ $row->source_type==='bid' ? 'bg-violet-50 text-violet-700' : 'bg-sky-50 text-sky-700' }}">{{ $row->source_type==='bid' ? 'HÀNG THẦU' : 'BẢNG GIÁ' }}</span></div></td>
   <td class="p-3"><div class="truncate font-semibold text-slate-800" title="{{ $row->resolved_customer_name }}">{{ $row->resolved_customer_name }}</div></td>
   <td class="p-3"><div class="truncate text-slate-700">{{ $row->resolved_manager_name }}</div></td>
   <td class="p-3 text-right font-bold tabular-nums">{{ number_format((float)$row->revenue_amount,0,',','.') }} đ</td>
   <td class="p-3 text-right font-bold tabular-nums text-emerald-700">{{ number_format((float)$row->commission_amount,0,',','.') }} đ <span class="text-slate-300">›</span></td>
  </tr>@empty<tr><td colspan="7" class="p-10 text-center text-slate-500">Chưa có phiếu xuất phát sinh hoa hồng trong phạm vi đã chọn.</td></tr>@endforelse</tbody></table></div>
  <div class="flex items-center justify-between gap-3 border-t border-slate-100 px-4 py-3"><p class="text-xs font-semibold text-slate-500">Hiển thị {{ $rows->firstItem() ?? 0 }}–{{ $rows->lastItem() ?? 0 }} / {{ number_format($rows->total(),0,',','.') }} phiếu · Trang {{ $rows->currentPage() }} / {{ max(1,$rows->lastPage()) }}</p>@if($rows->hasPages())<div>{{ $rows->onEachSide(1)->links() }}</div>@endif</div>
 </section>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const f=document.getElementById('commission-filter-form'),u=document.getElementById('commission-user-filter'),p=document.getElementById('commission-partner-filter'),m=document.getElementById('commission-medicine-filter');u?.addEventListener('change',()=>{if(p)p.value='';f?.submit()});p?.addEventListener('change',()=>f?.submit());m?.addEventListener('change',()=>f?.submit());
 const excelModal=document.getElementById('commission-excel-config'),excelColumns=[...document.querySelectorAll('.commission-excel-column')],excelAuto=document.getElementById('commission-excel-autowidth'),excelWrap=document.getElementById('commission-excel-wrap'),excelOrientation=document.getElementById('commission-excel-orientation');
 const excelDefaults={columns:excelColumns.map(x=>x.value),auto_width:true,wrap:true,orientation:'landscape'};
 const readExcel=()=>{try{return {...excelDefaults,...JSON.parse(localStorage.getItem('pharma.commissions.excel')||'{}')}}catch(e){return excelDefaults}};
 const paintExcel=()=>{const s=readExcel();excelColumns.forEach(x=>x.checked=s.columns.includes(x.value));if(excelAuto)excelAuto.checked=s.auto_width!==false;if(excelWrap)excelWrap.checked=s.wrap!==false;if(excelOrientation)excelOrientation.value=s.orientation||'landscape'};
 const excelParams=()=>{const s=readExcel(),q=new URLSearchParams();s.columns.forEach(x=>q.append('excel_columns[]',x));q.set('excel_auto_width',s.auto_width?'1':'0');q.set('excel_wrap',s.wrap?'1':'0');q.set('excel_orientation',s.orientation);return q};
 const applyExcelToSelected=()=>{const form=document.getElementById('commission-selected-export');form?.querySelectorAll('[data-excel-config]').forEach(x=>x.remove());excelParams().forEach((value,key)=>{const i=document.createElement('input');i.type='hidden';i.name=key;i.value=value;i.dataset.excelConfig='1';form?.appendChild(i)})};
 document.getElementById('commission-excel-config-open')?.addEventListener('click',()=>{paintExcel();excelModal?.classList.remove('hidden');excelModal?.classList.add('flex')});
 document.getElementById('commission-excel-config-close')?.addEventListener('click',()=>{excelModal?.classList.add('hidden');excelModal?.classList.remove('flex')});
 document.getElementById('commission-excel-config-reset')?.addEventListener('click',()=>{localStorage.removeItem('pharma.commissions.excel');paintExcel()});
 document.getElementById('commission-excel-config-save')?.addEventListener('click',()=>{const columns=excelColumns.filter(x=>x.checked).map(x=>x.value);if(!columns.length)return alert('Cần chọn ít nhất một cột.');localStorage.setItem('pharma.commissions.excel',JSON.stringify({columns,auto_width:!!excelAuto?.checked,wrap:!!excelWrap?.checked,orientation:excelOrientation?.value||'landscape'}));applyExcelToSelected();excelModal?.classList.add('hidden');excelModal?.classList.remove('flex')});
 document.getElementById('commission-filter-export')?.addEventListener('click',e=>{e.preventDefault();const a=e.currentTarget,url=new URL(a.href,window.location.origin);excelParams().forEach((value,key)=>url.searchParams.append(key,value));window.location.href=url.toString()});
 document.getElementById('commission-selected-export')?.addEventListener('submit',()=>applyExcelToSelected());paintExcel();applyExcelToSelected();
 const all=document.getElementById('commission-select-all'),boxes=[...document.querySelectorAll('.commission-row-checkbox')],toolbar=document.getElementById('commission-selection-toolbar'),count=document.getElementById('commission-selected-count'),inputs=document.getElementById('commission-selected-inputs');
 const sync=()=>{const selected=boxes.filter(x=>x.checked);if(count)count.textContent=selected.length;if(toolbar){toolbar.classList.toggle('hidden',selected.length===0);toolbar.classList.toggle('flex',selected.length>0)}if(all){all.checked=boxes.length>0&&selected.length===boxes.length;all.indeterminate=selected.length>0&&selected.length<boxes.length}if(inputs)inputs.innerHTML=selected.map(x=>'<input type="hidden" name="ids[]" value="'+x.value+'">').join('')};
 all?.addEventListener('change',()=>{boxes.forEach(x=>x.checked=all.checked);sync()});boxes.forEach(x=>x.addEventListener('change',sync));document.getElementById('commission-clear-selection')?.addEventListener('click',()=>{boxes.forEach(x=>x.checked=false);sync()});sync();
})</script>
@endsection
