@extends('Admin::layouts.master')
@section('title','Tồn kho Pharma')
@section('content')
<div class="space-y-6">
<header class="flex flex-col gap-4 border-b border-slate-200 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Pharma Inventory</p><h1 class="mt-2 text-2xl font-bold text-slate-950">Tồn kho theo lô & hạn dùng</h1><p class="mt-2 text-sm text-slate-600">{{ $warehouse->name }} · Medicine Master là nguồn mã thuốc duy nhất.</p></div><div class="flex flex-wrap gap-2">@can('create_pharma')<a href="{{ route('admin.pharma.inventory.receipts.create') }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">+ Phiếu nhập</a><a href="{{ route('admin.pharma.inventory.issues.create') }}" class="rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm font-semibold text-indigo-700">+ Phiếu xuất</a>@endcan</div></header>
@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('success') }}</div>@endif
<form method="GET" class="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_auto_auto]"><input name="q" value="{{ request('q') }}" placeholder="Tìm mã thuốc / tên thuốc" class="min-h-11 rounded-xl border border-slate-300 px-3 text-sm"><label class="flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 px-3 text-sm"><input type="checkbox" name="in_stock" value="1" @checked(request('in_stock'))> Chỉ còn tồn</label><button class="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white">Lọc</button></form>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1000px] w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-600"><tr><th class="px-4 py-3">Mã thuốc</th><th class="px-4 py-3">Thuốc</th><th class="px-4 py-3">Số lô</th><th class="px-4 py-3">Hạn dùng</th><th class="px-4 py-3 text-right">Tồn đầu</th><th class="px-4 py-3 text-right">Tồn cuối</th><th class="px-4 py-3">Cảnh báo</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($balances as $row)<tr><td class="px-4 py-4 font-mono text-xs font-semibold text-indigo-700">{{ $row->medicine->medicine_code }}</td><td class="px-4 py-4"><div class="font-semibold text-slate-900">{{ $row->medicine->name }}</div><div class="text-xs text-slate-500">{{ $row->medicine->unit ?: '—' }}</div></td><td class="px-4 py-4 font-mono">{{ $row->batch_number }}</td><td class="px-4 py-4">{{ $row->expiry_date->format('d/m/Y') }}</td><td class="px-4 py-4 text-right">{{ number_format((float)$row->opening_quantity,3,',','.') }}</td><td class="px-4 py-4 text-right font-bold">{{ number_format((float)$row->quantity_on_hand,3,',','.') }}</td><td class="px-4 py-4">@if($row->expiry_date->isPast())<span class="rounded-full bg-rose-50 px-2 py-1 text-xs font-semibold text-rose-700">Đã hết hạn</span>@elseif($row->expiry_date->lte(now()->addMonths(6)))<span class="rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700">Sắp hết hạn</span>@else<span class="text-xs text-slate-400">—</span>@endif</td></tr>@empty<tr><td colspan="7" class="px-6 py-12 text-center text-slate-500">Chưa có tồn kho. Hãy lập và ghi sổ phiếu nhập.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 p-4">{{ $balances->links() }}</div></section>
<div class="grid gap-5 xl:grid-cols-2">
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-950">Phiếu nhập gần đây</h2><div class="mt-3 space-y-2">@forelse($receipts as $doc)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div><div class="font-mono text-xs font-bold">{{ $doc->number }}</div><div class="mt-1 text-xs text-slate-500">{{ $doc->receipt_date->format('d/m/Y') }} · {{ $doc->items_count }} dòng · {{ strtoupper($doc->status) }}</div></div>@if($doc->status === 'draft')@can('edit_pharma')<form method="POST" action="{{ route('admin.pharma.inventory.receipts.post',$doc) }}">@csrf<button onclick="return confirm('Ghi sổ phiếu nhập này?')" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Ghi sổ</button></form>@endcan@endif</div>@empty<p class="text-sm text-slate-500">Chưa có phiếu nhập.</p>@endforelse</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-950">Phiếu xuất gần đây</h2><div class="mt-3 space-y-2">@forelse($issues as $doc)<div class="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div><div class="font-mono text-xs font-bold">{{ $doc->number }}</div><div class="mt-1 text-xs text-slate-500">{{ $doc->issue_date->format('d/m/Y') }} · {{ $doc->items_count }} dòng · {{ strtoupper($doc->status) }}</div></div>@if($doc->status === 'draft')@can('edit_pharma')<form method="POST" action="{{ route('admin.pharma.inventory.issues.post',$doc) }}">@csrf<button onclick="return confirm('Ghi sổ phiếu xuất này?')" class="rounded-lg bg-amber-600 px-3 py-2 text-xs font-semibold text-white">Ghi sổ</button></form>@endcan@endif</div>@empty<p class="text-sm text-slate-500">Chưa có phiếu xuất.</p>@endforelse</div></section>
</div>

</div>
@endsection