<!doctype html><html lang="vi"><head><meta charset="utf-8"><style>
@page{margin:16mm 12mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;font-size:10px;color:#111}h1{font-size:21px;text-align:center;margin:16px 0 2px}.center{text-align:center}.right{text-align:right}.muted{color:#555}.header{width:100%;margin-bottom:12px}.header td{vertical-align:top}.meta{line-height:1.65;margin:14px 0}.meta b{display:inline-block;min-width:115px}table.items{width:100%;border-collapse:collapse;margin-top:12px}table.items th,table.items td{border:1px solid #444;padding:6px 5px}table.items th{font-size:8px;background:#f3f4f6;text-transform:uppercase}.name{font-weight:bold}.small{font-size:8px}.totals{margin-top:12px;line-height:1.7}.sign{width:100%;margin-top:28px;text-align:center}.sign td{width:33.33%;vertical-align:top;font-weight:bold}.sign .space{height:70px}.note{margin-top:8px}.title-no{font-size:12px;font-weight:bold}.status{font-size:8px;text-transform:uppercase}.footer{position:fixed;bottom:-8mm;left:0;right:0;text-align:center;font-size:8px;color:#777}
</style></head><body>
=>(float)$i->quantity))
@php($totalValue=$issue->items->sum(fn($i)=>(float)$i->quantity*(float)$i->unit_price))
<table class="header"><tr><td><b>{{ $settings->organization_name ?: 'PHIẾU XUẤT KHO DƯỢC PHẨM' }}</b>@if($settings->organization_address)<br><span class="muted">{{ $settings->organization_address }}</span>@endif @if($settings->tax_code)<br><span class="muted">MST: {{ $settings->tax_code }}</span>@endif @if($settings->phone)<span class="muted"> · ĐT: {{ $settings->phone }}</span>@endif</td><td class="right"><b>Mẫu chứng từ nội bộ</b><br><span class="muted">Ngày lập: {{ $issue->issue_date->format('d/m/Y') }}</span></td></tr></table>
<h1>{{ $settings->document_title }}</h1>@if($settings->document_subtitle)<div class="center muted">{{ $settings->document_subtitle }}</div>@endif<div class="center title-no">Số: {{ $issue->number }}</div>
<div class="meta"><b>Ngày xuất:</b> {{ $issue->issue_date->format('d/m/Y') }}<br><b>Xuất tại kho:</b> {{ $settings->warehouse_name }}<br><b>Khách hàng / Nơi nhận:</b> {{ $issue->recipient_name ?: '—' }}<br><b>Người phụ trách:</b> {{ $issue->priceList?->manager?->name ?: '—' }}@if($settings->show_price_list)<br><b>Bảng giá áp dụng:</b> {{ $issue->priceList?->code ?: '—' }} {{ $issue->priceList?->name ? '('.$issue->priceList->name.')' : '' }}@endif</div>
<table class="items"><thead><tr><th>STT</th><th>Mã thuốc</th><th>Tên thuốc / Quy cách</th><th>ĐVT</th><th>Số lô</th><th>Hạn dùng</th><th>SL</th>@if($settings->show_unit_price)<th>Đơn giá</th>@endif @if($settings->show_total_value)<th>Thành tiền</th>@endif</tr></thead><tbody>@foreach($issue->items as $item)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $item->medicine->medicine_code }}</td><td><span class="name">{{ $item->medicine->name }}</span>@if($item->medicine->packaging_specification)<br><span class="small">{{ $item->medicine->packaging_specification }}</span>@endif</td><td class="center">{{ $item->medicine->unit ?: '—' }}</td><td>{{ $item->batch_number }}</td><td class="center">{{ $item->expiry_date->format('d/m/Y') }}</td><td class="right">{{ number_format((float)$item->quantity,3,',','.') }}</td>@if($settings->show_unit_price)<td class="right">{{ number_format((float)$item->unit_price,0,',','.') }}</td>@endif @if($settings->show_total_value)<td class="right"><b>{{ number_format((float)$item->quantity*(float)$item->unit_price,0,',','.') }}</b></td>@endif</tr>@endforeach<tr><td colspan="7" class="right"><b>Tổng cộng</b></td>@if($settings->show_unit_price)<td></td>@endif @if($settings->show_total_value)<td class="right"><b>{{ number_format($totalValue,0,',','.') }} đ</b></td>@endif</tr></tbody></table>
<div class="totals"><b>Tổng số mặt hàng:</b> {{ $issue->items->count() }}@if($settings->show_total_value)<br><b>Tổng giá trị:</b> {{ number_format($totalValue,0,',','.') }} đồng@endif</div>
@if($settings->show_notes)<div class="note"><b>Ghi chú:</b> {{ $issue->notes ?: 'Không có ghi chú.' }}</div>@endif
<table class="sign"><tr><td>{{ $settings->issuer_label }}<br><span class="muted small">(Ký, ghi rõ họ tên)</span><div class="space"></div></td><td>{{ $settings->deliverer_label }}<br><span class="muted small">(Ký, ghi rõ họ tên)</span><div class="space"></div></td><td>{{ $settings->receiver_label }}<br><span class="muted small">(Ký, ghi rõ họ tên)</span><div class="space"></div></td></tr></table>@if($settings->footer_note)<div class="note center muted">{{ $settings->footer_note }}</div>@endif
<div class="footer">Phiếu {{ $issue->number }} · Trạng thái: {{ $issue->status==='posted'?'Đã ghi sổ':'Nháp' }}</div>
</body></html>