@extends('Admin::layouts.master')
@section('title','Phiếu xuất kho '.$issue->number)
@section('admin_container','full')
@section('content')
@php
$totalQuantity=$issue->items->sum(fn($i)=>(float)$i->quantity);
$totalValue=$issue->items->sum(fn($i)=>(float)$i->quantity*(float)$i->unit_price);
@endphp
<div class="w-full space-y-5">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <div><a href="{{ route('admin.pharma.inventory.issues.index') }}" class="text-sm font-semibold text-indigo-700">← Danh sách phiếu xuất</a><h1 class="mt-1 text-2xl font-bold">Phiếu xuất kho</h1><p class="text-sm text-slate-500">Chứng từ xuất hàng · {{ $issue->number }}</p></div>
        <div class="flex gap-2">@if($issue->status==='draft')<a href="{{ route('admin.pharma.inventory.issues.edit',$issue) }}" class="rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm font-semibold text-indigo-700">Sửa phiếu nháp</a>@endif<span class="rounded-full px-3 py-2 text-xs font-bold uppercase {{ $issue->status==='posted'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-800' }}">{{ $issue->status==='posted'?'Đã ghi sổ':'Nháp' }}</span></div>
    </div>
    <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="border-b border-slate-200 p-6">
            <div class="flex flex-wrap justify-between gap-6"><div><p class="text-xs font-bold uppercase tracking-widest text-slate-400">Kho xuất</p><h2 class="mt-1 text-xl font-bold text-slate-950">Kho chính</h2><p class="mt-1 text-sm text-slate-500">Phiếu số: <b class="text-slate-800">{{ $issue->number }}</b></p></div><div class="text-left sm:text-right"><p class="text-xs font-bold uppercase tracking-widest text-slate-400">Ngày xuất</p><p class="mt-1 text-lg font-bold">{{ $issue->issue_date->format('d/m/Y') }}</p><p class="mt-1 text-sm text-slate-500">Trạng thái: {{ $issue->status==='posted'?'Đã ghi sổ':'Nháp' }}</p></div></div>
            <div class="mt-6 grid gap-4 rounded-xl bg-slate-50 p-4 md:grid-cols-3">
                <div><p class="text-xs font-bold uppercase text-slate-400">Khách hàng / nơi nhận</p><p class="mt-1 font-semibold text-slate-900">{{ $issue->recipient_name ?: 'Chưa xác định' }}</p></div>
                <div><p class="text-xs font-bold uppercase text-slate-400">Người phụ trách</p><p class="mt-1 font-semibold text-slate-900">{{ $issue->priceList?->manager?->name ?: '—' }}</p></div>
                <div><p class="text-xs font-bold uppercase text-slate-400">Bảng giá áp dụng</p><p class="mt-1 font-semibold text-slate-900">{{ $issue->priceList?->code ?: '—' }}</p><p class="text-xs text-slate-500">{{ $issue->priceList?->name }}</p></div>
            </div>
        </header>
        <div class="overflow-x-auto"><table class="min-w-[1100px] w-full text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="p-3 text-center">STT</th><th class="p-3 text-left">Mã thuốc</th><th class="p-3 text-left">Tên thuốc / Quy cách</th><th class="p-3 text-center">ĐVT</th><th class="p-3 text-left">Số lô</th><th class="p-3 text-center">Hạn dùng</th><th class="p-3 text-right">Số lượng</th><th class="p-3 text-right">Đơn giá xuất</th><th class="p-3 text-right">Thành tiền</th></tr></thead><tbody class="divide-y">@foreach($issue->items as $item)<tr><td class="p-3 text-center">{{ $loop->iteration }}</td><td class="p-3 font-semibold">{{ $item->medicine->medicine_code }}</td><td class="p-3"><b>{{ $item->medicine->name }}</b>@if($item->medicine->packaging_specification)<div class="text-xs text-slate-500">{{ $item->medicine->packaging_specification }}</div>@endif</td><td class="p-3 text-center">{{ $item->medicine->unit ?: '—' }}</td><td class="p-3">{{ $item->batch_number }}</td><td class="p-3 text-center">{{ $item->expiry_date->format('d/m/Y') }}</td><td class="p-3 text-right font-semibold">{{ number_format((float)$item->quantity,3,',','.') }}</td><td class="p-3 text-right">{{ number_format((float)$item->unit_price,0,',','.') }} đ</td><td class="p-3 text-right font-bold">{{ number_format((float)$item->quantity*(float)$item->unit_price,0,',','.') }} đ</td></tr>@endforeach</tbody><tfoot class="border-t-2 bg-slate-50"><tr><td colspan="6" class="p-4 text-right font-bold">Tổng cộng</td><td class="p-4 text-right font-bold">{{ number_format($totalQuantity,3,',','.') }}</td><td></td><td class="p-4 text-right text-base font-bold">{{ number_format($totalValue,0,',','.') }} đ</td></tr></tfoot></table></div>
        <div class="grid gap-6 border-t p-6 lg:grid-cols-3"><div class="lg:col-span-2"><p class="text-xs font-bold uppercase text-slate-400">Ghi chú</p><p class="mt-2 min-h-12 text-sm text-slate-700">{{ $issue->notes ?: 'Không có ghi chú.' }}</p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase text-slate-400">Tổng giá trị phiếu</p><p class="mt-1 text-2xl font-bold text-slate-950">{{ number_format($totalValue,0,',','.') }} đ</p><p class="mt-1 text-xs text-slate-500">Tổng số lượng: {{ number_format($totalQuantity,3,',','.') }}</p></div></div>
        <div class="grid grid-cols-1 gap-8 border-t px-6 py-8 text-center sm:grid-cols-3"><div><p class="font-bold">Người lập phiếu</p><p class="mt-1 text-xs text-slate-500">Ký, ghi rõ họ tên</p><div class="h-20"></div></div><div><p class="font-bold">Người giao hàng</p><p class="mt-1 text-xs text-slate-500">Ký, ghi rõ họ tên</p><div class="h-20"></div></div><div><p class="font-bold">Người nhận hàng</p><p class="mt-1 text-xs text-slate-500">Ký, ghi rõ họ tên</p><div class="h-20"></div></div></div>
    </article>
</div>
@endsection
