@extends('Admin::layouts.master')
@section('title','Nhập tồn đầu kỳ')
@section('content')
<div class="mx-auto max-w-3xl space-y-6"><header><a href="{{ route('admin.pharma.inventory.index') }}" class="text-sm font-semibold text-indigo-700">← Quay về Tồn kho</a><a href="{{ route('admin.pharma.dashboard') }}" class="ml-4 text-sm font-semibold text-slate-600">Pharma</a><h1 class="mt-3 text-2xl font-bold text-slate-950">Nhập tồn đầu kỳ</h1><p class="mt-1 text-sm text-slate-500">Chỉ dùng khi khởi tạo một lô chưa từng phát sinh. Sau đó tồn thay đổi qua chứng từ.</p></header>
<form method="POST" action="{{ route('admin.pharma.inventory.opening.store') }}" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">@csrf
<label class="block text-sm font-medium">Thuốc<select name="medicine_id" required class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"><option value="">Chọn thuốc</option>@foreach($medicines as $m)<option value="{{ $m->id }}">{{ $m->medicine_code }} — {{ $m->name }}</option>@endforeach</select></label>
<div class="grid gap-4 md:grid-cols-3"><label class="text-sm font-medium">Số lô<input name="batch_number" required class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label><label class="text-sm font-medium">Hạn dùng<input type="date" name="expiry_date" required class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label><label class="text-sm font-medium">Tồn đầu kỳ<input type="number" step="0.001" min="0.001" name="quantity" required class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label></div>
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<div class="flex justify-end"><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Ghi nhận tồn đầu kỳ</button></div></form></div>
@endsection