@extends('Admin::layouts.master')
@section('title','Lập phiếu nhập kho')
@section('content')
<div class="mx-auto max-w-7xl space-y-6" x-data="{items:[{}], add(){this.items.push({})}, remove(i){if(this.items.length>1)this.items.splice(i,1)}}"><header><a href="{{ route('admin.pharma.inventory.index') }}" class="text-sm font-semibold text-indigo-700">← Quay về Tồn kho</a><a href="{{ route('admin.pharma.dashboard') }}" class="ml-4 text-sm font-semibold text-slate-600">Pharma</a><h1 class="mt-3 text-2xl font-bold text-slate-950">Lập phiếu nhập kho</h1><p class="mt-1 text-sm text-slate-500">{{ $warehouse->name }} · Phiếu mới được lưu ở trạng thái DRAFT.</p></header>
<form method="POST" action="{{ route('admin.pharma.inventory.receipts.store') }}" class="space-y-5">@csrf
<div class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-2 lg:grid-cols-4"><label class="text-sm font-medium">Ngày nhập<input type="date" name="receipt_date" value="{{ old('receipt_date',now()->toDateString()) }}" required class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label><label class="text-sm font-medium">Nhà cung cấp<input name="supplier_name" value="{{ old('supplier_name') }}" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label><label class="text-sm font-medium">Số hóa đơn<input name="invoice_number" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label><label class="text-sm font-medium">Ngày hóa đơn<input type="date" name="invoice_date" class="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"></label></div>
<div class="rounded-2xl border border-slate-200 bg-white p-5"><div class="flex items-center justify-between"><h2 class="font-semibold">Chi tiết thuốc / lô</h2><button type="button" @click="add()" class="rounded-lg border border-indigo-200 px-3 py-2 text-sm font-semibold text-indigo-700">+ Thêm dòng</button></div><div class="mt-4 space-y-3"><template x-for="(item,i) in items" :key="i"><div class="grid gap-3 rounded-xl border border-slate-200 p-3 lg:grid-cols-12"><select :name="'items['+i+'][medicine_id]'" required class="min-h-11 rounded-xl border border-slate-300 px-3 lg:col-span-4"><option value="">Chọn thuốc</option>@foreach($medicines as $m)<option value="{{ $m->id }}">{{ $m->medicine_code }} — {{ $m->name }}</option>@endforeach</select><input :name="'items['+i+'][batch_number]'" required placeholder="Số lô" class="min-h-11 rounded-xl border border-slate-300 px-3 lg:col-span-2"><input type="date" :name="'items['+i+'][expiry_date]'" required class="min-h-11 rounded-xl border border-slate-300 px-3 lg:col-span-2"><input type="number" step="0.001" min="0.001" :name="'items['+i+'][quantity]'" required placeholder="Số lượng" class="min-h-11 rounded-xl border border-slate-300 px-3 lg:col-span-1"><input type="number" step="0.0001" min="0" :name="'items['+i+'][unit_price_ex_vat]'" required placeholder="Giá chưa VAT" class="min-h-11 rounded-xl border border-slate-300 px-3 lg:col-span-2"><button type="button" @click="remove(i)" class="text-sm font-semibold text-rose-700 lg:col-span-1">Xóa</button><input type="hidden" :name="'items['+i+'][vat_rate]'" value="0"></div></template></div></div>
@if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<div class="flex justify-end"><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Lưu phiếu nhập nháp</button></div></form></div>
@endsection