<div class="space-y-6">
    <div class="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between">
        <div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Module protection</p><h2 class="mt-1 text-xl font-bold text-slate-950">Backup & Recovery</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">MANUAL snapshot bảo vệ dữ liệu Invoices + metadata PDF. Google Drive là kho phục hồi ngoài server; Partner master và binary PDF không nằm trong snapshot.</p></div>
        <button type="button" wire:click="backupNow" wire:loading.attr="disabled" wire:target="backupNow" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700 disabled:opacity-60"><span wire:loading.remove wire:target="backupNow">Backup ngay</span><span wire:loading wire:target="backupNow">Đang backup & bảo vệ…</span></button>
    </div>

    @if ($message)<div role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ $message }}</div>@endif
    @if ($error)<div role="alert" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $error }}</div>@endif

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div><div class="flex items-center gap-2"><h3 class="font-bold text-slate-950">Google Drive — Disaster Recovery</h3><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $driveConnected ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-700' }}">{{ $driveConnected ? 'ĐÃ KẾT NỐI' : 'CHƯA KẾT NỐI' }}</span></div><p class="mt-1 text-sm text-slate-500">Laravel-Backup/Invoices/Module-Backups · Server mới có thể tải snapshot từ đây để Restore.</p></div>
            <button type="button" wire:click="refreshDriveBackups" wire:loading.attr="disabled" wire:target="refreshDriveBackups" class="min-h-10 rounded-xl border border-indigo-300 px-4 py-2 text-sm font-semibold text-indigo-700 hover:bg-indigo-50"><span wire:loading.remove wire:target="refreshDriveBackups">Tìm backup trên Drive</span><span wire:loading wire:target="refreshDriveBackups">Đang đọc Drive…</span></button>
        </div>
        @if ($driveBackups)
            <div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase tracking-wide text-slate-500"><th class="py-2 pr-4">Backup</th><th class="py-2 pr-4">Dung lượng</th><th class="py-2 pr-4">Integrity</th><th class="py-2 text-right">Thao tác</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($driveBackups as $backup)<tr><td class="py-3 pr-4"><p class="font-semibold text-slate-900">{{ $backup['name'] }}</p><p class="text-xs text-slate-500">{{ $backup['modified_at'] }}</p></td><td class="py-3 pr-4">{{ number_format($backup['size'] / 1024, 1) }} KB</td><td class="py-3 pr-4"><span class="font-semibold {{ $backup['checksum'] !== '' ? 'text-emerald-700' : 'text-amber-700' }}">{{ $backup['checksum'] !== '' ? 'SHA-256' : 'Chưa xác minh' }}</span></td><td class="py-3 text-right"><button type="button" wire:click="downloadDriveBackup(@js($backup['id']), @js($backup['name']))" wire:loading.attr="disabled" class="rounded-lg border border-emerald-300 px-3 py-1.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-50">Tải về & kiểm tra</button></td></tr>@endforeach</tbody></table></div>
        @else
            <p class="mt-4 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-500">Bấm “Tìm backup trên Drive” để đọc các snapshot có thể phục hồi khi chuyển server/production.</p>
        @endif
    </section>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,0.8fr)]">
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="border-b border-slate-200 p-5"><h3 class="font-bold text-slate-950">Snapshot Local</h3><p class="mt-1 text-sm text-slate-500">MANUAL có thể xóa Local mà không xóa bản Drive. Safety Backup dùng làm điểm rollback.</p></div>
            <div class="divide-y divide-slate-100">
                @forelse ($snapshots as $snapshot)
                    @php($isSafety = str_starts_with($snapshot['mode'], 'safety'))
                    <div class="px-5 py-4 {{ $selectedSnapshot === $snapshot['directory'] ? 'bg-indigo-50 ring-1 ring-inset ring-indigo-200' : 'bg-white' }}">
                        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><button type="button" wire:click="selectSnapshot(@js($snapshot['directory']))" class="min-w-0 flex-1 text-left"><p class="font-semibold text-slate-900">{{ $snapshot['created_at'] ? \Illuminate\Support\Carbon::parse($snapshot['created_at'])->timezone(config('app.timezone'))->format('d/m/Y H:i:s') : basename($snapshot['directory']) }}</p><p class="mt-1 text-xs text-slate-500">{{ number_format($snapshot['invoices']) }} hóa đơn · {{ number_format($snapshot['files']) }} metadata PDF</p></button><div class="flex flex-wrap items-center gap-2"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $isSafety ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-700' }}">{{ strtoupper($snapshot['mode']) }}</span>@if ($isSafety)<button type="button" wire:click="rollbackSafety(@js($snapshot['directory']))" wire:confirm="Rollback từ Safety Backup này?" class="rounded-lg border border-amber-300 px-3 py-1.5 text-xs font-semibold text-amber-800">Rollback</button>@else<button type="button" wire:click="protectSnapshot(@js($snapshot['directory']))" class="rounded-lg border border-emerald-300 px-3 py-1.5 text-xs font-semibold text-emerald-700">Bảo vệ Drive</button><button type="button" wire:click="deleteSnapshot(@js($snapshot['directory']))" wire:confirm="Chỉ xóa snapshot Local? Bản Google Drive nếu có vẫn được giữ." class="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700">Xóa Local</button>@endif</div></div>
                    </div>
                @empty<div class="p-8 text-center text-sm text-slate-500">Không có snapshot Local. Nếu đây là server mới, dùng “Tìm backup trên Drive”.</div>@endforelse
            </div>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold text-slate-950">Restore Readiness</h3><p class="mt-1 text-sm text-slate-500">Snapshot tải từ Drive cũng phải qua integrity + compatibility gate.</p></div>@if ($readiness)@php($status = strtoupper($readiness['status']))<span class="rounded-full px-3 py-1 text-xs font-bold {{ $status === 'READY' ? 'bg-emerald-100 text-emerald-800' : ($status === 'WARNING' ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800') }}">{{ $status }}</span>@else<span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">CHƯA KIỂM TRA</span>@endif</div>
            <button type="button" wire:click="checkRestore" wire:loading.attr="disabled" @disabled(! $selectedSnapshot) class="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-indigo-300 px-4 py-2.5 text-sm font-semibold text-indigo-700 disabled:bg-slate-100 disabled:text-slate-400">Kiểm tra khả năng khôi phục</button>
            @if ($readiness)<div class="mt-5 space-y-4">@if ($readiness['blockers'])<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-bold">Restore bị chặn</p><ul class="mt-2 list-disc pl-5">@foreach ($readiness['blockers'] as $blocker)<li>{{ $blocker }}</li>@endforeach</ul></div>@endif @if ($readiness['warnings'])<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><p class="font-bold">Cảnh báo</p><ul class="mt-2 list-disc pl-5">@foreach ($readiness['warnings'] as $warning)<li>{{ $warning }}</li>@endforeach</ul></div>@endif @if ($impact)<div class="rounded-xl bg-slate-50 p-4"><p class="text-sm font-bold">Ảnh hưởng dự kiến — Merge an toàn</p><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-slate-500">Thêm mới</dt><dd class="font-bold text-emerald-700">+ {{ number_format($impact['invoices']['insert']) }}</dd></div><div><dt class="text-slate-500">Đã tồn tại</dt><dd class="font-bold">{{ number_format($impact['invoices']['existing']) }}</dd></div><div><dt class="text-slate-500">Có khác biệt</dt><dd class="font-bold text-amber-700">! {{ number_format($impact['invoices']['different']) }}</dd></div><div><dt class="text-slate-500">Sẽ xóa</dt><dd class="font-bold">0</dd></div><div class="col-span-2"><dt class="text-slate-500">Partner master</dt><dd class="font-bold text-emerald-700">0 thay đổi</dd></div></dl></div>@endif<button type="button" wire:click="restoreMerge" wire:loading.attr="disabled" @disabled(strtoupper($readiness['status']) === 'BLOCKED') class="min-h-11 w-full rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:bg-slate-300">Tạo Safety Backup + Khôi phục Merge</button></div>@endif
            @if ($lastRestore)<div class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><p class="font-bold">Post-Restore Verification hoàn tất</p><p class="mt-2">Hóa đơn thêm: <b>{{ number_format($lastRestore['inserted_invoices']) }}</b> · giữ nguyên: <b>{{ number_format($lastRestore['preserved_invoices']) }}</b> · Partner master: <b>{{ number_format($lastRestore['partner_master_changes']) }}</b></p><p class="mt-2 break-all text-xs">Safety Backup mới: <span class="font-mono">{{ $lastRestore['safety_backup_directory'] ?: 'Đã tạo' }}</span></p></div>@endif
        </section>
    </div>
</div>
