<div class="space-y-6" @if ($syncId && in_array($syncState, ['queued', 'processing'], true)) wire:poll.2s="pollStatus" @endif>
    <div class="rounded-2xl border border-gray-200 bg-white shadow-sm">
        <div class="grid gap-4 p-6 md:grid-cols-3">
            <div><label class="text-sm font-medium text-gray-700">Từ ngày</label><input type="date" wire:model.live="start_date" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('start_date')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div><label class="text-sm font-medium text-gray-700">Đến ngày</label><input type="date" wire:model.live="end_date" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm">@error('end_date')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
            <div><label class="text-sm font-medium text-gray-700">Loại hóa đơn</label><select wire:model.live="vatIn" class="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm"><option value="0">Bán ra</option><option value="1">Mua vào</option></select></div>
        </div>
        <div class="flex flex-wrap items-center gap-3 border-t border-gray-200 px-6 py-4"><label class="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" wire:model.live="useQueue" class="rounded border-gray-300"> Xử lý qua queue</label><button wire:click="run" wire:loading.attr="disabled" class="h-11 rounded-xl bg-emerald-600 px-5 text-sm font-semibold text-white disabled:opacity-50"><span wire:loading.remove wire:target="run">Chạy đồng bộ</span><span wire:loading wire:target="run">Đang xử lý…</span></button></div>
    </div>

    <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-gray-900">Trạng thái đồng bộ</p><p class="mt-1 text-sm text-gray-600">Queue chỉ là trạng thái đã xếp hàng; khối này sẽ tự cập nhật đến khi hoàn tất hoặc thất bại.</p></div>@php($stateLabel=match($syncState){'queued'=>'Đang chờ queue','processing'=>'Đang xử lý','completed'=>'Hoàn tất','failed'=>'Thất bại',default=>'Chưa chạy'}) @php($stateClass=match($syncState){'completed'=>'bg-emerald-50 text-emerald-700','failed'=>'bg-red-50 text-red-700','queued','processing'=>'bg-amber-50 text-amber-700',default=>'bg-gray-100 text-gray-600'})<span class="rounded-full px-3 py-1 text-xs font-semibold {{ $stateClass }}">{{ $stateLabel }}</span></div>
        @if(in_array($syncState,['queued','processing'],true))<div class="mt-4 h-2 overflow-hidden rounded-full bg-gray-100"><div class="h-full w-2/3 animate-pulse rounded-full bg-indigo-500"></div></div>@endif
        @if($syncMessage)<p class="mt-3 text-sm text-gray-700">{{ $syncMessage }}</p>@endif
        @if($syncFile)<p class="mt-2 text-xs font-medium text-emerald-700">File đã tạo: {{ $syncFile }}</p>@endif
    </div>

    <div class="rounded-2xl border border-gray-200 bg-white shadow-sm">
        <div class="border-b border-gray-200 p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="text-base font-semibold text-gray-900">Kho file hóa đơn</h3><p class="mt-1 text-sm text-gray-500">Mọi nguồn file đều được đưa vào đây trước. Loại hóa đơn được tự nhận dạng từ tên file.</p></div><button wire:click="refreshAvailableFiles" class="h-10 rounded-xl border border-gray-300 px-4 text-sm font-semibold text-gray-700">Làm mới danh sách</button></div></div>
        <div class="grid gap-6 p-6 xl:grid-cols-[1.4fr_1fr]">
            <div>
                <div class="mb-3 flex items-center justify-between"><div><p class="text-sm font-semibold text-gray-900">File đã đồng bộ</p><p class="mt-1 text-xs text-gray-500">vat_in_* = Mua vào · vat_out_* = Bán ra.</p></div><span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold text-gray-600">{{ count($availableFiles) }} file</span></div>
                <div class="max-h-96 space-y-2 overflow-y-auto pr-1">@forelse($availableFiles as $file)<label class="flex cursor-pointer items-start gap-3 rounded-xl border border-gray-200 p-3 transition hover:border-indigo-200 hover:bg-indigo-50/30"><input type="radio" wire:model.live="selectedFile" value="{{ $file['token'] }}" class="mt-1 border-gray-300 text-indigo-600"><span class="min-w-0 flex-1"><span class="flex flex-wrap items-center gap-2"><span class="block truncate text-sm font-medium text-gray-800">{{ $file['name'] }}</span><span class="rounded-full px-2 py-0.5 text-[11px] font-semibold {{ $file['direction']==='vat_in'?'bg-blue-50 text-blue-700':'bg-emerald-50 text-emerald-700' }}">{{ $file['type_label'] }}</span></span><span class="mt-1 block text-xs text-gray-500">{{ number_format($file['size']/1024,1) }} KB · {{ $file['modified_at'] }}</span></span></label>@empty<div class="rounded-xl border border-dashed border-gray-300 p-8 text-center text-sm text-gray-500">Chưa có file XLSX/CSV đúng quy ước trong kho.</div>@endforelse</div>
                <div class="mt-4 flex flex-wrap gap-2"><button wire:click="importSelectedFile" wire:loading.attr="disabled" @disabled(!$selectedFile) class="h-11 rounded-xl bg-indigo-600 px-5 text-sm font-semibold text-white disabled:opacity-40"><span wire:loading.remove wire:target="importSelectedFile">Import file đã chọn</span><span wire:loading wire:target="importSelectedFile">Đang import…</span></button><button wire:click="downloadSelectedFile" wire:loading.attr="disabled" @disabled(!$selectedFile) class="h-11 rounded-xl bg-emerald-600 px-5 text-sm font-semibold text-white disabled:opacity-40">Download về máy</button><button wire:click="deleteSelectedFile" wire:confirm="Bạn chắc chắn muốn xóa file đã chọn? Thao tác này không xóa dữ liệu hóa đơn đã import." wire:loading.attr="disabled" @disabled(!$selectedFile) class="h-11 rounded-xl border border-red-200 bg-red-50 px-5 text-sm font-semibold text-red-700 disabled:opacity-40">Xóa file đã chọn</button></div>
                @error('selectedFile')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror
            </div>
            <div class="space-y-4">
                <div class="rounded-2xl border border-gray-200 bg-gray-50 p-5"><p class="text-sm font-semibold text-gray-900">Upload từ máy tính</p><p class="mt-1 text-xs text-gray-500">XLSX/CSV tối đa 20 MB. Hệ thống tự nhận dạng theo tên file; upload chỉ lưu vào kho, chưa import database.</p><div class="mt-3 rounded-xl border border-gray-200 bg-white px-3 py-2 text-xs text-gray-600"><strong>Quy ước:</strong> <code>vat_in_*</code> = Mua vào · <code>vat_out_*</code> = Bán ra. Tên khác sẽ bị từ chối để tránh import nhầm loại.</div><input type="file" wire:model="uploadFile" accept=".xlsx,.csv" class="mt-4 block w-full rounded-xl border border-gray-300 bg-white p-3 text-sm text-gray-700">@error('uploadFile')<p class="mt-2 text-sm font-medium text-red-600">{{ $message }}</p>@enderror @if($uploadFile)<p class="mt-2 truncate text-xs text-gray-600">Đã chọn: {{ $uploadFile->getClientOriginalName() }}</p>@endif<button wire:click="stageUploadedFile" wire:loading.attr="disabled" @disabled(!$uploadFile) class="mt-4 h-11 rounded-xl bg-slate-800 px-5 text-sm font-semibold text-white disabled:opacity-40"><span wire:loading.remove wire:target="stageUploadedFile">Đưa vào File đã đồng bộ</span><span wire:loading wire:target="stageUploadedFile">Đang kiểm tra & upload…</span></button></div>
                <div class="rounded-2xl border border-blue-100 bg-blue-50/50 p-5"><p class="text-sm font-semibold text-gray-900">Google Drive</p><p class="mt-1 text-xs text-gray-500">Dán link chia sẻ công khai. Hệ thống lấy tên file gốc và tự nhận dạng loại hóa đơn trước khi lưu.</p><div class="mt-3 rounded-xl border border-blue-100 bg-white px-3 py-2 text-xs text-blue-800"><strong>Tên bắt buộc:</strong> <code>vat_in_*</code> hoặc <code>vat_out_*</code>. Nếu sai, hãy đổi tên file trên Google Drive rồi thử lại.</div><input type="url" wire:model="googleDriveUrl" placeholder="https://drive.google.com/file/d/.../view" class="mt-4 h-11 w-full rounded-xl border border-blue-200 bg-white px-4 text-sm">@error('googleDriveUrl')<p class="mt-2 text-sm font-medium text-red-600">{{ $message }}</p>@enderror<button wire:click="stageGoogleDriveFile" wire:loading.attr="disabled" @disabled(trim($googleDriveUrl)==='') class="mt-4 h-11 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white disabled:opacity-40"><span wire:loading.remove wire:target="stageGoogleDriveFile">Tải từ Drive vào kho</span><span wire:loading wire:target="stageGoogleDriveFile">Đang kiểm tra & tải…</span></button></div>
            </div>
        </div>
    </div>
    <div class="rounded-2xl border border-gray-200 bg-gray-950 p-5 font-mono text-xs text-gray-200 shadow-sm"><p class="mb-3 font-sans text-sm font-semibold text-white">Nhật ký xử lý</p><div class="max-h-80 space-y-1 overflow-y-auto">@forelse($logs as $line)<div>{{ $line }}</div>@empty<div class="text-gray-400">Chưa có tác vụ.</div>@endforelse</div></div>
</div>
