<?php

return [
    'name' => 'Inventory',
    'type' => 'domain',
    'enabled' => false,
    'default_enabled' => false,
    'depends' => ['Shared'],
    'permissions_required' => true,
    'permissions' => [
        'inventory.dashboard.view',
        'inventory.warehouse.view',
        'inventory.warehouse.manage',
        'inventory.item.view',
        'inventory.item.manage',
        'inventory.receipt.view',
        'inventory.receipt.manage',
        'inventory.receipt.confirm',
        'inventory.issue.view',
        'inventory.issue.manage',
        'inventory.issue.confirm',
        'inventory.transfer.view',
        'inventory.transfer.manage',
        'inventory.transfer.confirm',
        'inventory.stocktake.view',
        'inventory.stocktake.manage',
        'inventory.stocktake.confirm',
        'inventory.stock.view',
        'inventory.movement.view',
        'inventory.movement.reverse',
        'inventory.audit.view',
        'inventory.export',
    ],
    'tables' => [
        'inventory_warehouses',
        'inventory_items',
        'inventory_item_aliases',
        'inventory_lots',
        'inventory_receipts',
        'inventory_receipt_lines',
        'inventory_issues',
        'inventory_issue_lines',
        'inventory_transfers',
        'inventory_transfer_lines',
        'inventory_stocktakes',
        'inventory_stocktake_lines',
        'inventory_movements',
        'inventory_balances',
        'inventory_invoice_inbox',
        'inventory_invoice_inbox_lines',
    ],
];
