@php
    $control = 'mt-2 block h-10 w-full rounded-xl border-slate-300 bg-white px-3 text-sm text-slate-800 shadow-sm focus:border-indigo-500 focus:ring-indigo-500';
    $toggle = 'h-5 w-5 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500';
    $background = match ((string) data_get($config, 'sidebar.presentation.background', 'theme')) {
        'system', 'white' => 'light',
        default => (string) data_get($config, 'sidebar.presentation.background', 'theme'),
    };
    $customBackground = (string) data_get($config, 'sidebar.presentation.custom_background', '#0f172a');
    $customAccent = (string) data_get($config, 'sidebar.presentation.custom_accent', '#4f46e5');
    $widthToPx = static function (mixed $value, int $fallback): int {
        if (is_numeric($value)) return (int) $value;
        $value = trim((string) $value);
        if (preg_match('/^(\d+(?:\.\d+)?)px$/', $value, $matches)) return (int) round((float) $matches[1]);
        if (preg_match('/^(\d+(?:\.\d+)?)rem$/', $value, $matches)) return (int) round((float) $matches[1] * 16);
        return $fallback;
    };
    $expandedWidthPx = max(224, min(384, $widthToPx(data_get($config, 'sidebar.expanded_width'), 256)));
    $collapsedWidthPx = max(64, min(112, $widthToPx(data_get($config, 'sidebar.collapsed_width'), 80)));
@endphp

<div class="mx-auto max-w-7xl">
    <div class="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
        <p class="text-sm text-slate-500">Thiết kế Sidebar theo preset hoặc tự chọn cặp màu nền + accent. Preview chỉ thay đổi trên trình duyệt; Sidebar thật chỉ áp dụng sau khi lưu.</p>
        <button type="button" wire:click="resetSection" wire:confirm="Khôi phục Sidebar về mặc định?" class="inline-flex h-10 shrink-0 items-center justify-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Khôi phục Sidebar</button>
    </div>

    <form wire:submit="save" class="space-y-6" x-data="{
        sidebarBackground: @js($background), customBackground: @js($customBackground), customAccent: @js($customAccent),
        choose(mode) { this.sidebarBackground = mode; $wire.config.sidebar.presentation.background = mode; },
        validHex(value, fallback) { return /^#[0-9a-fA-F]{6}$/.test(value || '') ? value : fallback; },
        isDark(hex) { hex = this.validHex(hex, '#ffffff').slice(1); const r=parseInt(hex.slice(0,2),16),g=parseInt(hex.slice(2,4),16),b=parseInt(hex.slice(4,6),16); return ((0.2126*r+0.7152*g+0.0722*b)/255)<.56; },
        bg() { return this.sidebarBackground==='dark'?'#020617':this.sidebarBackground==='custom'?this.validHex(this.customBackground,'#0f172a'):this.sidebarBackground==='light'?'#ffffff':'#eef2ff'; },
        accent() { return this.sidebarBackground==='custom'?this.validHex(this.customAccent,'#4f46e5'):'#4f46e5'; },
        text() { return this.isDark(this.bg())?'#f8fafc':'#0f172a'; }, secondary() { return this.isDark(this.bg())?'#cbd5e1':'#475569'; }, muted() { return this.isDark(this.bg())?'#94a3b8':'#64748b'; }, soft() { return this.isDark(this.bg())?'rgba(255,255,255,.075)':'rgba(15,23,42,.055)'; }, border() { return this.isDark(this.bg())?'rgba(255,255,255,.13)':'rgba(15,23,42,.10)'; }, activeText() { return this.isDark(this.accent())?'#ffffff':'#0f172a'; }
    }">
        <div class="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_23rem] xl:items-start">
            <div class="space-y-6">
                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                    <div class="mb-5"><h2 class="text-base font-semibold text-slate-900">Giao diện Sidebar</h2><p class="mt-1 text-sm leading-6 text-slate-500">Bốn chế độ có khác biệt rõ ràng. Custom dùng đúng hai màu và hệ thống tự tính contrast cho chữ, icon, border và hover.</p></div>
                    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4" role="radiogroup" aria-label="Kiểu giao diện Sidebar">
                        @foreach ([
                            'theme' => ['Theme', 'Palette thương hiệu', 'linear-gradient(135deg,#eef2ff,#e0e7ff)', '#4f46e5'],
                            'light' => ['Light', 'Sạch & trung tính', '#ffffff', '#4f46e5'],
                            'dark' => ['Dark', 'Slate cao cấp', '#020617', '#818cf8'],
                            'custom' => ['Custom', 'Màu của bạn', null, null],
                        ] as $value => [$label, $description, $swatchBg, $swatchAccent])
                            <button type="button" role="radio" :aria-checked="(sidebarBackground === '{{ $value }}').toString()" @click="choose('{{ $value }}')" class="group rounded-xl border p-4 text-left transition focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" :class="sidebarBackground === '{{ $value }}' ? 'border-indigo-500 bg-indigo-50/50 ring-1 ring-indigo-500' : 'border-slate-200 hover:border-slate-300 hover:bg-slate-50/70'">
                                <span class="mb-3 flex items-center gap-2"><span class="relative h-9 w-12 overflow-hidden rounded-lg border border-black/10 shadow-sm" @if($value === 'custom') :style="`background:${customBackground}`" @else style="background: {{ $swatchBg }}" @endif><span class="absolute bottom-1 right-1 h-3.5 w-3.5 rounded-full ring-2 ring-white" @if($value === 'custom') :style="`background:${customAccent}`" @else style="background: {{ $swatchAccent }}" @endif></span></span></span>
                                <span class="block text-sm font-semibold text-slate-900">{{ $label }}</span><span class="mt-1 block text-xs leading-5 text-slate-500">{{ $description }}</span>
                            </button>
                        @endforeach
                    </div>
                    <input type="hidden" wire:model="config.sidebar.presentation.background">
                    <div x-cloak x-show="sidebarBackground === 'custom'" x-transition.opacity class="mt-5 rounded-2xl border border-indigo-100 bg-indigo-50/40 p-4">
                        <div class="mb-4"><h3 class="text-sm font-semibold text-slate-900">Custom palette</h3><p class="mt-1 text-xs leading-5 text-slate-500">Chỉ cần hai màu. Hệ thống tự tính màu chữ/icon để luôn đọc được.</p></div>
                        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                            <label class="block"><span class="text-sm font-medium text-slate-700">Sidebar background</span><div class="mt-2 flex items-center gap-2"><input type="color" x-model="customBackground" @input="$wire.config.sidebar.presentation.custom_background = customBackground" class="h-10 w-12 cursor-pointer rounded-lg border border-slate-300 bg-white p-1"><input type="text" maxlength="7" x-model="customBackground" @input="$wire.config.sidebar.presentation.custom_background = customBackground" class="h-10 min-w-0 flex-1 rounded-xl border-slate-300 bg-white px-3 font-mono text-sm uppercase text-slate-800 focus:border-indigo-500 focus:ring-indigo-500" placeholder="#0F172A"></div></label>
                            <label class="block"><span class="text-sm font-medium text-slate-700">Accent color</span><div class="mt-2 flex items-center gap-2"><input type="color" x-model="customAccent" @input="$wire.config.sidebar.presentation.custom_accent = customAccent" class="h-10 w-12 cursor-pointer rounded-lg border border-slate-300 bg-white p-1"><input type="text" maxlength="7" x-model="customAccent" @input="$wire.config.sidebar.presentation.custom_accent = customAccent" class="h-10 min-w-0 flex-1 rounded-xl border-slate-300 bg-white px-3 font-mono text-sm uppercase text-slate-800 focus:border-indigo-500 focus:ring-indigo-500" placeholder="#4F46E5"></div></label>
                        </div>
                        <input type="hidden" wire:model="config.sidebar.presentation.custom_background"><input type="hidden" wire:model="config.sidebar.presentation.custom_accent">
                    </div>
                </section>

                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" data-admin-sidebar-width-settings>
                    <div class="mb-5"><h2 class="text-base font-semibold text-slate-900">Kích thước & hành vi</h2><p class="mt-1 text-sm leading-6 text-slate-500">Giữ Sidebar gọn trên desktop, drawer trên mobile và nhớ trạng thái nếu cần.</p></div>
                    <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">
                        @foreach (['config.sidebar.enabled'=>['Bật Sidebar','Hiển thị điều hướng chính.'],'config.sidebar.mobile_drawer'=>['Drawer mobile','Overlay ở màn hình nhỏ.'],'config.sidebar.persist_state'=>['Nhớ trạng thái','Ghi nhớ collapse/fullscreen.']] as $model => [$label,$description])
                            <label class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 px-4 py-3"><span><span class="block text-sm font-medium text-slate-800">{{ $label }}</span><span class="mt-0.5 block text-xs text-slate-500">{{ $description }}</span></span><input type="checkbox" wire:model.live="{{ $model }}" class="{{ $toggle }}"></label>
                        @endforeach
                    </div>
                    <div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <div class="rounded-xl border border-slate-200 p-4" x-data="{ value: {{ $expandedWidthPx }} }"><div class="flex items-center justify-between"><span class="text-sm font-medium text-slate-800">Độ rộng khi mở</span><span class="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold tabular-nums text-slate-700" x-text="value + ' px'"></span></div><input type="range" min="224" max="384" step="16" x-model.number="value" @input="$wire.set('config.sidebar.expanded_width', value + 'px')" class="mt-4 w-full accent-indigo-600"></div>
                        <div class="rounded-xl border border-slate-200 p-4" x-data="{ value: {{ $collapsedWidthPx }} }"><div class="flex items-center justify-between"><span class="text-sm font-medium text-slate-800">Độ rộng khi thu gọn</span><span class="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold tabular-nums text-slate-700" x-text="value + ' px'"></span></div><input type="range" min="64" max="112" step="16" x-model.number="value" @input="$wire.set('config.sidebar.collapsed_width', value + 'px')" class="mt-4 w-full accent-indigo-600"></div>
                    </div>
                    <input type="hidden" wire:model="config.sidebar.expanded_width"><input type="hidden" wire:model="config.sidebar.collapsed_width">
                    <div class="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2"><label class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 px-4 py-3"><span class="text-sm font-medium text-slate-700">Nút thu gọn / mở rộng</span><input type="checkbox" wire:model.live="config.sidebar.controls.collapse_enabled" class="{{ $toggle }}"></label><label class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 px-4 py-3"><span class="text-sm font-medium text-slate-700">Nút Fullscreen Sidebar</span><input type="checkbox" wire:model.live="config.sidebar.controls.fullscreen_enabled" class="{{ $toggle }}"></label></div>
                </section>

                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="mb-5 flex items-start justify-between gap-5"><div><h2 class="text-base font-semibold text-slate-900">Header Sidebar</h2><p class="mt-1 text-sm text-slate-500">Nhận diện ở đầu Sidebar.</p></div><input type="checkbox" wire:model.live="config.sidebar.header.enabled" class="{{ $toggle }}"></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><label class="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3"><span class="text-sm font-medium text-slate-700">Mark / Logo</span><input type="checkbox" wire:model.live="config.sidebar.header.show_mark" class="{{ $toggle }}"></label><label class="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3"><span class="text-sm font-medium text-slate-700">Title</span><input type="checkbox" wire:model.live="config.sidebar.header.show_title" class="{{ $toggle }}"></label><label class="flex items-center justify-between rounded-xl border border-slate-200 px-4 py-3"><span class="text-sm font-medium text-slate-700">Subtitle</span><input type="checkbox" wire:model.live="config.sidebar.header.show_subtitle" class="{{ $toggle }}"></label></div><div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">@if(data_get($config,'sidebar.header.show_title',true))<label class="block"><span class="text-sm font-medium text-slate-700">Nội dung Title</span><input type="text" maxlength="80" wire:model.live.debounce.300ms="config.sidebar.header.title" class="{{ $control }}" placeholder="Để trống để dùng tên hệ thống"></label>@endif @if(data_get($config,'sidebar.header.show_subtitle',true))<label class="block"><span class="text-sm font-medium text-slate-700">Nội dung Subtitle</span><input type="text" maxlength="80" wire:model.live.debounce.300ms="config.sidebar.header.subtitle" class="{{ $control }}"></label>@endif</div></section>

                <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="grid grid-cols-1 gap-5 md:grid-cols-2"><div><div class="flex items-start justify-between gap-4"><div><h2 class="text-base font-semibold text-slate-900">Tìm chức năng</h2><p class="mt-1 text-sm text-slate-500">Ô tìm kiếm menu Sidebar.</p></div><input type="checkbox" wire:model.live="config.sidebar.search.enabled" class="{{ $toggle }}"></div>@if(data_get($config,'sidebar.search.enabled',true))<label class="mt-4 block"><span class="text-sm font-medium text-slate-700">Ngưỡng hiển thị</span><input type="number" min="4" max="50" wire:model.live="config.sidebar.navigation_search_threshold" class="{{ $control }}"></label>@endif</div><div><div class="flex items-start justify-between gap-4"><div><h2 class="text-base font-semibold text-slate-900">Footer Sidebar</h2><p class="mt-1 text-sm text-slate-500">Thông tin tài khoản cuối Sidebar.</p></div><input type="checkbox" wire:model.live="config.sidebar.footer.enabled" class="{{ $toggle }}"></div><div class="mt-4 grid grid-cols-3 gap-2"><label class="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-700">Avatar<input type="checkbox" wire:model.live="config.sidebar.footer.show_avatar" class="{{ $toggle }}"></label><label class="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-700">Tên<input type="checkbox" wire:model.live="config.sidebar.footer.show_name" class="{{ $toggle }}"></label><label class="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-700">Subtitle<input type="checkbox" wire:model.live="config.sidebar.footer.show_subtitle" class="{{ $toggle }}"></label></div>@if(data_get($config,'sidebar.footer.show_subtitle',true))<label class="mt-4 block"><span class="text-sm font-medium text-slate-700">Nội dung Subtitle</span><input type="text" maxlength="80" wire:model.live.debounce.300ms="config.sidebar.footer.subtitle" class="{{ $control }}"></label>@endif</div></div></section>
            </div>

            <aside class="xl:sticky xl:top-24" aria-label="Xem trước Sidebar">
                <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-lg shadow-slate-950/5"><div class="border-b border-slate-100 px-4 py-3"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold text-slate-900">Sidebar preview</h2><p class="mt-0.5 text-xs text-slate-500">Visual hierarchy gần runtime thật.</p></div><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700 ring-1 ring-emerald-200">LIVE</span></div></div><div class="p-4">
                    <div class="mx-auto flex h-[34rem] w-[17rem] flex-col overflow-hidden rounded-2xl shadow-xl ring-1 ring-black/5 transition-colors" :style="`background:${bg()};color:${text()}`">
                        <div class="flex min-h-16 items-center gap-3 border-b px-3" :style="`border-color:${border()}`"><span class="flex h-9 w-9 items-center justify-center rounded-xl text-xs font-bold shadow-sm" :style="`background:${accent()};color:${activeText()}`">A</span><div class="min-w-0"><div class="truncate text-sm font-semibold">Admin Workspace</div><div class="truncate text-[10px]" :style="`color:${muted()}`">Không gian quản trị</div></div><span class="ml-auto h-8 w-8 rounded-xl border" :style="`background:${soft()};border-color:${border()}`"></span></div>
                        <div class="px-3 pt-3"><div class="flex h-9 items-center gap-2 rounded-xl border px-3 text-[11px]" :style="`background:${soft()};border-color:${border()};color:${muted()}`"><span>⌕</span><span>Tìm chức năng...</span></div></div>
                        <div class="flex-1 px-2 py-3"><div class="px-2 pb-2 text-[9px] font-semibold uppercase tracking-[.16em]" :style="`color:${muted()}`">Điều hướng</div><div class="space-y-1.5"><div class="flex h-10 items-center gap-3 rounded-xl px-3 text-xs font-semibold shadow-sm" :style="`background:${accent()};color:${activeText()}`"><span>◈</span><span>Tổng quan</span></div><div class="flex h-10 items-center gap-3 rounded-xl px-3 text-xs" :style="`background:${soft()};color:${secondary()}`"><span>▦</span><span>Quản lý dữ liệu</span><span class="ml-auto opacity-50">›</span></div><div class="ml-5 space-y-1 border-l pl-3" :style="`border-color:${border()}`"><div class="rounded-lg px-3 py-2 text-[11px]" :style="`color:${muted()}`">Danh mục</div><div class="rounded-lg px-3 py-2 text-[11px]" :style="`color:${muted()}`">Dữ liệu nhập</div></div><div class="flex h-10 items-center gap-3 rounded-xl px-3 text-xs" :style="`color:${secondary()}`"><span>▥</span><span>Báo cáo</span></div><div class="flex h-10 items-center gap-3 rounded-xl px-3 text-xs" :style="`color:${secondary()}`"><span>⚙</span><span>Cấu hình</span></div></div></div>
                        <div class="border-t p-3" :style="`border-color:${border()}`"><div class="flex items-center gap-3 rounded-xl px-2 py-2" :style="`background:${soft()}`"><span class="flex h-9 w-9 items-center justify-center rounded-xl text-xs font-bold" :style="`background:${accent()};color:${activeText()}`">T</span><div class="min-w-0"><div class="truncate text-xs font-semibold">Từ Ngọc Vân</div><div class="truncate text-[10px]" :style="`color:${muted()}`">Tài khoản quản trị</div></div></div></div>
                    </div><div class="mt-4 flex items-center justify-between text-xs text-slate-500"><span>Expanded <strong class="text-slate-700">{{ $expandedWidthPx }}px</strong></span><span>Collapsed <strong class="text-slate-700">{{ $collapsedWidthPx }}px</strong></span></div>
                </div></div>
            </aside>
        </div>
        @if ($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Có cấu hình Sidebar chưa hợp lệ. Kiểm tra màu HEX và các trường bắt buộc.</div>@endif
        <div class="sticky bottom-4 z-20 flex justify-end"><button type="submit" wire:loading.attr="disabled" class="inline-flex h-11 items-center justify-center rounded-xl bg-indigo-600 px-6 text-sm font-semibold text-white shadow-lg shadow-indigo-600/20 transition hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:opacity-60"><span wire:loading.remove wire:target="save">Lưu Sidebar</span><span wire:loading wire:target="save">Đang lưu...</span></button></div>
    </form>
</div>
