<?php

return [
    'key' => 'request',
    'source_module' => 'Request',
    'name' => 'Đề nghị & Phê duyệt',
    'description' => 'Tạo và theo dõi đề nghị cá nhân, đồng thời xử lý các công việc phê duyệt được giao.',
    'icon' => 'clipboard-document-check',
    'route' => 'client.request.dashboard',
    'permission' => 'client.request.access',
    'sort_order' => 20,
    'layout' => ['mode' => 'workspace'],
    'capabilities' => ['search', 'filter', 'background-jobs'],
    'quick_actions' => [
        'create' => [
            'name' => 'Tạo đề nghị',
            'route' => 'client.request.catalog',
            'permission' => 'client.request.create.view',
            'icon' => 'plus-circle',
            'sort_order' => 10,
        ],
        'inbox' => [
            'name' => 'Cần phê duyệt',
            'route' => 'client.request.inbox',
            'permission' => 'client.request.inbox.view',
            'icon' => 'inbox',
            'sort_order' => 20,
        ],
    ],
    'navigation' => [
        'overview' => [
            'name' => 'Tổng quan',
            'route' => 'client.request.dashboard',
            'permission' => 'client.request.overview.view',
            'icon' => 'home',
            'sort_order' => 10,
        ],
        'create' => [
            'name' => 'Tạo đề nghị',
            'route' => 'client.request.catalog',
            'permission' => 'client.request.create.view',
            'icon' => 'plus-circle',
            'sort_order' => 20,
        ],
        'mine' => [
            'name' => 'Của tôi',
            'route' => 'client.request.mine',
            'permission' => 'client.request.mine.view',
            'icon' => 'document-text',
            'sort_order' => 30,
        ],
        'inbox' => [
            'name' => 'Phê duyệt',
            'route' => 'client.request.inbox',
            'permission' => 'client.request.inbox.view',
            'icon' => 'inbox',
            'sort_order' => 40,
        ],
        'processed' => [
            'name' => 'Đã xử lý',
            'route' => 'client.request.processed',
            'permission' => 'client.request.processed.view',
            'icon' => 'check-circle',
            'placement' => 'more',
            'sort_order' => 50,
        ],
    ],
    'features' => [
        'overview' => [
            'name' => 'Tổng quan',
            'description' => 'Theo dõi nhanh đề nghị của bạn và khối lượng công việc cần phê duyệt.',
            'route' => 'client.request.dashboard',
            'permission' => 'client.request.overview.view',
            'sort_order' => 10,
        ],
        'create' => [
            'name' => 'Tạo đề nghị',
            'description' => 'Chọn loại đề nghị và bắt đầu một đề nghị mới.',
            'route' => 'client.request.catalog',
            'permission' => 'client.request.create.view',
            'sort_order' => 20,
        ],
        'mine' => [
            'name' => 'Đề nghị của tôi',
            'description' => 'Theo dõi bản nháp, đề nghị đang xử lý, cần bổ sung và đã hoàn tất.',
            'route' => 'client.request.mine',
            'permission' => 'client.request.mine.view',
            'sort_order' => 30,
        ],
        'inbox' => [
            'name' => 'Cần phê duyệt',
            'description' => 'Xem các công việc đang chờ bạn xem xét và quyết định.',
            'route' => 'client.request.inbox',
            'permission' => 'client.request.inbox.view',
            'sort_order' => 40,
        ],
        'processed' => [
            'name' => 'Đã xử lý',
            'description' => 'Tra cứu các công việc phê duyệt bạn đã xử lý.',
            'route' => 'client.request.processed',
            'permission' => 'client.request.processed.view',
            'sort_order' => 50,
        ],
    ],
];
