@extends('Admin::layouts.master')
@section('title','Sửa KQLCNT '.$awardItem->notify_no)
@section('content')
@php($input='mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500')
<div class="space-y-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">KQLCNT canonical</p><h1 class="mt-1 text-2xl font-bold text-gray-900">Sửa dữ liệu {{ $awardItem->notify_no }}</h1><p class="mt-1 text-sm text-gray-500">Chỉnh sửa bản dữ liệu quản trị. Dữ liệu API/import gốc không bị thay đổi.</p></div><div class="flex gap-2"><a href="{{ route('muasamcong.kqlcnt-awards.index') }}" class="rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700">← Danh sách KQLCNT</a>@if($awardItem->contractor_search_id)<a href="{{ route('muasamcong.contractors.kqlcnt-recovery',$awardItem->contractor_search_id) }}" class="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-700">Mở lịch sử TBMT</a>@endif</div></div>
@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">Vui lòng kiểm tra lại các trường chưa hợp lệ.</div>@endif
<form method="POST" action="{{ route('muasamcong.kqlcnt-awards.update',$awardItem) }}" class="space-y-5">@csrf @method('PUT')
<section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-base font-bold text-gray-900">Thông tin KQLCNT & nhà thầu</h2><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><div class="rounded-xl bg-gray-50 p-3"><div class="text-xs font-semibold text-gray-500">Mã TBMT</div><div class="mt-1 font-semibold">{{ $awardItem->notify_no }}</div></div><div class="rounded-xl bg-gray-50 p-3"><div class="text-xs font-semibold text-gray-500">Nhà thầu</div><div class="mt-1 font-semibold">{{ $awardItem->contractor_name }}</div><div class="text-xs text-gray-500">{{ $awardItem->contractor_code }}</div></div><label class="text-xs font-semibold text-gray-700">Trạng thái<select name="is_active" class="{{ $input }}"><option value="1" @selected(old('is_active',$awardItem->is_active)==1)>Đang hoạt động</option><option value="0" @selected(old('is_active',$awardItem->is_active)==0)>Ngưng</option></select></label><label class="text-xs font-semibold text-gray-700">Mã lô<input name="lot_no" value="{{ old('lot_no',$awardItem->lot_no) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700">Tên lô<input name="lot_name" value="{{ old('lot_name',$awardItem->lot_name) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700">Số hợp đồng<input name="contract_no" value="{{ old('contract_no',$awardItem->contract_no) }}" class="{{ $input }}"></label></div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-base font-bold text-gray-900">Thông tin thuốc</h2><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach(['medicine_code'=>'Mã thuốc','medicine_name'=>'Tên thuốc','drug_group'=>'Nhóm thuốc','active_ingredient'=>'Hoạt chất','concentration'=>'Hàm lượng','route'=>'Đường dùng','dosage_form'=>'Dạng bào chế','packaging_spec'=>'Quy cách','registration_or_import_license'=>'GĐKLH hoặc GPNK','unit'=>'ĐVT'] as $name=>$label)<label class="text-xs font-semibold text-gray-700">{{ $label }}<input name="{{ $name }}" value="{{ old($name,$awardItem->$name) }}" class="{{ $input }}"></label>@endforeach<label class="text-xs font-semibold text-gray-700">Hạn dùng (tháng)<input type="number" min="0" name="shelf_life_months" value="{{ old('shelf_life_months',$awardItem->shelf_life_months) }}" class="{{ $input }}"></label></div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-base font-bold text-gray-900">Giá, số lượng & sản xuất</h2><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach(['quantity'=>'Số lượng','price_plan'=>'Giá kế hoạch','winning_price'=>'Giá trúng thầu','amount'=>'Thành tiền'] as $name=>$label)<label class="text-xs font-semibold text-gray-700">{{ $label }}<input type="number" step="0.0001" min="0" name="{{ $name }}" value="{{ old($name,$awardItem->$name) }}" class="{{ $input }}"></label>@endforeach<label class="text-xs font-semibold text-gray-700">Nhà sản xuất<input name="manufacturer" value="{{ old('manufacturer',$awardItem->manufacturer) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700">Nước SX<input name="country" value="{{ old('country',$awardItem->country) }}" class="{{ $input }}"></label></div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-base font-bold text-gray-900">Quyết định & chủ đầu tư</h2><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label class="text-xs font-semibold text-gray-700">Số quyết định<input name="decision_no" value="{{ old('decision_no',$awardItem->decision_no) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700">Ngày quyết định<input type="date" name="decision_date" value="{{ old('decision_date',optional($awardItem->decision_date)->format('Y-m-d')) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700">Ngày đăng KQLCNT<input type="datetime-local" name="published_at" value="{{ old('published_at',optional($awardItem->published_at)->format('Y-m-d\TH:i')) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700">Mã chủ đầu tư<input name="investor_code" value="{{ old('investor_code',$awardItem->investor_code) }}" class="{{ $input }}"></label><label class="text-xs font-semibold text-gray-700 md:col-span-2">Chủ đầu tư<input name="investor_name" value="{{ old('investor_name',$awardItem->investor_name) }}" class="{{ $input }}"></label></div></section>
<section class="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 class="text-sm font-bold text-slate-900">Metadata đồng bộ</h2><div class="mt-3 grid gap-3 text-sm md:grid-cols-3"><div><span class="text-xs text-slate-500">Nguồn dữ liệu</span><div class="font-semibold">{{ $awardItem->source ?: '—' }}</div></div><div><span class="text-xs text-slate-500">Nguồn đồng bộ</span><div class="font-semibold">{{ $awardItem->sync_source ?: '—' }}</div></div><div><span class="text-xs text-slate-500">Đồng bộ lúc</span><div class="font-semibold">{{ optional($awardItem->synced_from_catalog_at)->format('d/m/Y H:i:s') ?: '—' }}</div></div></div></section>
<div class="sticky bottom-4 flex justify-end gap-2 rounded-2xl border border-gray-200 bg-white/95 p-3 shadow-lg backdrop-blur"><a href="{{ route('muasamcong.kqlcnt-awards.index') }}" class="rounded-xl border border-gray-300 px-5 py-2.5 text-sm font-semibold text-gray-700">Hủy</a><button class="rounded-xl bg-indigo-600 px-6 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">Lưu thay đổi</button></div></form></div>
@endsection
