@extends('Admin::layouts.master')
@section('title', 'Dữ liệu KQLCNT đã đồng bộ')
@section('content')
<div class="space-y-6">
<div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Mua sắm công</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Dữ liệu chi tiết KQLCNT</h1><p class="mt-1 text-sm text-gray-500">Kho dữ liệu canonical phục vụ quản trị, tra cứu và thống kê kết quả lựa chọn nhà thầu.</p></div><div class="flex flex-wrap gap-2">@include('Muasamcong::partials.dashboard-return-link')<button form="award-export-form" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-700">Xuất Excel</button></div></div>
<form method="GET" class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-sm font-bold text-gray-900">Bộ lọc dữ liệu</h2><p class="mt-0.5 text-xs text-gray-500">Các danh mục TBMT, nhà thầu và thuốc chỉ hiển thị giá trị duy nhất đã lưu.</p></div></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
<label class="text-xs font-semibold text-gray-700">Mã TBMT<input list="notify-options" name="notify_no" value="{{ $filters['notify_no'] }}" placeholder="Tìm Mã TBMT..." class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500"><datalist id="notify-options">@foreach($notifyOptions as $value)<option value="{{ $value }}">@endforeach</datalist></label>
<label class="text-xs font-semibold text-gray-700">Nhà thầu<input list="contractor-options" name="contractor_code" value="{{ $filters['contractor_code'] }}" placeholder="Tìm mã hoặc tên nhà thầu..." class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500"><datalist id="contractor-options">@foreach($contractorOptions as $option)<option value="{{ $option->contractor_code }}">{{ $option->contractor_name }}</option>@endforeach</datalist></label>
<label class="text-xs font-semibold text-gray-700">Tên thuốc<input list="medicine-options" name="medicine_name" value="{{ $filters['medicine_name'] }}" placeholder="Tìm tên thuốc..." class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500"><datalist id="medicine-options">@foreach($medicineOptions as $value)<option value="{{ $value }}">@endforeach</datalist></label>
<label class="text-xs font-semibold text-gray-700">Hoạt chất<input name="active_ingredient" value="{{ $filters['active_ingredient'] }}" placeholder="Gõ một phần hoạt chất..." class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></label>
<label class="text-xs font-semibold text-gray-700">Nguồn dữ liệu<input name="source" value="{{ $filters['source'] }}" placeholder="API, import, mixed..." class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm"></label>
<label class="text-xs font-semibold text-gray-700">Trạng thái<select name="active" class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm"><option value="">Tất cả</option><option value="1" @selected($filters['active']==='1')>Đang hoạt động</option><option value="0" @selected($filters['active']==='0')>Ngưng</option></select></label>
<label class="text-xs font-semibold text-gray-700">Ngày KQLCNT từ<input type="date" name="published_from" value="{{ $filters['published_from'] }}" class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm"></label><label class="text-xs font-semibold text-gray-700">đến<input type="date" name="published_to" value="{{ $filters['published_to'] }}" class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm"></label><label class="text-xs font-semibold text-gray-700">Ngày đồng bộ từ<input type="date" name="synced_from" value="{{ $filters['synced_from'] }}" class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm"></label><label class="text-xs font-semibold text-gray-700">đến<input type="date" name="synced_to" value="{{ $filters['synced_to'] }}" class="mt-1.5 block w-full rounded-xl border-gray-300 bg-white text-sm shadow-sm"></label>
</div><div class="mt-5 flex justify-end gap-2 border-t border-gray-100 pt-4"><a href="{{ route('muasamcong.kqlcnt-awards.index') }}" class="rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700 hover:bg-gray-50">Xóa bộ lọc</a><button class="rounded-xl bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-gray-800">Áp dụng bộ lọc</button></div></form>
<form id="award-export-form" method="POST" action="{{ route('muasamcong.kqlcnt-awards.export') }}">@csrf @foreach($filters as $key=>$value)@if($value!=='')<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50"><tr><th class="px-3 py-3"><input type="checkbox" onclick="document.querySelectorAll('.award-row').forEach(i=>i.checked=this.checked)"></th><th class="px-3 py-3 text-left">Mã TBMT</th><th class="px-3 py-3 text-left">Nhà thầu</th><th class="px-3 py-3 text-left">Thuốc / Hoạt chất</th><th class="px-3 py-3 text-right">SL</th><th class="px-3 py-3 text-right">Giá trúng</th><th class="px-3 py-3 text-right">Thành tiền</th><th class="px-3 py-3 text-left">Nguồn</th><th class="px-3 py-3 text-left">Đồng bộ</th><th class="px-3 py-3"></th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($items as $item)<tr class="align-top hover:bg-gray-50/70"><td class="px-3 py-3"><input class="award-row" type="checkbox" name="selected_ids[]" value="{{ $item->id }}"></td><td class="px-3 py-3 font-semibold text-gray-900">{{ $item->notify_no }}<div class="mt-1 text-xs font-normal text-gray-500">{{ $item->lot_no ?: 'Chưa có mã lô' }}</div></td><td class="px-3 py-3">{{ $item->contractor_name }}<div class="text-xs text-gray-500">{{ $item->contractor_code }}</div></td><td class="px-3 py-3"><span class="font-medium">{{ $item->medicine_name ?: '—' }}</span><div class="text-xs text-gray-500">{{ $item->active_ingredient ?: '—' }} {{ $item->concentration }}</div></td><td class="px-3 py-3 text-right tabular-nums">{{ is_null($item->quantity)?'—':number_format((float)$item->quantity,0,',','.') }}</td><td class="px-3 py-3 text-right tabular-nums">{{ is_null($item->winning_price)?'—':number_format((float)$item->winning_price,0,',','.') }}</td><td class="px-3 py-3 text-right tabular-nums">{{ is_null($item->amount)?'—':number_format((float)$item->amount,0,',','.') }}</td><td class="px-3 py-3 text-xs">{{ $item->source ?: $item->sync_source ?: '—' }}</td><td class="px-3 py-3 text-xs">{{ optional($item->synced_from_catalog_at)->format('d/m/Y H:i') ?: '—' }}<div class="mt-1 {{ $item->is_active?'text-emerald-700':'text-gray-500' }}">{{ $item->is_active?'Đang hoạt động':'Ngưng' }}</div></td><td class="px-3 py-3 text-right"><a href="{{ route('muasamcong.kqlcnt-awards.edit',$item) }}" class="inline-flex rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700 hover:bg-indigo-100">Sửa</a></td></tr>@empty<tr><td colspan="10" class="px-4 py-10 text-center text-gray-500">Chưa có dữ liệu KQLCNT canonical phù hợp.</td></tr>@endforelse</tbody></table></div></div></form><div>{{ $items->links() }}</div></div>
@endsection
