@extends('Admin::layouts.master')
@section('title', 'Chi tiết KQLCNT '.$awardItem->notify_no)
@section('content')
@php($fields = [
'Mã TBMT'=>$awardItem->notify_no,'Mã lô'=>$awardItem->lot_no,'Tên lô'=>$awardItem->lot_name,'Mã nhà thầu'=>$awardItem->contractor_code,'Tên nhà thầu'=>$awardItem->contractor_name,
'Mã thuốc'=>$awardItem->medicine_code,'Tên thuốc'=>$awardItem->medicine_name,'Nhóm thuốc'=>$awardItem->drug_group,'Hoạt chất'=>$awardItem->active_ingredient,'Hàm lượng'=>$awardItem->concentration,'Đường dùng'=>$awardItem->route,'Dạng bào chế'=>$awardItem->dosage_form,'Quy cách'=>$awardItem->packaging_spec,'Hạn dùng (tháng)'=>$awardItem->shelf_life_months,'GĐKLH hoặc GPNK'=>$awardItem->registration_or_import_license,'ĐVT'=>$awardItem->unit,
'Số lượng'=>$awardItem->quantity,'Giá kế hoạch'=>$awardItem->price_plan,'Giá trúng thầu'=>$awardItem->winning_price,'Thành tiền'=>$awardItem->amount,'Nhà sản xuất'=>$awardItem->manufacturer,'Nước SX'=>$awardItem->country,'Số quyết định'=>$awardItem->decision_no,'Ngày quyết định'=>optional($awardItem->decision_date)->format('d/m/Y'),'Ngày đăng KQLCNT'=>optional($awardItem->published_at)->format('d/m/Y H:i'),'Mã chủ đầu tư'=>$awardItem->investor_code,'Chủ đầu tư'=>$awardItem->investor_name,'Số hợp đồng'=>$awardItem->contract_no,'Nguồn dữ liệu'=>$awardItem->source,'Nguồn đồng bộ'=>$awardItem->sync_source,'Đồng bộ lúc'=>optional($awardItem->synced_from_catalog_at)->format('d/m/Y H:i:s')])
<div class="space-y-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">KQLCNT canonical</p><h1 class="mt-1 text-2xl font-bold text-gray-900">{{ $awardItem->notify_no }}</h1><p class="mt-1 text-sm text-gray-500">Chi tiết dữ liệu trúng thầu đã lưu trong CSDL quản trị.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('muasamcong.kqlcnt-awards.index') }}" class="rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700">← Danh sách KQLCNT</a>@if($awardItem->contractor_search_id)<a href="{{ route('muasamcong.contractors.kqlcnt-recovery', $awardItem->contractor_search_id) }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Mở lịch sử TBMT</a>@endif</div></div>
<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($fields as $label=>$value)<div class="rounded-xl border border-gray-200 bg-white p-4"><div class="text-xs font-semibold uppercase tracking-wide text-gray-500">{{ $label }}</div><div class="mt-2 break-words text-sm font-medium text-gray-900">{{ filled($value) ? $value : '—' }}</div></div>@endforeach</div></div>
@endsection
