<?php

return [
    'sections' => [
        'hero' => [
            'type' => 'hero',
            'label' => 'Banner Slider',
            'description' => 'Slider chính đầu trang',
            'renderer' => 'website.home.hero-banner',
            'duplicatable' => true,
        ],
        'categories' => [
            'type' => 'category_grid',
            'label' => 'Danh mục nổi bật',
            'description' => 'Lưới hình ảnh danh mục',
            'renderer' => 'website.home.category-highlight',
            'props' => ['categoryIds' => 'categoryIds'],
            'duplicatable' => true,
        ],
        'flash_sale' => [
            'type' => 'flash_sale',
            'label' => 'Flash Sale',
            'description' => 'Sản phẩm giảm giá có đếm ngược',
            'renderer' => 'website.home.flash-sale',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'featured' => [
            'type' => 'product_grid',
            'label' => 'Sản phẩm nổi bật',
            'description' => 'Khối sản phẩm ghim thủ công',
            'renderer' => 'website.home.featured-products',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'new_arrivals' => [
            'type' => 'product_grid',
            'label' => 'Hàng mới về',
            'description' => 'Sản phẩm mới nhất tự động',
            'renderer' => 'website.home.new-arrivals',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'best_sellers' => [
            'type' => 'product_grid',
            'label' => 'Top bán chạy',
            'description' => 'Sản phẩm bán chạy nhất',
            'renderer' => 'website.home.best-sellers',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'blog_highlight' => [
            'type' => 'post_grid',
            'label' => 'Tin tức / Blog',
            'description' => 'Bài viết mới nhất',
            'renderer' => 'website.home.blog-highlight',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'promo_banner' => [
            'type' => 'promo_banner',
            'label' => 'Banner Quảng cáo',
            'description' => 'Banner CTA quảng cáo',
            'renderer' => 'website.home.promo-banner',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'trust_badges' => [
            'type' => 'trust_badges',
            'label' => 'Các Icon service',
            'description' => 'Cam kết và dịch vụ nổi bật',
            'renderer' => 'website.home.trust-badges',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
        'newsletter' => [
            'type' => 'newsletter',
            'label' => 'Newsletter',
            'description' => 'Đăng ký nhận tin và ưu đãi',
            'renderer' => 'website.home.newsletter-signup',
            'params' => ['lazy' => true],
            'duplicatable' => true,
        ],
    ],
];
