@extends('Admin::layouts.master')
@section('title', 'Danh sách đã đồng bộ')
@section('content')
<div class="space-y-6"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Mua sắm công</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Danh sách đã đồng bộ</h1><p class="mt-1 text-sm text-gray-500">Quản lý các thuốc đã lưu vào database, bổ sung KQLCNT, cập nhật đơn vị trúng thầu và xóa dữ liệu không còn cần theo dõi.</p></div><div class="flex flex-wrap gap-2">@include('Muasamcong::partials.dashboard-return-link')@can('muasamcong.pricing.sync')<button type="button" onclick="exportSyncedScope()" class="inline-flex items-center justify-center rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-100">Xuất Excel</button><button type="button" onclick="exportSelectedBbg()" class="inline-flex items-center justify-center rounded-xl border border-amber-300 bg-amber-50 px-4 py-2.5 text-sm font-semibold text-amber-800">Xuất BBG đã chọn</button>@endcan<a href="{{ route('muasamcong.wishlist') }}" class="inline-flex items-center justify-center rounded-xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-semibold text-rose-700">♥ Wishlist</a><a href="{{ route('muasamcong.index') }}" class="inline-flex items-center justify-center rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700">← Về tra cứu thuốc</a></div></div><div class="rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-xs text-sky-800">Cấu hình xuất Excel trong danh sách này là nguồn cấu hình dùng chung cho Admin và Client PWA: cột dữ liệu, Header/Footer, logo, chữ ký và định dạng đều được tái sử dụng khi Client xuất Bảng Giá qua Queue.</div>@livewire('muasamcong.synced-pricing-list')</div>
@can('muasamcong.pricing.sync')
<script>
function syncedPricingComponent(){if(typeof Livewire==='undefined')return null;const cb=document.querySelector('input[wire\\:model\\.live="selectedIds"]'),root=cb?cb.closest('[wire\\:id]'):null;return root?Livewire.find(root.getAttribute('wire:id')):null}
function exportSyncedScope(){const component=syncedPricingComponent();if(!component){alert('Không tìm thấy danh sách đồng bộ.');return}const ids=component.get('selectedIds')||[],profileId=component.get('activeExportProfileId');const f=document.createElement('form');f.method='POST';f.action=@js(route('muasamcong.synced.export-selected'));f.innerHTML='<input type="hidden" name="_token" value="'+@js(csrf_token())+'">';if(profileId){const p=document.createElement('input');p.type='hidden';p.name='export_profile_id';p.value=profileId;f.appendChild(p)}if(Array.isArray(ids)){ids.forEach(id=>{const i=document.createElement('input');i.type='hidden';i.name='selected_ids[]';i.value=id;f.appendChild(i)})}document.body.appendChild(f);f.submit()}
function exportSelectedBbg(){const component=syncedPricingComponent();if(!component){alert('Không tìm thấy danh sách đồng bộ.');return}const ids=component.get('selectedIds')||[];if(!Array.isArray(ids)||!ids.length){alert('Vui lòng chọn ít nhất một bản ghi để xuất BBG.');return}const f=document.createElement('form');f.method='POST';f.action=@js(route('muasamcong.synced.export-bbg'));f.innerHTML='<input type="hidden" name="_token" value="'+@js(csrf_token())+'">';ids.forEach(id=>{const i=document.createElement('input');i.type='hidden';i.name='selected_ids[]';i.value=id;f.appendChild(i)});document.body.appendChild(f);f.submit()}
</script>
@endcan
@endsection
