<div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between mb-6 gap-4">
        <div><h1 class="text-2xl font-bold text-gray-900">Quản lý Vai trò (Roles)</h1><p class="mt-1 text-sm text-gray-500">Phân quyền truy cập cho nhân viên hệ thống.</p></div>
        <div class="flex flex-wrap gap-2">@can('create_role')<a href="{{ route('admin.role.create') }}" class="px-4 py-2 rounded-lg text-white bg-indigo-600 hover:bg-indigo-700 text-sm font-medium">Tạo vai trò mới</a>@endcan @if(auth('admin')->user()?->hasRole('Super Admin'))<button wire:click="previewPermissionSync" class="px-4 py-2 rounded-lg border border-emerald-300 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 text-sm font-medium">Quét & Đồng bộ phân quyền Modules</button>@endif</div>
    </div>
    <div class="mb-6 bg-white rounded-xl border border-gray-200 shadow-sm p-2 flex gap-2"><input wire:model.live.debounce.300ms="search" type="text" placeholder="Tìm kiếm vai trò..." class="block flex-1 rounded-lg border-gray-300 text-sm"><select wire:model.live="perPage" class="rounded-lg border-gray-300 text-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option></select></div>
    @if(count($selected) > 0)<div class="mb-4 p-3 bg-indigo-50 rounded-xl flex items-center justify-between"><span class="text-sm font-semibold text-indigo-900">Đã chọn {{ count($selected) }} vai trò</span>@can('delete_role')<button wire:click="deleteSelected" wire:confirm="Bạn có chắc muốn xóa các vai trò đã chọn?" class="px-4 py-2 bg-white border border-red-200 text-red-600 rounded-lg text-sm font-bold">Xóa</button>@endcan</div>@endif
    <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-4 py-3"></th><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Tên Vai trò</th><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Nhân sự</th><th class="px-6 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Guard</th><th class="px-6 py-3 text-right"></th></tr></thead><tbody class="divide-y divide-gray-200">@forelse($roles as $role)<tr class="hover:bg-gray-50"><td class="px-4 py-4 text-center">@if($role->name !== 'Super Admin')<input type="checkbox" value="{{ $role->id }}" wire:model.live="selected" class="rounded border-gray-300">@else<span title="Vai trò hệ thống">🔒</span>@endif</td><td class="px-6 py-4"><div class="font-bold text-gray-900">{{ $role->name }}</div>@if($role->name === 'Super Admin')<span class="text-xs text-red-700">System Core</span>@endif</td><td class="px-6 py-4 text-sm text-gray-600">{{ $role->users_count }} tài khoản</td><td class="px-6 py-4"><span class="font-mono text-xs">{{ $role->guard_name }}</span></td><td class="px-6 py-4 text-right text-sm">@if($role->name !== 'Super Admin')@can('edit_role')<a href="{{ route('admin.role.edit', $role->id) }}" class="text-indigo-600 font-bold mr-3">Sửa</a>@endcan @can('delete_role')<button wire:click="delete({{ $role->id }})" wire:confirm="Bạn có chắc muốn xóa vai trò này?" class="text-red-600 font-bold">Xóa</button>@endcan @else<span class="text-gray-400">Được bảo vệ</span>@endif</td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-gray-500">Chưa có vai trò nào.</td></tr>@endforelse</tbody></table><div class="bg-gray-50 border-t px-4 py-3">{{ $roles->links() }}</div></div>

    @if($showSyncModal)<div class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/50"><div class="bg-white rounded-xl shadow-xl w-full max-w-4xl overflow-hidden"><div class="px-6 py-4 border-b"><h3 class="text-lg font-bold">Quét & Đồng bộ phân quyền Modules</h3><p class="text-sm text-gray-500">Quét toàn bộ thư mục con cấp 1 trong Modules/. Đồng bộ chỉ bổ sung permission đã khai báo chính thức; không tự sinh và không xóa permission.</p></div>
        <div class="p-6 grid grid-cols-2 md:grid-cols-5 gap-3 text-sm"><div class="p-3 bg-gray-50 rounded-lg"><div class="text-gray-500">Filesystem</div><div class="text-xl font-bold">{{ $syncPreview['filesystem_modules'] ?? 0 }}</div></div><div class="p-3 bg-gray-50 rounded-lg"><div class="text-gray-500">Có catalog</div><div class="text-xl font-bold">{{ $syncPreview['modules_with_permissions'] ?? 0 }}</div></div><div class="p-3 bg-gray-50 rounded-lg"><div class="text-gray-500">Tổng quyền</div><div class="text-xl font-bold">{{ $syncPreview['total'] ?? 0 }}</div></div><div class="p-3 bg-amber-50 rounded-lg"><div class="text-amber-700">Thiếu DB</div><div class="text-xl font-bold">{{ $syncPreview['missing_count'] ?? 0 }}</div></div><div class="p-3 bg-indigo-50 rounded-lg"><div class="text-indigo-700">SA còn thiếu</div><div class="text-xl font-bold">{{ count($syncPreview['super_admin_missing'] ?? []) }}</div></div></div>
        @if(!empty($syncPreview['audit_warnings']))<div class="px-6 pb-5"><div class="font-semibold text-amber-800 mb-2">Cảnh báo cấu hình Modules ({{ count($syncPreview['audit_warnings']) }})</div><div class="max-h-64 overflow-auto border border-amber-200 rounded-lg divide-y divide-amber-100">@foreach($syncPreview['audit_warnings'] as $module)<div class="p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-2 bg-amber-50"><div><span class="font-semibold">{{ $module['name'] }}</span><span class="ml-2 text-xs text-gray-500">{{ $module['path'] }}</span></div><div class="text-sm">@if($module['status'] === 'missing_registry')<span class="text-red-700">Không có trong registry</span>@elseif($module['status'] === 'missing_manifest')<span class="text-red-700">Thiếu config/module.php</span>@elseif($module['status'] === 'missing_permissions')<span class="text-amber-800">Chưa khai báo permissions[]</span>@endif</div></div>@endforeach</div></div>@endif
        @if(!empty($syncPreview['missing']))<div class="px-6 pb-4"><div class="text-sm font-semibold mb-2">Permission hợp lệ sẽ được tạo:</div><div class="max-h-32 overflow-auto bg-gray-50 rounded-lg p-3 font-mono text-xs">{{ implode(', ', $syncPreview['missing']) }}</div></div>@endif
        <div class="px-6 py-4 bg-gray-50 flex justify-end gap-2"><button wire:click="$set('showSyncModal', false)" class="px-4 py-2 border rounded-lg">Hủy</button><button wire:click="syncModulePermissions" wire:confirm="Đồng bộ permission hợp lệ và bổ sung vào Super Admin? Các cảnh báo cấu hình sẽ không được tự sửa." class="px-4 py-2 bg-indigo-600 text-white rounded-lg font-semibold">Đồng bộ permission hợp lệ</button></div>
    </div></div>@endif
</div>
