<?php

return [
    'key' => 'pharma',
    'source_module' => 'Pharma',
    'name' => 'Pharma',
    'description' => 'Không gian làm việc Pharma dành cho User trên PWA, tách biệt với khu vực quản trị.',
    'icon' => 'beaker',
    'route' => 'client.pharma.dashboard',
    'permission' => 'client.pharma.access',
    'sort_order' => 20,
    'layout' => ['mode' => 'workspace'],
    'hub' => [
        'key' => 'overview',
        'name' => 'Tổng quan',
        'permission' => 'client.pharma.overview.view',
        'eyebrow' => 'Pharma PWA',
        'title' => 'Không gian làm việc Pharma',
        'description' => 'Các chức năng hiển thị theo quyền Web của User. Dữ liệu và business rules vẫn thuộc Modules/Pharma; PWA không sử dụng giao diện hoặc quyền Admin Pharma.',
        'supporting' => [
            'visible' => true,
            'title' => 'Làm việc theo phạm vi được giao',
            'body' => 'Chọn chức năng phù hợp với công việc của bạn. Mỗi workspace chỉ hiển thị dữ liệu và hành động theo quyền Web được cấp; nghiệp vụ và dữ liệu chuẩn tiếp tục do Modules/Pharma quản lý.',
        ],
    ],
    'capabilities' => ['search', 'filter', 'background-jobs', 'export'],
    'navigation' => [
        'overview' => [
            'name' => 'Tổng quan',
            'route' => 'client.pharma.dashboard',
            'permission' => 'client.pharma.overview.view',
            'icon' => 'home',
            'sort_order' => 10,
        ],
        'products' => [
            'name' => 'Danh mục thuốc',
            'route' => 'client.pharma.products',
            'permission' => 'client.pharma.products.view',
            'icon' => 'beaker',
            'sort_order' => 20,
            'actions' => [
                'supplier-pricing' => [
                    'name' => 'Xem giá nhà cung cấp',
                    'permission' => 'client.pharma.products.supplier-pricing',
                    'sort_order' => 10,
                ],
            ],
        ],
        'price-lists' => [
            'name' => 'Bảng giá của tôi',
            'route' => 'client.pharma.price-lists',
            'permission' => 'client.pharma.price-lists.view',
            'icon' => 'document-chart-bar',
            'sort_order' => 30,
            'actions' => [
                'create' => ['name' => 'Tạo bảng giá', 'permission' => 'client.pharma.price-lists.create', 'sort_order' => 10],
                'submit' => ['name' => 'Gửi duyệt bảng giá', 'permission' => 'client.pharma.price-lists.submit', 'sort_order' => 20],
                'approve' => ['name' => 'Phê duyệt bảng giá', 'permission' => 'client.pharma.price-lists.approve', 'sort_order' => 30],
            ],
        ],
        'orders' => [
            'name' => 'Đơn hàng',
            'route' => 'client.pharma.orders',
            'permission' => 'client.pharma.orders',
            'icon' => 'clipboard-document-list',
            'sort_order' => 60,
            'actions' => [
                'create' => [
                    'name' => 'Tạo đơn hàng',
                    'permission' => 'client.pharma.orders.create',
                    'sort_order' => 10,
                ],
                'submit' => [
                    'name' => 'Gửi duyệt đơn hàng',
                    'permission' => 'client.pharma.orders.submit',
                    'sort_order' => 20,
                ],
                'create-for-user' => [
                    'name' => 'Lên đơn thay User',
                    'permission' => 'client.pharma.orders.create-for-user',
                    'sort_order' => 30,
                ],
                'approve' => [
                    'name' => 'Phê duyệt đơn hàng',
                    'permission' => 'client.pharma.orders.approve',
                    'sort_order' => 40,
                ],
                'post' => [
                    'name' => 'Ghi sổ đơn hàng',
                    'permission' => 'client.pharma.orders.post',
                    'sort_order' => 50,
                ],
            ],
        ],
        'commissions' => [
            'name' => 'Hoa hồng của tôi',
            'route' => 'client.pharma.commissions',
            'permission' => 'client.pharma.commissions.view',
            'icon' => 'banknotes',
            'sort_order' => 80,
        ],
        'inventory' => [
            'name' => 'Tồn kho',
            'route' => 'client.pharma.inventory',
            'permission' => 'client.pharma.inventory.view',
            'icon' => 'archive-box',
            'sort_order' => 70,
        ],
    ],
    'features' => [
        'products' => [
            'name' => 'Danh mục thuốc',
            'description' => 'Tra cứu Medicine Master và thông tin sản phẩm theo phạm vi được cấp.',
            'eyebrow' => 'Medicine Catalog',
            'page_title' => 'Danh mục thuốc',
            'page_description' => 'Tra cứu danh mục chuẩn theo tên thuốc, mã thuốc, SKU, hoạt chất hoặc giấy phép lưu hành. PWA chỉ đọc và không thay đổi Medicine Master.',
            'route' => 'client.pharma.products',
            'permission' => 'client.pharma.products.view',
            'icon' => 'beaker',
            'sort_order' => 20,
        ],
        'price-lists' => [
            'name' => 'Bảng giá',
            'description' => 'Quản lý các bảng giá do User phụ trách và theo dõi vòng đời phê duyệt.',
            'eyebrow' => 'My Price Lists',
            'page_title' => 'Bảng giá của tôi',
            'page_description' => 'Chỉ hiển thị các bảng giá bạn là người phụ trách. Tạo, gửi duyệt và phê duyệt được kiểm soát theo quyền nghiệp vụ.',
            'route' => 'client.pharma.price-lists',
            'permission' => 'client.pharma.price-lists.view',
            'icon' => 'document-chart-bar',
            'sort_order' => 30,
            'actions' => [
                'create' => [
                    'name' => 'Tạo bảng giá',
                    'permission' => 'client.pharma.price-lists.create',
                    'sort_order' => 10,
                ],
                'submit' => [
                    'name' => 'Gửi duyệt bảng giá',
                    'permission' => 'client.pharma.price-lists.submit',
                    'sort_order' => 20,
                ],
                'approve' => [
                    'name' => 'Phê duyệt bảng giá',
                    'permission' => 'client.pharma.price-lists.approve',
                    'sort_order' => 30,
                ],
            ],
        ],
        'bid-awards' => [
            'name' => 'Trúng thầu',
            'description' => 'Theo dõi TBMT, sản phẩm trúng thầu và phạm vi bệnh viện được giao.',
            'eyebrow' => 'Bid Awards',
            'page_title' => 'Kết quả trúng thầu',
            'page_description' => 'Theo dõi kết quả trúng thầu và nhận biết nhanh phần sản phẩm được phân công phụ trách.',
            'route' => 'client.pharma.bid-awards',
            'permission' => 'client.pharma.bid-awards.view',
            'icon' => 'building-library',
            'actions' => [
                'allocate' => [
                    'name' => 'Phân bổ số lượng',
                    'permission' => 'client.pharma.bid-awards.allocate',
                    'sort_order' => 10,
                ],
                'commercial-policy' => [
                    'name' => 'Thiết lập chính sách kinh doanh',
                    'permission' => 'client.pharma.bid-awards.commercial-policy',
                    'sort_order' => 20,
                ],
            ],
            'sort_order' => 40,
        ],
        'commercial' => [
            'name' => 'Chính sách kinh doanh',
            'description' => 'Theo dõi chính sách và phân công thương mại thuộc phạm vi User.',
            'eyebrow' => 'Commercial Workspace',
            'page_title' => 'Công việc bệnh viện của tôi',
            'page_description' => 'Chọn Chủ đầu tư / kết quả trúng thầu để xem đúng phạm vi bệnh viện được phân công.',
            'route' => 'client.pharma.commercial',
            'permission' => 'client.pharma.commercial.view',
            'icon' => 'briefcase',
            'actions' => [
                'view-team' => [
                    'name' => 'Xem công việc User khác',
                    'permission' => 'client.pharma.commercial.view-team',
                    'sort_order' => 10,
                ],
            ],
            'sort_order' => 50,
        ],
        'orders' => [
            'name' => 'Đơn hàng',
            'description' => 'Lập và theo dõi đơn hàng theo bảng giá hoặc kết quả trúng thầu trong phạm vi User.',
            'eyebrow' => 'Orders',
            'page_title' => 'Đơn hàng',
            'page_description' => 'Theo dõi đơn hàng, nguồn giá và tiến trình xử lý thuộc phạm vi được giao.',
            'route' => 'client.pharma.orders',
            'permission' => 'client.pharma.orders',
            'icon' => 'clipboard-document-list',
            'sort_order' => 60,
            'actions' => [
                'create' => [
                    'name' => 'Tạo đơn hàng',
                    'permission' => 'client.pharma.orders.create',
                    'sort_order' => 10,
                ],
                'submit' => [
                    'name' => 'Gửi duyệt đơn hàng',
                    'permission' => 'client.pharma.orders.submit',
                    'sort_order' => 20,
                ],
                'create-for-user' => [
                    'name' => 'Lên đơn thay User',
                    'permission' => 'client.pharma.orders.create-for-user',
                    'sort_order' => 30,
                ],
                'approve' => [
                    'name' => 'Phê duyệt đơn hàng',
                    'permission' => 'client.pharma.orders.approve',
                    'sort_order' => 40,
                ],
                'post' => [
                    'name' => 'Ghi sổ đơn hàng',
                    'permission' => 'client.pharma.orders.post',
                    'sort_order' => 50,
                ],
            ],
        ],
        'inventory' => [
            'name' => 'Tồn kho',
            'description' => 'Theo dõi tồn kho, lô và hạn dùng của sản phẩm trong phạm vi được cấp.',
            'eyebrow' => 'Inventory',
            'page_title' => 'Tồn kho Pharma',
            'page_description' => 'Theo dõi số lượng tồn, giá trị, lô và hạn dùng để ưu tiên xử lý hàng sắp hết hạn.',
            'route' => 'client.pharma.inventory',
            'permission' => 'client.pharma.inventory.view',
            'icon' => 'archive-box',
            'sort_order' => 70,
            'actions' => [
                'costs' => [
                    'name' => 'Xem giá vốn và giá trị tồn',
                    'permission' => 'client.pharma.inventory.costs',
                    'sort_order' => 5,
                ],
                'receipts' => [
                    'name' => 'Phiếu nhập',
                    'permission' => 'client.pharma.inventory.receipts',
                    'sort_order' => 10,
                ],
                'receipts-create' => [
                    'name' => 'Lập phiếu nhập nháp',
                    'permission' => 'client.pharma.inventory.receipts.create',
                    'sort_order' => 20,
                ],
                'receipts-submit' => [
                    'name' => 'Gửi duyệt phiếu nhập',
                    'permission' => 'client.pharma.inventory.receipts.submit',
                    'sort_order' => 30,
                ],
                'receipts-approve' => [
                    'name' => 'Phê duyệt phiếu nhập',
                    'permission' => 'client.pharma.inventory.receipts.approve',
                    'sort_order' => 40,
                ],
                'receipts-post' => [
                    'name' => 'Ghi sổ phiếu nhập',
                    'permission' => 'client.pharma.inventory.receipts.post',
                    'sort_order' => 50,
                ],
            ],
        ],
        'commissions' => [
            'name' => 'Hoa hồng',
            'description' => 'Theo dõi hoa hồng thuộc phạm vi của User.',
            'eyebrow' => 'Commissions',
            'page_title' => 'Hoa hồng của tôi',
            'page_description' => 'Theo dõi doanh số và hoa hồng đã ghi nhận từ đơn hàng trúng thầu hoặc bảng giá thuộc chính tài khoản của bạn.',
            'route' => 'client.pharma.commissions',
            'permission' => 'client.pharma.commissions.view',
            'icon' => 'banknotes',
            'sort_order' => 80,
            'actions' => [
                'view-team' => [
                    'name' => 'Xem hoa hồng tất cả User',
                    'permission' => 'client.pharma.commissions.view-team',
                    'sort_order' => 10,
                ],
            ],
        ],
    ],
];
