<div class="px-4 sm:px-6 md:px-8" x-data="{ toolsOpen: false }">
    <div class="mb-5 flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
        <div>
            <h1 class="text-2xl font-bold tracking-tight text-gray-900">Quản lý Menu</h1>
            <p class="mt-1 text-sm text-gray-500">Tổ chức cấu trúc menu quản trị, phân quyền và thứ tự hiển thị.</p>
            <div class="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-gray-500">
                <span><strong class="font-semibold text-gray-900">{{ $totalMenus }}</strong> menu</span><span class="text-gray-300">•</span><span><strong class="font-semibold text-emerald-700">{{ $activeMenus }}</strong> hoạt động</span><span class="text-gray-300">•</span><span><strong class="font-semibold text-gray-700">{{ $totalMenus - $activeMenus }}</strong> đang tắt</span>
            </div>
        </div>
        <div class="flex flex-wrap items-center gap-2">
            <button type="button" wire:click="openRouteScannerModal" wire:loading.attr="disabled" wire:target="openRouteScannerModal" class="inline-flex items-center gap-2 rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-700 shadow-sm transition hover:bg-indigo-100 disabled:opacity-50"><span wire:loading.remove wire:target="openRouteScannerModal">Quét route</span><span wire:loading wire:target="openRouteScannerModal">Đang quét...</span></button>
            <a href="{{ route('admin.menus.create') }}" class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-indigo-700">Thêm menu</a>
            <div class="relative" @click.outside="toolsOpen = false">
                <button type="button" @click="toolsOpen = !toolsOpen" class="inline-flex items-center gap-2 rounded-xl border border-gray-300 bg-white px-4 py-2.5 text-sm font-semibold text-gray-700 shadow-sm hover:bg-gray-50">Công cụ</button>
                <div x-show="toolsOpen" x-transition x-cloak class="absolute right-0 z-40 mt-2 w-72 overflow-hidden rounded-xl border border-gray-200 bg-white py-1 shadow-xl">
                    <a href="{{ route('admin.layout.design') }}#sidebar-menu" class="flex items-center px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50">Thiết lập giao diện Menu</a>
                    <button type="button" wire:click="exportTemplate" @click="toolsOpen = false" class="flex w-full items-center px-4 py-2.5 text-left text-sm text-gray-700 hover:bg-gray-50">Tải Template Excel</button>
                    <button type="button" wire:click="export" @click="toolsOpen = false" class="flex w-full items-center justify-between gap-3 px-4 py-2.5 text-left text-sm text-gray-700 hover:bg-gray-50"><span>Export Excel</span>@if(!empty($selectedMenus))<span class="rounded-full bg-indigo-50 px-2 py-0.5 text-xs font-semibold text-indigo-700">{{ count($selectedMenus) }} đã chọn</span>@endif</button>
                    <button type="button" wire:click="openImportModal" @click="toolsOpen = false" class="flex w-full items-center px-4 py-2.5 text-left text-sm text-gray-700 hover:bg-gray-50">Import Menu</button>
                    <div class="my-1 border-t border-gray-100"></div>
                    <button type="button" wire:click="openSnapshotLibraryModal" wire:loading.attr="disabled" wire:target="openSnapshotLibraryModal" @click="toolsOpen = false" class="flex w-full items-center justify-between gap-3 px-4 py-2.5 text-left text-sm font-medium text-blue-700 hover:bg-blue-50 disabled:opacity-50"><span>Quản lý snapshot Google Drive</span><span class="text-xs text-blue-500">Library</span></button>
                    <button type="button" wire:click="restoreDefaultMenu" wire:confirm="Khôi phục menu từ snapshot local đã được kiểm tra? Thao tác này sẽ thay thế cấu trúc menu hiện tại." @click="toolsOpen = false" class="flex w-full items-center px-4 py-2.5 text-left text-sm font-medium text-amber-700 hover:bg-amber-50">Khôi phục snapshot</button>
                </div>
            </div>
        </div>
    </div>

    <div class="mb-5 grid gap-3 md:grid-cols-3">
        <div class="rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-sm"><div class="text-xs font-semibold uppercase tracking-wide text-gray-500">Snapshot local</div><div class="mt-1 text-sm font-semibold {{ $snapshotStatus['local_exists'] ? 'text-emerald-700' : 'text-amber-700' }}">{{ $snapshotStatus['local_exists'] ? 'Sẵn sàng' : 'Chưa có' }}</div><div class="mt-1 text-xs text-gray-500">storage/app/menu/menus.json</div></div>
        <div class="rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-sm"><div class="text-xs font-semibold uppercase tracking-wide text-gray-500">Google Drive</div><div class="mt-1 text-sm font-semibold {{ $snapshotStatus['cloud_connected'] ? 'text-emerald-700' : 'text-amber-700' }}">{{ $snapshotStatus['cloud_connected'] ? 'Đã kết nối' : 'Chưa kết nối' }}</div><div class="mt-1 text-xs text-gray-500">{{ $snapshotStatus['cloud_folder'] }}/{{ $snapshotStatus['cloud_path'] }}/*.json</div></div>
        <div class="rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-sm"><div class="text-xs font-semibold uppercase tracking-wide text-gray-500">Bản local cập nhật</div><div class="mt-1 text-sm font-semibold text-gray-800">{{ $snapshotStatus['local_modified_at'] ? \Illuminate\Support\Carbon::parse($snapshotStatus['local_modified_at'])->format('d/m/Y H:i') : '—' }}</div><div class="mt-1 text-xs text-gray-500">Chỉ “Đồng bộ về local” mới thay file này; Export Excel không thay snapshot.</div></div>
    </div>

    <section class="overflow-visible rounded-2xl border border-gray-200 bg-white shadow-sm">
        <div class="border-b border-gray-200 p-4 sm:p-5"><div class="flex flex-col gap-3 xl:flex-row xl:items-end"><div class="flex-1"><x-admin::form.input label="Tìm kiếm" type="search" wire:model.live.debounce.300ms="search" placeholder="Tìm theo tên hoặc URL..." /></div><div class="sm:w-56"><x-admin::form.select label="Trạng thái" wire:model.live="filterStatus"><option value="all">Tất cả</option><option value="active">Đang hoạt động</option><option value="inactive">Không hoạt động</option></x-admin::form.select></div><div class="flex flex-wrap items-center gap-2 xl:pb-0.5"><button type="button" @click="$dispatch('menu-tree-expand')" class="rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50">Mở rộng tất cả</button><button type="button" @click="$dispatch('menu-tree-collapse')" class="rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50">Thu gọn tất cả</button></div></div></div>
        <div x-data="menuSortable()" x-init="initSortable()" class="min-h-[420px] bg-gray-50/70 p-3 sm:p-4">
            <div class="mb-3 flex flex-col gap-2 rounded-xl border border-gray-200 bg-white px-3 py-2.5 sm:flex-row sm:items-center sm:justify-between"><label for="menu-select-all" class="flex cursor-pointer items-center gap-2 text-sm font-medium text-gray-700"><input id="menu-select-all" type="checkbox" wire:model.live="selectAll" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500">Chọn tất cả theo bộ lọc hiện tại</label><span class="text-xs text-gray-500">Kéo biểu tượng chấm để thay đổi thứ tự và phân cấp.</span></div>
            <ul id="root-menu-list" class="menu-list space-y-2">@foreach ($menus as $menu)<x-menu-item :menu="$menu" :selected="$selectedMenus" />@endforeach</ul>
            @if ($menus->isEmpty())<div class="rounded-xl border-2 border-dashed border-gray-300 bg-white py-12 text-center text-gray-500"><p class="text-base font-semibold text-gray-800">Không tìm thấy menu phù hợp</p></div>@endif
        </div>
    </section>

    @if (! empty($selectedMenus))
        <div class="sticky bottom-4 z-40 mx-auto mt-4 max-w-5xl rounded-2xl border border-indigo-200 bg-white/95 p-3 shadow-2xl backdrop-blur"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-2 text-sm text-gray-700"><span class="inline-flex h-7 min-w-7 items-center justify-center rounded-full bg-indigo-600 px-2 font-bold text-white">{{ count($selectedMenus) }}</span><span>menu đã chọn</span></div><div class="flex flex-wrap items-center gap-2"><button type="button" wire:click="bulkToggleStatus(true)" class="rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700">Bật</button><button type="button" wire:click="bulkToggleStatus(false)" class="rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700">Tắt</button><button type="button" wire:click="openBulkPermissionsModal" class="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700">Gán quyền</button><button type="button" wire:click="export" wire:loading.attr="disabled" wire:target="export" class="rounded-xl border border-indigo-200 bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700">Export đã chọn</button><button type="button" wire:click="requestBulkDelete" class="rounded-xl bg-red-600 px-3 py-2 text-sm font-bold text-white">Xóa</button></div></div></div>
    @endif

    @if ($showSnapshotModal)
        <div class="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/50 p-4 backdrop-blur-sm">
            <div class="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
                <div class="border-b border-gray-200 px-6 py-5"><div class="flex items-start justify-between gap-4"><div><h3 class="text-lg font-bold text-gray-900">Thư viện snapshot Menu</h3><p class="mt-1 text-sm text-gray-500">Tạo JSON snapshot trực tiếp từ DB lên Google Drive. Thao tác này không ghi file local và không tạo Excel.</p></div><button type="button" wire:click="closeSnapshotModal" class="rounded-lg px-3 py-2 text-sm font-semibold text-gray-500 hover:bg-gray-100">Đóng</button></div></div>
                <div class="overflow-y-auto p-6"><div class="grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.25fr)]">
                    <section class="rounded-2xl border border-gray-200 bg-gray-50 p-5">
                        <h4 class="text-sm font-bold text-gray-900">Tạo / cập nhật snapshot Drive</h4><p class="mt-1 text-xs text-gray-500">Nếu tên đã tồn tại, file Drive được cập nhật thay vì tạo bản trùng.</p>
                        <div class="mt-4"><div class="mb-2 text-sm font-semibold text-gray-700">Phạm vi snapshot</div><div class="space-y-2"><label class="flex items-start gap-3 rounded-xl border border-gray-200 bg-white p-3 {{ $selectedMenus === [] ? 'opacity-50' : '' }}"><input type="radio" wire:model.live="snapshotExportScope" value="selected" @disabled($selectedMenus === []) class="mt-0.5 border-gray-300 text-indigo-600"><span><span class="block text-sm font-semibold text-gray-900">Các menu đang chọn ({{ count($selectedMenus) }})</span><span class="block text-xs text-gray-500">JSON snapshot chỉ chứa menu đang chọn.</span></span></label><label class="flex items-start gap-3 rounded-xl border border-gray-200 bg-white p-3"><input type="radio" wire:model.live="snapshotExportScope" value="all" class="mt-0.5 border-gray-300 text-indigo-600"><span><span class="block text-sm font-semibold text-gray-900">Toàn bộ menu</span><span class="block text-xs text-gray-500">Tạo JSON snapshot toàn bộ cấu trúc menu.</span></span></label></div></div>
                        <div class="mt-4"><label for="snapshot-name" class="mb-1.5 block text-sm font-semibold text-gray-700">Tên snapshot</label><input id="snapshot-name" type="text" wire:model.live.debounce.250ms="snapshotName" maxlength="80" class="w-full rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm" placeholder="Ví dụ: Menu Kho">@error('snapshotName')<p class="mt-1 text-xs font-semibold text-red-600">{{ $message }}</p>@enderror</div>
                        <div class="mt-4 rounded-xl border border-indigo-100 bg-indigo-50 p-3"><div class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Google Drive đích</div><div class="mt-1 break-all font-mono text-xs text-indigo-900">{{ $snapshotStatus['cloud_folder'] }}/{{ $snapshotStatus['cloud_path'] }}/{{ $snapshotFilePreview }}</div></div>
                        <button type="button" wire:click="exportWithSnapshot" wire:loading.attr="disabled" wire:target="exportWithSnapshot" class="mt-4 inline-flex w-full items-center justify-center rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><span wire:loading.remove wire:target="exportWithSnapshot">{{ $snapshotExportScope === 'selected' ? 'Lưu snapshot '.count($selectedMenus).' menu lên Drive' : 'Lưu snapshot toàn bộ lên Drive' }}</span><span wire:loading wire:target="exportWithSnapshot">Đang lưu snapshot...</span></button>
                    </section>
                    <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white">
                        <div class="flex flex-col gap-3 border-b border-gray-200 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h4 class="text-sm font-bold text-gray-900">Snapshot trên Google Drive</h4><p class="mt-0.5 text-xs text-gray-500">{{ $snapshotStatus['cloud_folder'] }}/{{ $snapshotStatus['cloud_path'] }}</p></div><div class="flex gap-2">@if($selectedCloudSnapshotFiles !== [])<button type="button" wire:click="deleteSelectedSnapshots" wire:confirm="Xóa {{ count($selectedCloudSnapshotFiles) }} snapshot đã chọn khỏi Google Drive?" class="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs font-bold text-red-700">Xóa {{ count($selectedCloudSnapshotFiles) }} file</button>@endif<button type="button" wire:click="refreshSnapshotLibrary" class="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold text-gray-700">Làm mới</button></div></div>
                        @if ($snapshotListError)<div class="m-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{ $snapshotListError }}</div>@elseif ($cloudSnapshots === [])<div class="p-8 text-center text-sm text-gray-500">Chưa có snapshot Menu trên Drive.</div>@else<div class="max-h-[470px] divide-y divide-gray-100 overflow-y-auto">@foreach ($cloudSnapshots as $snapshot)<div class="px-4 py-3"><div class="flex items-start gap-3"><input type="checkbox" wire:model.live="selectedCloudSnapshotFiles" value="{{ $snapshot['name'] }}" class="mt-1 h-4 w-4 rounded border-gray-300 text-indigo-600"><div class="min-w-0 flex-1">@if($renamingSnapshotFile === $snapshot['name'])<div class="flex gap-2"><input type="text" wire:model="renameSnapshotName" class="min-w-0 flex-1 rounded-lg border border-gray-300 px-3 py-2 text-sm"><button type="button" wire:click="saveRenameSnapshot" class="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Lưu</button><button type="button" wire:click="cancelRenameSnapshot" class="rounded-lg border px-3 py-2 text-xs">Hủy</button></div>@else<div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><div class="break-all font-mono text-sm font-semibold text-gray-800">{{ $snapshot['name'] }}</div><div class="mt-1 text-xs text-gray-500">{{ number_format(((int) $snapshot['size']) / 1024, 1) }} KB · {{ $snapshot['modified_at'] ? \Illuminate\Support\Carbon::parse($snapshot['modified_at'])->format('d/m/Y H:i') : '—' }}</div></div><div class="flex flex-wrap gap-2"><button type="button" wire:click="syncSnapshotFromGoogleDrive('{{ $snapshot['name'] }}')" wire:confirm="Đồng bộ {{ $snapshot['name'] }} về storage/app/menu/menus.json? DB chưa thay đổi." class="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Đồng bộ về local</button><button type="button" wire:click="startRenameSnapshot('{{ $snapshot['name'] }}')" class="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold text-gray-700">Đổi tên</button></div></div>@endif</div></div></div>@endforeach</div>@endif
                    </section>
                </div></div>
            </div>
        </div>
    @endif

    @if ($showBulkDeleteModal)<div class="fixed inset-0 z-50 flex items-center justify-center bg-gray-900/50 p-4"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 class="text-lg font-bold">Xác nhận xóa menu</h3><p class="mt-2 text-sm text-gray-600">Bạn đang xóa {{ count($selectedMenus) }} menu đã chọn.</p><div class="mt-6 flex justify-end gap-3"><button wire:click="closeBulkDeleteModal" class="rounded-lg border px-4 py-2">Hủy</button><button wire:click="bulkDelete" class="rounded-lg bg-red-600 px-4 py-2 font-bold text-white">Xóa</button></div></div></div>@endif

    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.2/Sortable.min.js"></script>
    <script>function menuSortable(){return{sortables:[],initSortable(){this.$nextTick(()=>this.createSortables());Livewire.on('menu-reload',()=>this.$nextTick(()=>this.createSortables()))},createSortables(){this.destroySortables();document.querySelectorAll('.menu-list').forEach((el)=>{this.sortables.push(Sortable.create(el,{group:'nested',animation:150,handle:'.drag-handle',fallbackOnBody:true,swapThreshold:.65,onEnd:()=>this.saveOrder()}))})},destroySortables(){this.sortables.forEach((sortable)=>sortable.destroy());this.sortables=[]},saveOrder(){const getIds=(root)=>Array.from(root.children).filter((element)=>element.tagName==='LI').map((element)=>{const item={id:element.getAttribute('data-id')};const childList=element.querySelector(':scope > ul');if(childList&&childList.children.length>0)item.children=getIds(childList);return item});const rootList=document.getElementById('root-menu-list');if(rootList)@this.updateMenuOrder(getIds(rootList))}}}</script>
</div>
