<div class="space-y-5">
    @if($successMessage)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-medium text-emerald-800">{{ $successMessage }}</div>@endif
    @if($errorMessage)<div class="rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-medium text-red-800">{{ $errorMessage }}</div>@endif

    <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><div class="grid gap-3 lg:grid-cols-[1fr_220px_140px]">
        <x-search wire:model.live.debounce.300ms="search" placeholder="Thuốc, SĐK, nhà thầu, quyết định..." />
        <select wire:model.live="status" class="min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 shadow-sm"><option value="pending">Cần rà soát</option><option value="linked">Đã liên kết</option><option value="unmatched">Chưa liên kết</option><option value="all">Tất cả</option></select>
        <select wire:model.live="perPage" class="min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 shadow-sm">@foreach([10,25,50,100] as $size)<option value="{{ $size }}">{{ $size }} / trang</option>@endforeach</select>
    </div></div>

    <div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
        <div class="hidden overflow-x-auto lg:block"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50 text-left text-xs font-semibold uppercase tracking-wide text-gray-500"><tr><th class="px-5 py-3">Thuốc nguồn</th><th class="px-5 py-3">Kết quả trúng thầu</th><th class="px-5 py-3">Danh mục thuốc chuẩn</th><th class="px-5 py-3 text-right">Thao tác</th></tr></thead><tbody class="divide-y divide-gray-100">
        @forelse($awards as $award)<tr class="align-top"><td class="px-5 py-4"><div class="font-semibold text-gray-900">{{ $award->medicine_name }}</div><div class="mt-1 text-gray-500">SĐK: {{ $award->registration_or_import_license ?: '—' }}</div><div class="text-gray-500">{{ $award->concentration }} · {{ $award->packaging_specification }}</div></td><td class="px-5 py-4"><div class="font-semibold text-gray-900">{{ number_format((float)$award->winning_price,0,',','.') }} đ</div><div class="mt-1 text-gray-500">SL: {{ number_format((float)$award->quantity,0,',','.') }}</div><div class="text-gray-500">{{ $award->decision_number ?: 'Chưa có QĐ' }} · {{ optional($award->decision_date)->format('d/m/Y') ?: optional($award->published_at)->format('d/m/Y') ?: '—' }}</div><div class="text-gray-500">{{ $award->winning_company_name ?: '—' }}</div></td><td class="px-5 py-4"><div class="font-medium text-gray-900">{{ $award->canonicalMatch?->medicine?->name ?: 'Chưa liên kết' }}</div><div class="mt-1 text-gray-500">{{ $award->canonicalMatch?->medicine?->medicine_code ?: '—' }}</div><div class="text-gray-500">{{ $award->canonicalMatch?->variant?->sku ?: '—' }} · {{ $award->canonicalMatch?->package?->packaging_text ?: '—' }}</div><span class="mt-2 inline-flex rounded-full bg-gray-100 px-2.5 py-1 text-xs font-semibold text-gray-700">{{ $award->canonicalMatch?->review_status ?: 'pending' }}</span></td><td class="px-5 py-4 text-right"><button type="button" wire:click="selectAward({{ $award->id }})" class="rounded-xl border border-gray-300 px-3 py-2 font-semibold text-gray-700 hover:bg-gray-50">Rà soát</button></td></tr>
        @empty<tr><td colspan="4" class="px-5 py-10 text-center text-gray-500">Không có kết quả phù hợp.</td></tr>@endforelse
        </tbody></table></div>
        <div class="divide-y divide-gray-100 lg:hidden">@forelse($awards as $award)<button type="button" wire:click="selectAward({{ $award->id }})" class="block w-full p-4 text-left"><div class="flex items-start justify-between gap-3"><div><div class="font-semibold text-gray-900">{{ $award->medicine_name }}</div><div class="mt-1 text-xs text-gray-500">{{ $award->registration_or_import_license ?: 'Chưa có SĐK' }}</div></div><span class="rounded-full bg-gray-100 px-2 py-1 text-xs font-semibold text-gray-600">{{ $award->canonicalMatch?->review_status ?: 'pending' }}</span></div><div class="mt-3 grid grid-cols-2 gap-2 text-sm"><div><span class="text-gray-500">Đơn giá</span><div class="font-semibold">{{ number_format((float)$award->winning_price,0,',','.') }} đ</div></div><div><span class="text-gray-500">Ngày QĐ</span><div class="font-medium">{{ optional($award->decision_date)->format('d/m/Y') ?: optional($award->published_at)->format('d/m/Y') ?: '—' }}</div></div></div><div class="mt-3 text-sm text-gray-600">Danh mục chuẩn: {{ $award->canonicalMatch?->medicine?->medicine_code ?: 'Chưa liên kết' }}</div></button>@empty<div class="p-8 text-center text-gray-500">Không có kết quả phù hợp.</div>@endforelse</div>
        <div class="border-t border-gray-100 p-4">{{ $awards->links() }}</div>
    </div>

    @if($selectedAward)<div class="fixed inset-0 z-50 bg-gray-950/40" wire:click.self="closeReview"><div class="absolute inset-y-0 right-0 w-full overflow-y-auto bg-white shadow-2xl sm:max-w-2xl"><div class="sticky top-0 z-10 flex items-center justify-between border-b border-gray-200 bg-white px-5 py-4"><div><div class="text-lg font-bold text-gray-900">Rà soát liên kết Danh mục thuốc chuẩn</div><div class="text-sm text-gray-500">Kết quả #{{ $selectedAward->id }}</div></div><button type="button" wire:click="closeReview" class="rounded-xl border border-gray-300 px-3 py-2 text-sm font-semibold">Đóng</button></div><div class="space-y-5 p-5">
        <section class="rounded-2xl border border-gray-200 p-4"><h3 class="font-bold text-gray-900">Dữ liệu trúng thầu</h3><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-gray-500">Tên thuốc</dt><dd class="font-semibold">{{ $selectedAward->medicine_name }}</dd></div><div><dt class="text-gray-500">SĐK</dt><dd>{{ $selectedAward->registration_or_import_license ?: '—' }}</dd></div><div><dt class="text-gray-500">Đơn giá</dt><dd class="font-semibold">{{ number_format((float)$selectedAward->winning_price,0,',','.') }} đ</dd></div><div><dt class="text-gray-500">Số lượng</dt><dd>{{ number_format((float)$selectedAward->quantity,0,',','.') }}</dd></div><div><dt class="text-gray-500">Quyết định</dt><dd>{{ $selectedAward->decision_number ?: '—' }}</dd></div><div><dt class="text-gray-500">Ngày trúng thầu</dt><dd>{{ optional($selectedAward->decision_date)->format('d/m/Y') ?: optional($selectedAward->published_at)->format('d/m/Y') ?: '—' }}</dd></div><div class="col-span-2"><dt class="text-gray-500">Nhà thầu</dt><dd>{{ $selectedAward->winning_company_name ?: '—' }}</dd></div></dl></section>

        <section class="rounded-2xl border border-gray-200 p-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Danh mục thuốc chuẩn</p><h3 class="mt-1 font-bold text-gray-900">Liên kết mã thuốc chuẩn</h3><p class="mt-1 text-xs text-gray-500">Medicine là liên kết bắt buộc; SKU và Package được tự chọn khi chỉ có một lựa chọn xác định.</p></div><div class="mt-3"><x-search wire:model.live.debounce.300ms="candidateSearch" placeholder="Tên thuốc / Mã thuốc chuẩn / SĐK..." /></div><div class="mt-3 max-h-80 space-y-2 overflow-y-auto">
            @forelse($candidates as $medicine)<button type="button" wire:click="chooseMedicine({{ $medicine->id }})" class="block w-full rounded-xl border p-3 text-left transition {{ (int)$selectedMedicineId === $medicine->id ? 'border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500' : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50' }}"><div class="flex items-start gap-3"><span class="mt-1 h-4 w-4 rounded-full border {{ (int)$selectedMedicineId === $medicine->id ? 'border-indigo-600 bg-indigo-600 ring-2 ring-indigo-100' : 'border-gray-300' }}"></span><span><span class="block text-xs font-bold uppercase tracking-wide text-indigo-700">{{ $medicine->medicine_code ?: 'Chưa có mã thuốc' }}</span><span class="mt-0.5 block font-semibold text-gray-900">{{ $medicine->name }}</span><span class="block text-xs text-gray-500">SĐK: {{ $medicine->registration_number ?: '—' }}</span></span></div></button>@empty<div class="rounded-xl border border-dashed border-gray-300 p-4 text-sm text-gray-500">Không tìm thấy thuốc phù hợp trong Danh mục thuốc chuẩn.</div>@endforelse
        </div>
        @if($selectedMedicineId)@php($selectedMedicine = $candidates->firstWhere('id', (int)$selectedMedicineId))@if($selectedMedicine)<div class="mt-4 rounded-xl bg-gray-50 p-3"><div class="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-500">Liên kết đang chọn</div><div class="grid gap-2 sm:grid-cols-2"><select wire:model.live="selectedVariantId" class="min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm"><option value="">Chỉ liên kết Medicine</option>@foreach($selectedMedicine->variants as $variant)<option value="{{ $variant->id }}">{{ $variant->sku }} · {{ $variant->strength_text }}</option>@endforeach</select><select wire:model.live="selectedPackageId" class="min-h-11 w-full rounded-xl border border-gray-300 bg-white px-3 py-2 text-sm"><option value="">Chưa xác định Package</option>@foreach($selectedMedicine->variants->where('id',(int)$selectedVariantId)->flatMap->packages as $package)<option value="{{ $package->id }}">{{ $package->packaging_text }}</option>@endforeach</select></div></div>@endif@endif
        </section>

        @if($errorMessage)<div class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-800">{{ $errorMessage }}</div>@endif
        <div class="sticky bottom-0 grid grid-cols-2 gap-2 border-t border-gray-200 bg-white py-4 sm:grid-cols-4"><button type="button" wire:click="rematch" wire:loading.attr="disabled" class="rounded-xl border border-gray-300 px-3 py-2.5 text-sm font-semibold">Match lại</button><button type="button" wire:click="ignore" wire:loading.attr="disabled" class="rounded-xl border border-gray-300 px-3 py-2.5 text-sm font-semibold">Bỏ qua</button><button type="button" wire:click="closeReview" class="rounded-xl border border-gray-300 px-3 py-2.5 text-sm font-semibold">Hủy</button><button type="button" wire:click="confirmSelection" wire:loading.attr="disabled" wire:target="confirmSelection" class="rounded-xl bg-gray-900 px-3 py-2.5 text-sm font-semibold text-white"><span wire:loading.remove wire:target="confirmSelection">Xác nhận liên kết</span><span wire:loading wire:target="confirmSelection">Đang lưu...</span></button></div>
    </div></div></div>@endif
</div>
