<div class="space-y-6">
@if($successMessage)<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{{ $successMessage }}</div>@endif
@if($errorMessage)<div role="alert" class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-medium text-rose-700">{{ $errorMessage }}</div>@endif

<section class="rounded-2xl border border-gray-200 bg-white shadow-sm">
<div class="border-b border-gray-100 px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-indigo-600">Bước 1</p><h2 class="mt-1 text-lg font-bold text-gray-900">Thông tin bảng giá</h2></div>
<div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">
<div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Tên bảng giá *</label><input wire:model="name" class="mt-1 w-full rounded-xl border-gray-300" placeholder="BG Chung 2026">@error('name')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-medium text-gray-700">Mã bảng giá *</label><input wire:model="code" class="mt-1 w-full rounded-xl border-gray-300">@error('code')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-medium text-gray-700">Loại *</label><select wire:model.live="type" class="mt-1 w-full rounded-xl border-gray-300"><option value="global">Bảng giá chung</option><option value="customer">Bảng giá khách hàng</option></select></div>
@if($type==='customer')<div class="md:col-span-2"><label class="text-sm font-medium text-gray-700">Khách hàng *</label><select wire:model="partnerId" class="mt-1 w-full rounded-xl border-gray-300"><option value="">Chọn khách hàng</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select>@error('partnerId')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>@endif
<div><label class="text-sm font-medium text-gray-700">Ngày hiệu lực</label><input type="date" wire:model="effectiveFrom" class="mt-1 w-full rounded-xl border-gray-300"></div>
<div><label class="text-sm font-medium text-gray-700">Ngày hết hiệu lực</label><input type="date" wire:model="effectiveTo" class="mt-1 w-full rounded-xl border-gray-300"></div>
<div><label class="text-sm font-medium text-gray-700">Currency</label><input wire:model="currency" class="mt-1 w-full rounded-xl border-gray-300" maxlength="3"></div>
<div><label class="text-sm font-medium text-gray-700">Priority</label><input type="number" wire:model="priority" class="mt-1 w-full rounded-xl border-gray-300"></div>
<div class="md:col-span-2 xl:col-span-4"><label class="text-sm font-medium text-gray-700">Ghi chú</label><textarea wire:model="notes" rows="2" class="mt-1 w-full rounded-xl border-gray-300"></textarea></div>
</div></section>

<section class="rounded-2xl border border-gray-200 bg-white shadow-sm">
<div class="border-b border-gray-100 px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-indigo-600">Bước 2</p><h2 class="mt-1 text-lg font-bold text-gray-900">Chọn sản phẩm từ Medicine Master</h2><p class="mt-1 text-sm text-gray-500">Không sử dụng workbook nguồn. Selection được giữ khi đổi trang/tìm kiếm.</p></div>
<div class="grid gap-3 border-b border-gray-100 p-4 lg:grid-cols-[1fr_180px_180px_130px]">
<input type="search" wire:model.live.debounce.300ms="search" placeholder="Medicine code, tên thuốc, hoạt chất, GPLH, SKU, hàm lượng, quy cách..." class="rounded-xl border-gray-300 text-sm">
<select wire:model.live="catalogStatus" class="rounded-xl border-gray-300 text-sm"><option value="all">Mọi catalog status</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="needs_review">Needs review</option></select>
<select wire:model.live="specialControl" class="rounded-xl border-gray-300 text-sm"><option value="all">Tất cả KSĐB</option><option value="yes">KSĐB</option><option value="no">Không KSĐB</option></select>
<select wire:model.live="perPage" class="rounded-xl border-gray-300 text-sm">@foreach($perPageOptions as $option)<option value="{{ $option }}">{{ $option }} dòng</option>@endforeach</select>
</div>
<div class="flex flex-col gap-3 border-b border-gray-100 bg-gray-50/70 p-4 lg:flex-row lg:items-center lg:justify-between"><div class="text-sm text-gray-600"><strong>{{ $products->total() }}</strong> kết quả · <strong class="text-indigo-700">{{ count($selectedRows) }}</strong> đã chọn</div><button type="button" wire:click="clearSelection" class="text-sm font-semibold text-gray-600">Bỏ chọn</button></div>
<div class="overflow-x-auto"><table class="w-full min-w-[1500px] text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-3 py-3 text-center"><input type="checkbox" wire:model.live="selectPage" class="rounded border-gray-300"></th><th class="px-3 py-3">Medicine code</th><th class="px-3 py-3">Tên thuốc</th><th class="px-3 py-3">Hoạt chất / hàm lượng</th><th class="px-3 py-3">GPLH</th><th class="px-3 py-3">SKU</th><th class="px-3 py-3">Quy cách</th><th class="px-3 py-3 text-right">Giá kê khai</th><th class="px-3 py-3">Giá bán công ty</th><th class="px-3 py-3">Giá thu thực tế</th><th class="px-3 py-3">Giá xuất HĐ</th></tr></thead>
<tbody class="divide-y divide-gray-100">@forelse($products as $row)<tr wire:key="medicine-price-{{ $row->key }}" class="align-top hover:bg-gray-50"><td class="px-3 py-3 text-center"><input type="checkbox" wire:model.live="selectedRows" value="{{ $row->key }}" class="rounded border-gray-300"></td><td class="px-3 py-3 font-semibold">{{ $row->medicine_code }}</td><td class="px-3 py-3 font-medium text-gray-900">{{ $row->name }}</td><td class="px-3 py-3">{{ $row->active_ingredients ?: '-' }}<div class="text-xs text-gray-500">{{ $row->strength_text ?: $row->concentration }}</div></td><td class="px-3 py-3">{{ $row->registration_number ?: '-' }}</td><td class="px-3 py-3 font-mono text-xs">{{ $row->sku }}</td><td class="px-3 py-3">{{ $row->packaging_text ?: $row->packaging_specification ?: '-' }}</td><td class="px-3 py-3 text-right font-semibold">{{ $row->declared_price!==null ? number_format((float)$row->declared_price,0,',','.') . ' ₫' : '-' }}</td><td class="px-3 py-3"><input type="number" min="0" step="0.01" wire:model.blur="prices.{{ $row->key }}.company" class="w-36 rounded-lg border-gray-300 text-right" @disabled(!in_array($row->key,$selectedRows,true))>@if(in_array($row->key,$selectedRows,true) && ($prices[$row->key]['company'] ?? '')!=='' && $row->declared_price!==null && (float)$prices[$row->key]['company']>(float)$row->declared_price)<p class="mt-1 max-w-44 text-xs font-medium text-rose-600">Giá bán công ty không được vượt quá giá kê khai {{ number_format((float)$row->declared_price,0,',','.') }} ₫.</p>@endif</td><td class="px-3 py-3"><input type="number" min="0" step="0.01" wire:model.blur="prices.{{ $row->key }}.receivable" class="w-36 rounded-lg border-gray-300 text-right" @disabled(!in_array($row->key,$selectedRows,true))></td><td class="px-3 py-3"><input type="number" min="0" step="0.01" wire:model.blur="prices.{{ $row->key }}.invoice" class="w-36 rounded-lg border-gray-300 text-right" @disabled(!in_array($row->key,$selectedRows,true))></td></tr>@empty<tr><td colspan="11" class="px-6 py-12 text-center text-gray-500">Không tìm thấy SKU/package phù hợp.</td></tr>@endforelse</tbody></table></div>
<div class="flex items-center gap-2 border-t border-gray-100 p-4"><button type="button" wire:click="gotoPage({{ max(1,$products->currentPage()-1) }})" @disabled($products->onFirstPage()) class="rounded-lg border border-gray-300 px-3 py-2 text-sm disabled:opacity-40">Trước</button><span class="text-sm font-semibold">{{ $products->currentPage() }} / {{ max(1,$products->lastPage()) }}</span><button type="button" wire:click="gotoPage({{ min(max(1,$products->lastPage()),$products->currentPage()+1) }})" @disabled(!$products->hasMorePages()) class="rounded-lg border border-gray-300 px-3 py-2 text-sm disabled:opacity-40">Sau</button></div>
</section>

<section class="rounded-2xl border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-100 px-5 py-4"><h2 class="text-base font-bold text-gray-900">Bulk pricing</h2></div><div class="flex flex-col gap-3 p-5 lg:flex-row lg:items-end"><div><label class="text-sm font-medium text-gray-700">Giảm % so với giá kê khai</label><input type="number" min="0" max="100" step="0.01" wire:model="bulkDiscount" class="mt-1 w-40 rounded-xl border-gray-300">@error('bulkDiscount')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><button type="button" wire:click="applyDiscount" class="min-h-11 rounded-xl border border-gray-300 px-4 text-sm font-semibold">Áp dụng</button><button type="button" wire:click="copyCompanyToReceivable" class="min-h-11 rounded-xl border border-gray-300 px-4 text-sm font-semibold">Giá bán → Giá thu</button><button type="button" wire:click="copyCompanyToInvoice" class="min-h-11 rounded-xl border border-gray-300 px-4 text-sm font-semibold">Giá bán → Giá hóa đơn</button></div></section>

<section class="rounded-2xl border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-100 px-5 py-4"><p class="text-xs font-bold uppercase tracking-wide text-indigo-600">Bước 3</p><h2 class="mt-1 text-lg font-bold text-gray-900">Review & Save</h2></div><div class="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-5"><div><p class="text-xs text-gray-500">Loại</p><p class="font-semibold">{{ $type==='global'?'Bảng giá chung':'Khách hàng' }}</p></div><div><p class="text-xs text-gray-500">Khách hàng</p><p class="font-semibold">{{ $type==='customer' ? optional($customers->firstWhere('id',$partnerId))->name ?? 'Chưa chọn' : '-' }}</p></div><div><p class="text-xs text-gray-500">SKU/package chọn</p><p class="text-xl font-bold">{{ count($selectedRows) }}</p></div><div><p class="text-xs text-gray-500">Chưa có giá bán</p><p class="text-xl font-bold {{ $missingSaleCount?'text-amber-600':'' }}">{{ $missingSaleCount }}</p></div><div><p class="text-xs text-gray-500">Lỗi vượt giá kê khai</p><p class="text-xl font-bold {{ $overCeilingCount?'text-rose-600':'text-emerald-600' }}">{{ $overCeilingCount }}</p></div></div><div class="flex justify-end border-t border-gray-100 p-5"><button type="button" wire:click="saveDraft" wire:loading.attr="disabled" wire:target="saveDraft" class="min-h-11 rounded-xl bg-indigo-600 px-5 text-sm font-semibold text-white disabled:opacity-50"><span wire:loading.remove wire:target="saveDraft">Lưu Draft</span><span wire:loading wire:target="saveDraft">Đang lưu...</span></button></div></section>
</div>
