<div class="space-y-5">
@if($successMessage)<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-5 py-3 text-sm font-semibold text-emerald-800">{{ $successMessage }}</div>@endif
@if($errorMessage)<div role="alert" class="rounded-xl border border-rose-200 bg-rose-50 px-5 py-3 text-sm font-semibold text-rose-800">{{ $errorMessage }}</div>@endif

<nav class="sticky top-0 z-20 rounded-2xl border border-gray-200 bg-white/95 p-2 shadow-sm backdrop-blur">
<div class="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
@foreach([1=>['Thông tin','Phạm vi & hiệu lực'],2=>['Chọn thuốc','Medicine Master'],3=>['Thiết lập giá','Chính sách thương mại'],4=>['Kiểm tra & lưu','Rà soát Draft']] as $number=>$meta)
<button type="button" wire:click="goToStep({{ $number }})" class="flex min-h-14 items-center gap-3 rounded-xl border px-4 text-left {{ $step===$number?'border-indigo-300 bg-indigo-50 ring-1 ring-indigo-200':($step>$number?'border-emerald-200 bg-emerald-50/70':'border-transparent hover:bg-gray-50') }}"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-black {{ $step===$number?'bg-indigo-600 text-white':($step>$number?'bg-emerald-600 text-white':'bg-gray-100 text-gray-500') }}">{{ $step>$number?'✓':$number }}</span><span><span class="block text-sm font-bold text-gray-900">{{ $meta[0] }}</span><span class="block text-xs text-gray-500">{{ $meta[1] }}</span></span></button>
@endforeach
</div>
</nav>

@if($step===1)
<div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
<section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
<header class="border-b border-gray-100 px-6 py-5"><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Bước 1</p><h2 class="mt-1 text-xl font-bold text-gray-900">Thông tin bảng giá</h2><p class="mt-1 text-sm text-gray-500">Xác định phạm vi thương mại trước khi chọn SKU.</p></header>
<div class="grid gap-5 p-6 lg:grid-cols-2">
<div class="lg:col-span-2"><label class="text-sm font-semibold text-gray-700">Tên bảng giá <span class="text-rose-500">*</span></label><input wire:model="name" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 px-4 text-sm shadow-sm" placeholder="Ví dụ: BG Chung 2026">@error('name')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-semibold text-gray-700">Mã bảng giá <span class="text-rose-500">*</span></label><input wire:model="code" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 px-4 font-mono text-sm shadow-sm">@error('code')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-semibold text-gray-700">Loại bảng giá <span class="text-rose-500">*</span></label><select wire:model.live="type" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 px-4 text-sm shadow-sm"><option value="global">Bảng giá chung</option><option value="customer">Bảng giá khách hàng</option></select></div>
@if($type==='customer')
<div class="lg:col-span-2 rounded-2xl border border-indigo-100 bg-indigo-50/60 p-5">
<div class="mb-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-sm font-bold text-gray-900">Chính sách giá theo khách hàng</h3><p class="mt-1 text-xs text-gray-600">Khách hàng được lấy trực tiếp từ Partner Master.</p></div><a href="{{ route('admin.partners.index') }}" target="_blank" class="text-xs font-bold text-indigo-700 hover:underline">Mở danh mục khách hàng ↗</a></div>
<div class="grid gap-4 lg:grid-cols-2">
<div><label class="text-sm font-semibold text-gray-700">Khách hàng <span class="text-rose-500">*</span></label><select wire:model="partnerId" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 bg-white px-4 text-sm shadow-sm"><option value="">Chọn khách hàng</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}{{ $customer->tax_code?' · MST '.$customer->tax_code:'' }}</option>@endforeach</select>@if($customers->isEmpty())<p class="mt-2 text-xs font-semibold text-amber-700">Chưa có Partner ACTIVE được phân loại “Khách hàng”. Hãy cập nhật tại Partner Master.</p>@endif @error('partnerId')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
<div><label class="text-sm font-semibold text-gray-700">Khởi tạo từ bảng giá chung ACTIVE</label>@if($globalPriceLists->isNotEmpty())<div class="mt-1.5 flex gap-2"><select wire:model="sourceGlobalPriceListId" class="min-h-11 min-w-0 flex-1 rounded-xl border-gray-300 bg-white px-4 text-sm shadow-sm"><option value="">Chọn bảng giá nguồn</option>@foreach($globalPriceLists as $globalList)<option value="{{ $globalList->id }}">{{ $globalList->code }} — {{ $globalList->name }}</option>@endforeach</select><button type="button" wire:click="loadFromGlobalPriceList" class="min-h-11 shrink-0 rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white shadow-sm hover:bg-indigo-700">Khởi tạo</button></div><p class="mt-2 text-xs text-gray-600">Sao chép toàn bộ SKU và giá rồi chỉ chỉnh các ngoại lệ của khách hàng.</p>@else<div class="mt-1.5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs font-semibold text-amber-800">Chưa có bảng giá chung ACTIVE đang hiệu lực. Hãy kích hoạt một bảng giá chung trước khi khởi tạo giá khách hàng.</div>@endif @error('sourceGlobalPriceListId')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
</div></div>
@endif
<div><label class="text-sm font-semibold text-gray-700">Ngày hiệu lực</label><input type="date" wire:model="effectiveFrom" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 px-4 text-sm shadow-sm"></div><div><label class="text-sm font-semibold text-gray-700">Ngày hết hiệu lực</label><input type="date" wire:model="effectiveTo" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 px-4 text-sm shadow-sm"></div>
<div><label class="text-sm font-semibold text-gray-700">Tiền tệ</label><div class="mt-1.5 flex min-h-11 items-center rounded-xl border border-gray-200 bg-gray-50 px-4 text-sm font-bold">VND</div></div><div><label class="text-sm font-semibold text-gray-700">Priority</label><input type="number" wire:model="priority" class="mt-1.5 min-h-11 w-full rounded-xl border-gray-300 px-4 text-sm shadow-sm"></div>
<div class="lg:col-span-2"><label class="text-sm font-semibold text-gray-700">Ghi chú</label><textarea wire:model="notes" rows="3" class="mt-1.5 w-full rounded-xl border-gray-300 px-4 py-3 text-sm shadow-sm" placeholder="Điều kiện thương mại hoặc ghi chú nội bộ..."></textarea></div>
</div></section>
<aside class="h-fit rounded-2xl border border-gray-200 bg-white p-6 shadow-sm xl:sticky xl:top-24"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-gray-400">Tóm tắt</p><h3 class="mt-1 text-lg font-bold text-gray-900">{{ $name?:'Bảng giá mới' }}</h3></div><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">DRAFT</span></div><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between gap-3 border-b border-gray-100 pb-3"><dt class="text-gray-500">Mã</dt><dd class="font-mono font-semibold">{{ $code }}</dd></div><div class="flex justify-between gap-3 border-b border-gray-100 pb-3"><dt class="text-gray-500">Phạm vi</dt><dd class="font-semibold">{{ $type==='global'?'Toàn hệ thống':'Theo khách hàng' }}</dd></div>@if($type==='customer')<div class="flex justify-between gap-3 border-b border-gray-100 pb-3"><dt class="text-gray-500">Khách hàng</dt><dd class="text-right font-semibold">{{ optional($customers->firstWhere('id',$partnerId))->name??'Chưa chọn' }}</dd></div>@endif<div class="flex justify-between gap-3"><dt class="text-gray-500">Hiệu lực</dt><dd class="text-right font-semibold">{{ $effectiveFrom?:'Chưa đặt' }} → {{ $effectiveTo?:'∞' }}</dd></div></dl></aside>
</div>
@endif

@if($step===2)
<section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
<header class="flex flex-col gap-3 border-b border-gray-100 px-6 py-5 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Bước 2</p><h2 class="mt-1 text-xl font-bold">Chọn SKU / quy cách</h2><p class="mt-1 text-sm text-gray-500">Chọn sản phẩm trước; thiết lập giá ở bước tiếp theo.</p></div><div class="rounded-xl bg-indigo-50 px-4 py-2 text-sm font-semibold text-indigo-800">{{ count($selectedRows) }} SKU đã chọn</div></header>
<div class="grid gap-3 border-b border-gray-100 bg-gray-50/60 p-4 lg:grid-cols-[minmax(300px,1fr)_180px_180px_130px]"><input type="search" wire:model.live.debounce.300ms="search" placeholder="Mã thuốc, tên, hoạt chất, GPLH, SKU, quy cách..." class="min-h-11 rounded-xl border-gray-300 bg-white px-4 text-sm"><select wire:model.live="catalogStatus" class="min-h-11 rounded-xl border-gray-300 bg-white text-sm"><option value="all">Mọi trạng thái</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="needs_review">Needs review</option></select><select wire:model.live="specialControl" class="min-h-11 rounded-xl border-gray-300 bg-white text-sm"><option value="all">Tất cả KSĐB</option><option value="yes">KSĐB</option><option value="no">Không KSĐB</option></select><select wire:model.live="perPage" class="min-h-11 rounded-xl border-gray-300 bg-white text-sm">@foreach($perPageOptions as $option)<option value="{{ $option }}">{{ $option }} dòng</option>@endforeach</select></div>
<div class="flex flex-wrap items-center justify-between gap-3 border-b border-gray-100 px-5 py-3"><p class="text-sm text-gray-600"><strong>{{ $products->total() }}</strong> kết quả</p><div class="flex flex-wrap gap-2"><button type="button" wire:click="$set('selectPage',true)" class="rounded-lg border border-gray-300 px-3 py-2 text-xs font-bold">Chọn trang</button><button type="button" wire:click="selectAllMatching" class="rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Chọn tất cả kết quả</button><button type="button" wire:click="clearSelection" class="rounded-lg px-3 py-2 text-xs font-bold text-gray-500">Bỏ chọn</button></div></div>
@error('selectedRows')<p class="px-5 py-3 text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror
<div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-sm"><thead class="bg-gray-50 text-left text-[11px] font-bold uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3"><input type="checkbox" wire:model.live="selectPage" class="rounded border-gray-300"></th><th class="px-4 py-3">Thuốc</th><th class="px-4 py-3">Hoạt chất / hàm lượng</th><th class="px-4 py-3">GPLH</th><th class="px-4 py-3">SKU</th><th class="px-4 py-3">Quy cách</th><th class="px-4 py-3 text-right">Giá kê khai</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($products as $row)<tr class="hover:bg-indigo-50/30"><td class="px-4 py-4"><input type="checkbox" wire:model.live="selectedRows" value="{{ $row->key }}" class="rounded border-gray-300"></td><td class="px-4 py-4"><div class="font-bold text-gray-900">{{ $row->name }}</div><div class="mt-1 font-mono text-xs text-gray-500">{{ $row->medicine_code }}</div></td><td class="px-4 py-4">{{ $row->active_ingredients?:'-' }}<div class="mt-1 text-xs text-gray-500">{{ $row->strength_text?:$row->concentration }}</div></td><td class="px-4 py-4">{{ $row->registration_number?:'-' }}</td><td class="px-4 py-4 font-mono text-xs">{{ $row->sku }}</td><td class="px-4 py-4">{{ $row->packaging_text?:$row->packaging_specification?:'-' }}</td><td class="px-4 py-4 text-right font-bold">{{ $row->declared_price!==null?number_format((float)$row->declared_price,0,',','.').' ₫':'-' }}</td></tr>@empty<tr><td colspan="7" class="px-6 py-14 text-center text-gray-500">Không tìm thấy SKU phù hợp.</td></tr>@endforelse</tbody></table></div>
<div class="flex items-center justify-between border-t border-gray-100 px-5 py-4"><button type="button" wire:click="gotoPage({{ max(1,$products->currentPage()-1) }})" @disabled($products->onFirstPage()) class="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">← Trước</button><span class="text-sm font-semibold">Trang {{ $products->currentPage() }}/{{ max(1,$products->lastPage()) }}</span><button type="button" wire:click="gotoPage({{ min(max(1,$products->lastPage()),$products->currentPage()+1) }})" @disabled(!$products->hasMorePages()) class="rounded-lg border px-3 py-2 text-sm disabled:opacity-40">Sau →</button></div>
</section>
@endif

@if($step===3)
<section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
<header class="flex flex-col gap-4 border-b border-gray-100 px-6 py-5 xl:flex-row xl:items-end xl:justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Bước 3</p><h2 class="mt-1 text-xl font-bold">Thiết lập chính sách giá</h2><p class="mt-1 text-sm text-gray-500">Giá bán công ty mặc định bằng giá kê khai. % giảm được tính vào <strong>Giá thu thực tế</strong>.</p></div><div class="rounded-xl border border-gray-200 bg-gray-50 p-3"><label class="text-xs font-bold text-gray-600">Giảm từ giá kê khai → Giá thu thực tế</label><div class="mt-1 flex gap-2"><div class="relative"><input type="number" min="0" max="100" step="0.01" wire:model="bulkDiscount" class="w-28 rounded-lg border-gray-300 pr-8 text-right text-sm"><span class="absolute right-3 top-2 text-sm text-gray-400">%</span></div><button type="button" wire:click="applyDiscount" class="rounded-lg bg-indigo-600 px-4 text-xs font-bold text-white">Áp dụng</button><button type="button" wire:click="copyCompanyToReceivable" class="rounded-lg border bg-white px-3 text-xs font-bold">Giá bán → Giá thu</button><button type="button" wire:click="copyCompanyToInvoice" class="rounded-lg border bg-white px-3 text-xs font-bold">Giá bán → Giá HĐ</button></div>@error('bulkDiscount')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div></header>
<div class="overflow-x-auto"><table class="w-full min-w-[1250px] text-sm"><thead class="bg-gray-50 text-left text-[11px] font-bold uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3">Thuốc / SKU</th><th class="px-4 py-3">Quy cách</th><th class="px-4 py-3 text-right">Giá kê khai</th><th class="px-4 py-3">Giá bán công ty</th><th class="px-4 py-3 text-center">CK thu về</th><th class="px-4 py-3">Giá thu thực tế</th><th class="px-4 py-3">Giá xuất HĐ</th><th class="px-4 py-3">Kiểm tra</th></tr></thead><tbody class="divide-y divide-gray-100">@foreach($selectedProducts as $row)@php($company=$prices[$row->key]['company']??'') @php($receivable=$prices[$row->key]['receivable']??'') @php($over=$company!==''&&$row->declared_price!==null&&(float)$company>(float)$row->declared_price) @php($discount=$row->declared_price&&$receivable!==''?max(0,(1-((float)$receivable/(float)$row->declared_price))*100):0)<tr class="align-top"><td class="px-4 py-4"><div class="font-bold">{{ $row->name }}</div><div class="mt-1 font-mono text-xs text-gray-500">{{ $row->medicine_code }} · {{ $row->sku }}</div></td><td class="px-4 py-4">{{ $row->packaging_text?:$row->packaging_specification?:'-' }}</td><td class="px-4 py-4 text-right font-bold">{{ $row->declared_price!==null?number_format((float)$row->declared_price,0,',','.').' ₫':'-' }}</td><td class="px-4 py-4"><input type="number" min="0" step="0.01" wire:model.blur="prices.{{ $row->key }}.company" class="w-36 rounded-lg border-gray-300 bg-indigo-50/40 text-right font-semibold"></td><td class="px-4 py-4 text-center"><span class="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{{ number_format($discount,2,',','.') }}%</span></td><td class="px-4 py-4"><input type="number" min="0" step="0.01" wire:model.blur="prices.{{ $row->key }}.receivable" class="w-36 rounded-lg border-gray-300 text-right font-semibold"></td><td class="px-4 py-4"><input type="number" min="0" step="0.01" wire:model.blur="prices.{{ $row->key }}.invoice" class="w-36 rounded-lg border-gray-300 text-right"></td><td class="px-4 py-4">@if($over)<span class="rounded-full bg-rose-100 px-2.5 py-1 text-xs font-bold text-rose-700">Vượt kê khai</span><p class="mt-2 max-w-44 text-xs text-rose-600">Giá bán không được vượt {{ number_format((float)$row->declared_price,0,',','.') }} ₫.</p>@elseif($company==='')<span class="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-700">Thiếu giá</span>@else<span class="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-700">Hợp lệ</span>@endif</td></tr>@endforeach</tbody></table></div>
</section>
@endif

@if($step===4)
<div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
<section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><p class="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Bước 4</p><h2 class="mt-1 text-xl font-bold">Kiểm tra trước khi lưu</h2><p class="mt-1 text-sm text-gray-500">Draft có thể chỉnh sửa. Kích hoạt được thực hiện riêng sau khi rà soát.</p><div class="mt-6 grid gap-4 sm:grid-cols-3"><div class="rounded-xl border bg-gray-50 p-4"><p class="text-xs font-bold uppercase text-gray-500">SKU / quy cách</p><p class="mt-2 text-3xl font-black">{{ count($selectedRows) }}</p></div><div class="rounded-xl border {{ $missingSaleCount?'border-amber-200 bg-amber-50':'border-emerald-200 bg-emerald-50' }} p-4"><p class="text-xs font-bold uppercase text-gray-500">Thiếu giá bán</p><p class="mt-2 text-3xl font-black">{{ $missingSaleCount }}</p></div><div class="rounded-xl border {{ $overCeilingCount?'border-rose-200 bg-rose-50':'border-emerald-200 bg-emerald-50' }} p-4"><p class="text-xs font-bold uppercase text-gray-500">Vượt giá kê khai</p><p class="mt-2 text-3xl font-black">{{ $overCeilingCount }}</p></div></div>@if(!$missingSaleCount&&!$overCeilingCount)<div class="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">✓ Tất cả SKU có giá bán hợp lệ và không vượt giá kê khai.</div>@endif</section>
<aside class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[.18em] text-gray-400">Thông tin bảng giá</p><h3 class="mt-1 text-lg font-bold">{{ $name }}</h3></div><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">DRAFT</span></div><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between border-b pb-3"><dt class="text-gray-500">Mã</dt><dd class="font-mono font-semibold">{{ $code }}</dd></div><div class="flex justify-between border-b pb-3"><dt class="text-gray-500">Loại</dt><dd class="font-semibold">{{ $type==='global'?'Bảng giá chung':'Khách hàng' }}</dd></div>@if($type==='customer')<div class="flex justify-between border-b pb-3"><dt class="text-gray-500">Khách hàng</dt><dd class="text-right font-semibold">{{ optional($customers->firstWhere('id',$partnerId))->name??'Chưa chọn' }}</dd></div>@endif<div class="flex justify-between"><dt class="text-gray-500">Hiệu lực</dt><dd class="font-semibold">{{ $effectiveFrom?:'∞' }} → {{ $effectiveTo?:'∞' }}</dd></div></dl><button type="button" wire:click="saveDraft" wire:loading.attr="disabled" @disabled($missingSaleCount||$overCeilingCount) class="mt-6 min-h-11 w-full rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white shadow-sm disabled:cursor-not-allowed disabled:opacity-40"><span wire:loading.remove wire:target="saveDraft">Lưu bảng giá Draft</span><span wire:loading wire:target="saveDraft">Đang lưu...</span></button></aside>
</div>
@endif

<footer class="sticky bottom-3 z-10 flex items-center justify-between rounded-2xl border border-gray-200 bg-white/95 px-5 py-3 shadow-lg backdrop-blur"><div class="text-sm text-gray-500">Bước <strong class="text-gray-900">{{ $step }}/4</strong> · <strong class="text-indigo-700">{{ count($selectedRows) }} SKU/quy cách</strong></div><div class="flex gap-2">@if($step>1)<button type="button" wire:click="previousStep" class="min-h-10 rounded-xl border border-gray-300 bg-white px-4 text-sm font-bold text-gray-700">← Quay lại</button>@endif @if($step<4)<button type="button" wire:click="nextStep" class="min-h-10 rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white shadow-sm">Tiếp tục →</button>@endif</div></footer>

@if($savedModal)
<div class="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/50 p-4 backdrop-blur-sm"><div class="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl"><div class="px-6 pb-5 pt-7 text-center"><div class="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-2xl font-black text-emerald-700">✓</div><h3 class="mt-4 text-xl font-bold text-gray-900">Đã lưu bảng giá Draft</h3><p class="mt-2 text-sm leading-6 text-gray-600"><strong>{{ $savedName }}</strong> đã được lưu thành công. Giá kê khai đã được snapshot để bảo toàn lịch sử.</p></div><div class="border-t border-gray-100 bg-gray-50 p-4"><button type="button" wire:click="returnToIndex" class="min-h-11 w-full rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white">Về danh sách bảng giá</button></div></div></div>
@endif
</div>
