<div class="space-y-5">
@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{{ session('success') }}</div>@endif
<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
@foreach(['total'=>'Tổng bảng giá','active'=>'Đang hiệu lực','global'=>'Bảng giá chung','customer'=>'Bảng giá khách hàng','expiring'=>'Sắp hết hiệu lực'] as $key=>$label)
<div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><p class="text-sm text-gray-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-gray-900">{{ $kpis[$key] }}</p></div>
@endforeach
</div>
<div class="rounded-2xl border border-gray-200 bg-white shadow-sm">
<div class="grid gap-3 border-b border-gray-100 p-4 md:grid-cols-4">
<input type="search" wire:model.live.debounce.300ms="search" placeholder="Tìm mã hoặc tên bảng giá..." class="rounded-xl border-gray-300 text-sm">
<select wire:model.live="type" class="rounded-xl border-gray-300 text-sm"><option value="all">Tất cả loại</option><option value="global">Chung</option><option value="customer">Khách hàng</option></select>
<select wire:model.live="status" class="rounded-xl border-gray-300 text-sm"><option value="all">Tất cả trạng thái</option><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select>
<select wire:model.live="perPage" class="rounded-xl border-gray-300 text-sm"><option>10</option><option>25</option><option>50</option><option>100</option></select>
</div>
<div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-4 py-3">Mã</th><th class="px-4 py-3">Tên bảng giá</th><th class="px-4 py-3">Loại</th><th class="px-4 py-3">Khách hàng</th><th class="px-4 py-3">Hiệu lực</th><th class="px-4 py-3">SKU</th><th class="px-4 py-3">Trạng thái</th><th class="px-4 py-3">Cập nhật</th><th class="px-4 py-3">Thao tác</th></tr></thead>
<tbody class="divide-y divide-gray-100">@forelse($priceLists as $list)<tr class="hover:bg-gray-50"><td class="px-4 py-3 font-semibold">{{ $list->code }}</td><td class="px-4 py-3">{{ $list->name }}</td><td class="px-4 py-3">{{ $list->type === 'global' ? 'Chung' : 'Khách hàng' }}</td><td class="px-4 py-3">{{ $list->partner?->name ?? '-' }}</td><td class="px-4 py-3">{{ $list->effective_from?->format('d/m/Y') ?? '∞' }} → {{ $list->effective_to?->format('d/m/Y') ?? '∞' }}</td><td class="px-4 py-3">{{ $list->items_count }}</td><td class="px-4 py-3"><span class="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-semibold">{{ strtoupper($list->status) }}</span></td><td class="px-4 py-3">{{ $list->updated_at?->format('d/m/Y H:i') }}</td><td class="px-4 py-3"><div class="flex gap-2"><a href="{{ route('admin.pharma.price-lists.show',$list) }}" class="font-semibold text-indigo-600">Xem</a>@if($list->status==='draft')<a href="{{ route('admin.pharma.price-lists.edit',$list) }}" class="font-semibold text-gray-700">Sửa</a><button wire:click="confirm({{ $list->id }},'activate')" class="font-semibold text-emerald-700">Activate</button>@else<button wire:click="confirm({{ $list->id }},'deactivate')" class="font-semibold text-amber-700">Deactivate</button>@endif<button wire:click="confirm({{ $list->id }},'clone')" class="font-semibold text-gray-700">Clone</button><a href="{{ route('admin.pharma.price-lists.export',$list) }}" class="font-semibold text-gray-700">Export</a></div></td></tr>@empty<tr><td colspan="9" class="px-6 py-12 text-center text-gray-500">Chưa có bảng giá phù hợp.</td></tr>@endforelse</tbody></table></div>
<div class="border-t border-gray-100 p-4">{{ $priceLists->links() }}</div>
</div>
@if($confirmingId)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h3 class="text-lg font-bold text-gray-900">Xác nhận thao tác</h3><p class="mt-2 text-sm text-gray-600">Bạn có chắc muốn {{ $confirmingAction }} bảng giá này? Thao tác lifecycle sẽ được kiểm tra business rule phía server.</p><div class="mt-6 flex justify-end gap-3"><button wire:click="cancelConfirm" class="rounded-xl border border-gray-300 px-4 py-2 text-sm font-semibold">Hủy</button><button wire:click="executeConfirmed" class="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Xác nhận</button></div></div></div>@endif
</div>
