<?php
namespace Modules\ClientPortal\Applications\Muasamcong\Http\Controllers;
use App\Http\Controllers\Controller; use Illuminate\Contracts\View\View; use Illuminate\Http\JsonResponse; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Modules\ClientPortal\Jobs\GeneratePriceListExport; use Modules\ClientPortal\Jobs\SendPriceListExportEmail; use Modules\ClientPortal\Models\PriceListExport; use Modules\Muasamcong\Models\PriceListProfile; use Modules\Muasamcong\Models\PricingResult; use Modules\Muasamcong\Models\PricingWishlist;
class MuasamcongPriceListController extends Controller
{
 public function index(Request $request): View { $u=$request->user('web'); abort_if(!$u,401); $source=in_array($request->query('source'),['synced','wishlist'],true)?$request->query('source'):'synced'; $profiles=PriceListProfile::where('is_active',true)->orderByDesc('is_default')->orderBy('sort_order')->get(); $items=$source==='wishlist'?PricingWishlist::where('user_id',$u->getKey())->latest()->paginate(20)->withQueryString():PricingResult::latest('synced_at')->paginate(20)->withQueryString(); $exports=PriceListExport::where('user_id',$u->getKey())->latest()->limit(10)->get(); $canExport=$u->can('client.muasamcong.price-list.export'); return view('ClientPortal::applications.muasamcong.price-list',compact('source','profiles','items','exports','canExport')); }
 public function store(Request $request): RedirectResponse { $u=$this->exportUser($request); $d=$request->validate(['source'=>'required|in:synced,wishlist','profile_id'=>'required|integer|exists:muasamcong_price_list_profiles,id','selected_ids'=>'required|array|min:1|max:200','selected_ids.*'=>'required|string|max:64']); $profile=PriceListProfile::whereKey($d['profile_id'])->where('is_active',true)->firstOrFail(); $ids=array_values(array_unique($d['selected_ids'])); if($d['source']==='wishlist'){$allowed=PricingWishlist::where('user_id',$u->getKey())->whereIn('id',$ids)->pluck('id')->map(fn($v)=>(string)$v)->all();}else{$allowed=PricingResult::whereIn('source_id',$ids)->pluck('source_id')->map(fn($v)=>(string)$v)->all();} abort_if(count($allowed)!==count($ids),403); $export=PriceListExport::create(['user_id'=>$u->getKey(),'profile_id'=>$profile->id,'source'=>$d['source'],'selected_ids'=>$ids,'status'=>'queued']); GeneratePriceListExport::dispatch($export->id); return back()->with('status','Đã đưa yêu cầu xuất Bảng Giá vào Queue.'); }
 public function status(Request $r,PriceListExport $e): JsonResponse{$this->owner($r,$e);return response()->json(['status'=>$e->status,'items_count'=>$e->items_count,'error'=>$e->error_message,'download_url'=>$e->status==='completed'?route('client.muasamcong.price-list.download',$e):null]);}
 public function download(Request $r,PriceListExport $e): BinaryFileResponse{$this->owner($r,$e);abort_unless($e->status==='completed'&&$e->file_path&&Storage::disk('local')->exists($e->file_path),404);return response()->download(Storage::disk('local')->path($e->file_path),$e->file_name);}
 public function share(Request $r,PriceListExport $e): JsonResponse{$this->exportUser($r);$this->owner($r,$e);abort_unless($e->status==='completed',409);if(!$e->share_token)$e->update(['share_token'=>Str::random(64)]);return response()->json(['url'=>route('public.muasamcong.price-list',$e->share_token)]);}
 public function publicDownload(string $token): BinaryFileResponse{$e=PriceListExport::where('share_token',$token)->where('status','completed')->firstOrFail();abort_unless($e->file_path&&Storage::disk('local')->exists($e->file_path),404);return response()->download(Storage::disk('local')->path($e->file_path),$e->file_name);}
 public function email(Request $r,PriceListExport $e): RedirectResponse{$this->exportUser($r);$this->owner($r,$e);abort_unless($e->status==='completed',409);$d=$r->validate(['email'=>'required|email|max:200']);SendPriceListExportEmail::dispatch($e->id,$d['email']);return back()->with('status','Đã đưa email Bảng Giá vào Queue gửi.');}
 private function owner(Request $r,PriceListExport $e): void{$u=$r->user('web');abort_if(!$u||(int)$e->user_id!==(int)$u->getKey(),403);}
 private function exportUser(Request $r){$u=$r->user('web');abort_if(!$u,401);abort_unless($u->can('client.muasamcong.price-list.export'),403);return $u;}
}
