<?php
namespace Modules\ClientPortal\Applications\Muasamcong\Http\Controllers;
use App\Http\Controllers\Controller; use Illuminate\Contracts\View\View; use Illuminate\Http\JsonResponse; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Modules\ClientPortal\Jobs\GeneratePriceListExport; use Modules\ClientPortal\Jobs\SendPriceListExportEmail; use Modules\ClientPortal\Models\PriceListExport; use Modules\Muasamcong\Models\PriceListProfile; use Modules\Muasamcong\Models\PricingResult; use Modules\Muasamcong\Models\PricingWishlist;
class MuasamcongPriceListController extends Controller
{
 public function index(Request $request): View
 { $u=$request->user('web'); abort_if(!$u,401); $source=in_array($request->query('source'),['synced','wishlist'],true)?$request->query('source'):'synced'; $profiles=PriceListProfile::where('is_active',true)->orderByDesc('is_default')->orderBy('sort_order')->get(); $items=$source==='wishlist'?PricingWishlist::where('user_id',$u->getKey())->latest()->paginate(20)->withQueryString():PricingResult::latest('synced_at')->paginate(20)->withQueryString(); $exports=PriceListExport::where('user_id',$u->getKey())->latest()->limit(10)->get(); return view('ClientPortal::applications.muasamcong.price-list',compact('source','profiles','items','exports')); }
 public function store(Request $request): RedirectResponse
 { $u=$request->user('web'); abort_if(!$u,401); $d=$request->validate(['source'=>'required|in:synced,wishlist','profile_id'=>'required|integer|exists:muasamcong_price_list_profiles,id','selected_ids'=>'required|array|min:1|max:200','selected_ids.*'=>'required|string|max:64']); $profile=PriceListProfile::whereKey($d['profile_id'])->where('is_active',true)->firstOrFail(); $ids=array_values(array_unique($d['selected_ids'])); if($d['source']==='wishlist'){$allowed=PricingWishlist::where('user_id',$u->getKey())->whereIn('id',$ids)->pluck('id')->map(fn($v)=>(string)$v)->all();}else{$allowed=PricingResult::whereIn('source_id',$ids)->pluck('source_id')->map(fn($v)=>(string)$v)->all();} abort_if(count($allowed)!==count($ids),403); $export=PriceListExport::create(['user_id'=>$u->getKey(),'profile_id'=>$profile->id,'source'=>$d['source'],'selected_ids'=>$ids,'status'=>'queued']); GeneratePriceListExport::dispatch($export->id); return back()->with('status','Đã đưa yêu cầu xuất Bảng Giá vào Queue.'); }
 public function status(Request $request, PriceListExport $export): JsonResponse { $this->owner($request,$export); return response()->json(['status'=>$export->status,'items_count'=>$export->items_count,'error'=>$export->error_message,'download_url'=>$export->status==='completed'?route('client.muasamcong.price-list.download',$export):null]); }
 public function download(Request $request, PriceListExport $export): BinaryFileResponse { $this->owner($request,$export); abort_unless($export->status==='completed'&&$export->file_path&&Storage::disk('local')->exists($export->file_path),404); return response()->download(Storage::disk('local')->path($export->file_path),$export->file_name); }
 public function share(Request $request, PriceListExport $export): JsonResponse { $this->owner($request,$export); abort_unless($export->status==='completed',409); if(!$export->share_token){$export->update(['share_token'=>Str::random(64)]);} return response()->json(['url'=>route('public.muasamcong.price-list',$export->share_token)]); }
 public function publicDownload(string $token): BinaryFileResponse { $export=PriceListExport::where('share_token',$token)->where('status','completed')->firstOrFail(); abort_unless($export->file_path&&Storage::disk('local')->exists($export->file_path),404); return response()->download(Storage::disk('local')->path($export->file_path),$export->file_name); }
 public function email(Request $request, PriceListExport $export): RedirectResponse { $this->owner($request,$export); abort_unless($export->status==='completed',409); $d=$request->validate(['email'=>'required|email|max:200']); SendPriceListExportEmail::dispatch($export->id,$d['email']); return back()->with('status','Đã đưa email Bảng Giá vào Queue gửi.'); }
 private function owner(Request $r,PriceListExport $e): void { $u=$r->user('web'); abort_if(!$u||(int)$e->user_id!==(int)$u->getKey(),403); }
}
