<?php

namespace Tests\Feature\ClientApps;

use Tests\TestCase;

class PharmaPriceListsCapabilityTest extends TestCase
{
    public function test_client_price_lists_are_scoped_to_managed_lists_without_admin_reuse(): void
    {
        $manifest = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/manifest.php'));
        $routes = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/routes.php'));
        $controller = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/Http/Controllers/PharmaApplicationController.php'));
        $service = file_get_contents(base_path('Modules/Pharma/Services/UserPriceListWorkspace.php'));
        $view = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-lists.blade.php'));
        $detail = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-show.blade.php'));
        $create = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-create.blade.php'));
        $createWizard = file_get_contents(base_path('resources/js/clientportal/pharma-price-list-wizard.js'));
        $workflow = file_get_contents(base_path('Modules/Pharma/Services/UserPriceListWorkflow.php'));
        $model = file_get_contents(base_path('Modules/Pharma/Models/PriceList.php'));
        $approval = file_get_contents(base_path('Modules/Pharma/Services/PriceListApprovalWorkflow.php'));
        $approvalQueue = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-approvals.blade.php'));
        $approvalDetail = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-approval-show.blade.php'));
        $globalWorkflow = file_get_contents(base_path('Modules/Pharma/Services/ApproverGlobalPriceListWorkflow.php'));
        $deactivation = file_get_contents(base_path('Modules/Pharma/Services/PriceListDeactivationWorkflow.php'));
        $shareExport = file_get_contents(base_path('Modules/Pharma/Services/PriceListShareExportService.php'));
        $shareModel = file_get_contents(base_path('Modules/Pharma/Models/PriceListExportShare.php'));
        $pdfJob = file_get_contents(base_path('Modules/Pharma/Jobs/GeneratePriceListSharePdf.php'));
        $pdfMigration = file_get_contents(base_path('Modules/Pharma/database/migrations/2026_09_27_204000_add_pdf_fields_to_price_list_export_shares.php'));

        $this->assertStringContainsString("'route' => 'client.pharma.price-lists'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.view'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.create'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.submit'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.approve'", $manifest);
        $priceListFeature = require base_path('Modules/ClientPortal/Applications/Pharma/manifest.php');
        $priceListActions = $priceListFeature['features']['price-lists']['actions'] ?? [];
        $this->assertSame('client.pharma.price-lists.create', $priceListActions['create']['permission'] ?? null);
        $this->assertSame('client.pharma.price-lists.submit', $priceListActions['submit']['permission'] ?? null);
        $this->assertSame('client.pharma.price-lists.approve', $priceListActions['approve']['permission'] ?? null);

        $this->assertStringContainsString("->name('price-lists')", $routes);
        $this->assertStringContainsString("->name('price-lists.show')", $routes);
        $this->assertStringContainsString("->name('price-lists.create')", $routes);
        $this->assertStringContainsString("->name('price-lists.store')", $routes);
        $this->assertStringContainsString("->name('price-lists.global.store')", $routes);
        $this->assertStringContainsString("->name('price-lists.submit')", $routes);
        $this->assertStringContainsString("->name('price-lists.activate-own-draft')", $routes);
        $this->assertStringContainsString("->name('price-lists.edit')", $routes);
        $this->assertStringContainsString("->name('price-lists.update')", $routes);
        $this->assertStringContainsString("->name('price-lists.delete')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivation.request')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivation.approve')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivate')", $routes);
        $this->assertStringContainsString("->name('price-lists.export-share')", $routes);
        $this->assertStringContainsString("->name('client.pharma.price-lists.share.download')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.revoke')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.pdf.queue')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.status')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.email')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.pdf.regenerate')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.export.delete')", $routes);
        $this->assertStringContainsString("->name('client.pharma.price-lists.share.pdf')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.show')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.approve')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.reject')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.items.update')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.items.delete')", $routes);
        $this->assertStringContainsString('client.feature:pharma,price-lists', $routes);
        $this->assertStringNotContainsString('auth:admin', $routes);
        $approvalBrowseStart = strpos($controller, 'public function priceListApprovals(');
        $approvalBrowseEnd = strpos($controller, 'public function priceListApproval(', $approvalBrowseStart);
        $approvalBrowse = substr($controller, $approvalBrowseStart, $approvalBrowseEnd - $approvalBrowseStart);
        $this->assertStringContainsString("'q' => ['nullable', 'string', 'max:120']", $approvalBrowse);
        $this->assertStringContainsString("'page' => ['nullable', 'integer', 'min:1']", $approvalBrowse);
        $this->assertStringContainsString('perPage: 25', $approvalBrowse);
        $this->assertStringNotContainsString("'per_page' =>", $approvalBrowse);
        $this->assertStringNotContainsString('filterOptions()', $approvalBrowse);
        $this->assertStringNotContainsString('investor:', $approvalBrowse);
        $this->assertStringNotContainsString('medicine:', $approvalBrowse);

        $this->assertStringContainsString('UserPriceListWorkspace $workspace', $controller);
        $this->assertStringContainsString('$workspace->browse(', $controller);
        $this->assertStringContainsString('$workspace->findVisible(', $controller);
        $this->assertStringContainsString('findVisible((int) $user->id, $priceList, $canApprove)', $controller);
        $this->assertStringContainsString('abort_if($list === null, 404)', $controller);

        $this->assertStringContainsString("where('manager_user_id', \$userId)", $service);
        $this->assertStringContainsString('public function findManaged(int $userId, int $priceListId)', $service);
        $this->assertStringContainsString('public function findEditable(int $userId, int $priceListId, bool $approverScope = false)', $service);
        $this->assertStringContainsString('$workspace->findEditable((int) $user->id, $priceList, $canApprove)', $controller);
        $this->assertStringContainsString('public function findVisible(int $userId, int $priceListId, bool $approverScope = false)', $service);
        $this->assertStringNotContainsString('auth(', $service);

        $manifest = require base_path('Modules/ClientPortal/Applications/Pharma/manifest.php');
        $priceListFeature = $manifest['features']['price-lists'];
        $this->assertSame('Bảng giá của tôi', $priceListFeature['page_title']);
        $this->assertStringContainsString('Chỉ hiển thị các bảng giá bạn là người phụ trách', $priceListFeature['page_description']);
        $this->assertStringContainsString("\$featurePresentation['page_title']", $view);
        $this->assertStringContainsString("\$featurePresentation['page_description']", $view);
        $this->assertStringNotContainsString('name="per_page"', $view);
        $this->assertStringNotContainsString('->links()', $view);
        $this->assertStringNotContainsString("setTimeout(()=>f.requestSubmit(),350)", $view);
        $this->assertStringContainsString('data-pwa-debounced-search="350"', $view);
        $this->assertStringContainsString('data-pwa-search-clear-button', $view);
        $this->assertStringContainsString('data-pwa-load-more-targets', $view);
        $this->assertStringContainsString('Xem thêm', $view);
        $this->assertStringContainsString('hidden overflow-visible rounded-3xl border border-slate-200 bg-white shadow-sm lg:block', $view);
        $this->assertStringContainsString('absolute right-0 z-[100] mt-2 w-56', $view);
        $this->assertStringNotContainsString('hidden overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm lg:block', $view);
        $this->assertStringContainsString("['from_date','Từ ngày',\$fromDate]", $view);
        $this->assertStringContainsString("['to_date','Đến ngày',\$toDate]", $view);
        $this->assertStringContainsString('<x-pwa-date :name="$dateName" :label="$dateLabel" :value="$dateIso"', $view);
        $this->assertStringContainsString('onchange="this.form?.requestSubmit()"', $view);
        $this->assertStringNotContainsString('data-filter-date-display=', $view);
        $this->assertStringNotContainsString('data-filter-date-native=', $view);
        $this->assertStringContainsString('Đặt lại', $view);
        $this->assertStringContainsString("'from_date' => \$fromDate", $view);
        $this->assertStringContainsString("'to_date' => \$toDate", $view);
        $this->assertStringContainsString("whereDate('effective_from', '>='", $service);
        $this->assertStringContainsString("whereDate('effective_from', '<='", $service);
        $this->assertStringContainsString('?int $managerUserId = null', $service);
        $this->assertStringContainsString('bool $approverScope = false', $service);
        $this->assertStringContainsString("->where('manager_user_id', \$managerUserId)", $service);
        $this->assertStringContainsString("'manager_user_id' => ['nullable', 'integer']", $controller);
        $this->assertStringContainsString('managerUserId: $managerUserId', $controller);
        $this->assertStringContainsString('approverScope: $canApprove', $controller);
        $this->assertStringContainsString('name="manager_user_id"', $view);
        $this->assertStringContainsString('Tất cả User', $view);
        $this->assertStringContainsString('Người phụ trách', $view);
        $this->assertStringContainsString("'manager_user_id' => \$managerUserId", $view);
        $this->assertStringNotContainsString('Admin::', $view);

        $this->assertStringContainsString('Giá kê khai', $detail);
        $this->assertStringContainsString('Giá bán CT', $detail);
        $this->assertStringContainsString('Giá thu / Giá HĐ', $detail);
        $this->assertStringContainsString('Gửi duyệt', $detail);
        $this->assertStringContainsString('Sửa Nháp', $detail);
        $this->assertStringContainsString('Xóa', $detail);
        $this->assertStringContainsString("route('client.pharma.price-lists.edit'", $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.delete'", $view);
        $this->assertStringContainsString("'draft' => 'Nháp'", $view);
        $this->assertStringContainsString('STATUS_PENDING_APPROVAL', $detail);
        $this->assertStringContainsString('Không thể hoàn tất thao tác', $detail);
        $this->assertStringContainsString('Sửa thông tin', $detail);
        $this->assertStringContainsString('pending-price-list-edit-dialog', $detail);
        $this->assertStringContainsString("route('client.pharma.price-list-approvals.header.update'", $detail);
        $this->assertStringContainsString('updatePendingPriceListHeader', $controller);
        $this->assertStringContainsString("'effective_to' => ['required', 'date', 'after_or_equal:effective_from']", $controller);

        $this->assertStringContainsString('$errors->first()', $detail);
        $this->assertStringContainsString("redirect()->route('client.pharma.price-lists.show', \$priceList)", $controller);

        $this->assertStringContainsString('Tạo bảng giá cho khách hàng', $create);
        // Single-value business selectors use the canonical PWA searchable-selector contract;
        // wizard validation still observes the shared hidden value through its change event.
        $this->assertStringNotContainsString('<x-search-select', $create);
        $this->assertStringNotContainsString('data-customer-combobox', $create);
        $this->assertStringContainsString('<x-pwa-select-search id="client-price-list-customer"', $create);
        $this->assertStringContainsString('name="partner_id"', $create);
        $pwaSelectSearch = file_get_contents(base_path('resources/views/components/pwa-select-search.blade.php'));
        $this->assertStringContainsString('<input type="hidden" id="{{ $id }}" name="{{ $name }}"', $pwaSelectSearch);
        $this->assertStringContainsString('data-pwa-select-search-option', $create);
        $this->assertStringContainsString("document.getElementById('client-price-list-customer')", $createWizard);
        $this->assertStringContainsString('const stepTwoReady = () =>', $createWizard);
        $this->assertStringContainsString("back.classList.toggle('hidden', currentStep === 1)", $createWizard);
        $this->assertStringContainsString("replace(/\\D/g, '')", $createWizard);
        $this->assertStringContainsString('id="source-product-search" type="search"', $create);
        $this->assertStringContainsString('01 · Khởi tạo bảng giá', $create);
        $this->assertStringContainsString('02 · Khách hàng & mục đích', $create);
        $this->assertStringContainsString('03 · Sản phẩm & giá', $create);
        $this->assertStringContainsString('04 · Xem lại & lưu', $create);
        $this->assertStringContainsString('id="source-product-search"', $create);
        $this->assertStringContainsString('select-all-source-products', $create);
        $this->assertStringContainsString('source-product-search', $create);
        $this->assertStringNotContainsString('clear-source-product-search', $create);
        $this->assertStringContainsString('source-price-list-error', $create);
        $this->assertStringContainsString('id="source-price-list" name="source_price_list_id"', $create);
        $this->assertStringContainsString('source_price_list_id', $create);
        $this->assertStringContainsString('name="source_price_list_id" value="{{ old(\'source_price_list_id\', $sourcePriceListId) }}"', $create);
        $this->assertStringContainsString("route('client.pharma.price-lists.create', ['type'=>'global'])", $create);
        $this->assertStringContainsString('<x-pwa-date :name="$dateName" :label="$dateLabel.\' *\'" :value="$dateIso" required', $create);
        $this->assertStringNotContainsString('data-date-display=', $create);
        $this->assertStringNotContainsString('data-date-native=', $create);
        $this->assertStringNotContainsString("document.querySelectorAll('[data-date-native]')", $createWizard);
        $this->assertStringNotContainsString('sticky bottom-4', $create);
        $this->assertStringContainsString('Lưu bảng giá Nháp', $create);
        $this->assertStringContainsString('name="selected[', $create);
        $this->assertStringContainsString('name="company_price[', $create);
        $this->assertStringContainsString('name="actual_receivable_price[', $create);
        $this->assertStringContainsString('name="invoice_price[', $create);
        $this->assertStringContainsString('>Giá thu</th>', $create);
        $this->assertStringContainsString('>Giá HĐ</th>', $create);
        $this->assertStringContainsString('+ Bổ sung sản phẩm', $create);
        $this->assertStringContainsString('data-draft-selected=', $create);
        $this->assertStringContainsString("row.dataset.draftSelected==='1' || checkbox?.checked", $create);
        $this->assertStringContainsString("if(checkbox?.checked) row.dataset.draftSelected='1'", $create);
        $this->assertStringContainsString('w-32 px-3 py-3 text-right">Giá thu', $create);
        $this->assertStringContainsString('$workflow->updateDraft((int) $user->id, $priceList, $header, $items, $canApprove)', $controller);
        $this->assertStringContainsString('$workflow->submit((int) $user->id, $priceList, $canApprove)', $controller);
        $this->assertStringContainsString('public function submit(int $userId, int $priceListId, bool $approverScope = false)', $workflow);
        $this->assertStringContainsString('bool $approverScope = false', $workflow);
        $adminIndex = file_get_contents(base_path('Modules/Pharma/resources/views/livewire/price-list/index.blade.php'));
        $adminIndexComponent = file_get_contents(base_path('Modules/Pharma/Livewire/PriceList/Index.php'));
        $this->assertStringContainsString('Phê duyệt &amp; kích hoạt', $adminIndex);
        $this->assertStringContainsString("confirm({{ \$list->id }},'approve')", $adminIndex);
        $this->assertStringContainsString("if (\$this->confirmingAction === 'approve')", $adminIndexComponent);
        $this->assertStringContainsString('aria-label="Thao tác cho {{ $list->name }}">•••</button>', $adminIndex);
        $this->assertStringContainsString('Chi tiết bảng giá', $adminIndex);
        $this->assertStringContainsString('Sửa thông tin', $adminIndex);
        $this->assertStringNotContainsString('>Xem</a>', $adminIndex);
        $this->assertStringNotContainsString('>Thêm <svg', $adminIndex);
        $this->assertStringContainsString('whitespace-nowrap px-4 py-3 text-right">Thao tác</th>', $view);
        $this->assertStringContainsString('data-price-list-actions', $view);
        $this->assertStringContainsString('aria-label="Mở menu thao tác', $view);
        $this->assertStringContainsString('grid min-w-0 w-full gap-2.5 px-0.5 lg:hidden', $view);
        $this->assertStringContainsString('relative min-w-0 w-full max-w-full overflow-visible rounded-3xl', $view);
        $this->assertStringContainsString('max-w-[calc(100vw-3rem)]', $view);
        $this->assertStringContainsString('>•••</summary>', $view);
        $this->assertStringContainsString('w-[12%] px-4 py-3">Trạng thái', $view);
        $this->assertStringContainsString('whitespace-nowrap rounded-full px-2 py-1 text-[11px]', $view);
        $this->assertStringNotContainsString('title="Tải Excel đã xuất"', $view);
        $this->assertStringContainsString('Sửa thông tin', $view);
        $this->assertStringContainsString('Phê duyệt & kích hoạt', $view);
        $this->assertStringContainsString('Xuất Excel mới', $view);
        $this->assertStringContainsString('Tải Excel đã xuất', $view);
        $this->assertStringContainsString('Chuyển sang PDF', $view);
        $this->assertStringNotContainsString('>Xem</a><a href="{{ route(\'client.pharma.price-lists.show\',$priceList->id) }}#price-list-actions"', $view);
        $this->assertStringNotContainsString('Tài liệu bảng giá', $detail);
        $this->assertStringContainsString("'actual_receivable_price' => ['nullable', 'array']", $controller);
        $this->assertStringContainsString("'invoice_price' => ['nullable', 'array']", $controller);
        $this->assertStringContainsString('public function editableProducts(int $userId, PriceList $priceList', $workflow);
        $this->assertStringContainsString('Giá Bán (VAT) *', $create);
        $this->assertStringContainsString('Bảng giá khách hàng', $create);
        $this->assertStringContainsString('Bảng giá chung', $create);
        $this->assertStringNotContainsString("name=\"manager_user_id\"", $create);
        $this->assertStringContainsString('Kích hoạt trực tiếp', $create);
        $this->assertStringNotContainsString('>Giá gốc<', $create);
        $this->assertStringContainsString('data-money-input', $create);

        $this->assertStringContainsString("public const STATUS_PENDING_APPROVAL = 'pending_approval'", $model);
        $this->assertStringContainsString("public const STATUS_REJECTED = 'rejected'", $model);
        $this->assertStringContainsString("public const STATUS_PENDING_DEACTIVATION = 'pending_deactivation'", $model);
        $this->assertStringContainsString("public const STATUS_INACTIVE = 'inactive'", $model);
        $this->assertStringContainsString("public const TYPE_GLOBAL = 'global'", $model);
        $this->assertStringContainsString("public const TYPE_CUSTOMER = 'customer'", $model);
        $this->assertStringContainsString('PriceListApprovalWorkflow $approval', $controller);
        $this->assertStringContainsString('public function approve(int $approverUserId, int $priceListId)', $approval);
        $this->assertStringContainsString('public function reject(int $approverUserId, int $priceListId, string $reason)', $approval);
        $this->assertStringContainsString('return $this->manager->activate($list, $approverUserId);', $approval);
        $this->assertStringContainsString("'status' => PriceList::STATUS_REJECTED", $approval);
        $this->assertStringContainsString('approved_by', $approval);
        $this->assertStringContainsString('rejected_by', $approval);
        $this->assertStringContainsString('priceListApprovals(', $controller);
        $this->assertStringContainsString('priceListApproval(', $controller);
        $this->assertStringContainsString('approvePriceList(', $controller);
        $this->assertStringContainsString('rejectPriceList(', $controller);
        $this->assertStringContainsString("route('client.pharma.price-list-approvals.show'", $approvalQueue);
        $this->assertStringContainsString('Phê duyệt', $approvalDetail);
        $this->assertStringContainsString('Từ chối', $approvalDetail);
        $this->assertStringContainsString('class ApproverGlobalPriceListWorkflow', $globalWorkflow);
        $this->assertStringContainsString('public function createAndActivate(', $globalWorkflow);
        $this->assertStringContainsString("'type' => PriceList::TYPE_GLOBAL", $globalWorkflow);
        $this->assertStringContainsString('return $this->manager->activate($list, $approverUserId)->load([\'items\', \'globalUsers\']);', $globalWorkflow);
        $this->assertStringContainsString('Kích hoạt bảng giá chung', $create);
        $this->assertStringContainsString('$globalWorkflow->createAndActivate(', $controller);
        $this->assertStringContainsString('Hàng chờ phê duyệt', $approvalQueue);
        $this->assertStringContainsString('public function updateItemPrice(', $approval);
        $this->assertStringContainsString('public function removeItem(', $approval);
        $this->assertStringContainsString("pharma_price_list_approval_item_audits", $approval);
        $this->assertStringContainsString("'action' => 'price_changed'", $approval);
        $this->assertStringContainsString("'action' => 'removed'", $approval);
        $this->assertStringContainsString('Bảng giá phải còn ít nhất một sản phẩm', $approval);
        $this->assertStringContainsString('updatePriceListApprovalItem(', $controller);
        $this->assertStringContainsString('deletePriceListApprovalItem(', $controller);
        $this->assertStringContainsString('name="company_sale_price"', $approvalDetail);
        $this->assertStringContainsString('data-approval-money', $approvalDetail);
        $this->assertStringContainsString('>Cập nhật</button>', $approvalDetail);
        $this->assertStringContainsString('>Xóa</button>', $approvalDetail);
        $this->assertStringContainsString('Mọi thay đổi đều được ghi audit', $approvalDetail);
        $this->assertStringContainsString('class PriceListDeactivationWorkflow', $deactivation);
        $this->assertStringContainsString('public function request(int $userId', $deactivation);
        $this->assertStringContainsString('public function approveRequest(int $approverUserId', $deactivation);
        $this->assertStringContainsString('public function deactivateDirectly(int $approverUserId', $deactivation);
        $this->assertStringContainsString("'status' => PriceList::STATUS_PENDING_DEACTIVATION", $deactivation);
        $this->assertStringContainsString("'status' => PriceList::STATUS_INACTIVE", $deactivation);
        $this->assertStringContainsString('Ngừng kích hoạt…', $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.deactivation.request',\$priceList->id)", $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.deactivate',\$priceList->id)", $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.deactivation.approve',\$priceList->id)", $view);
        $this->assertStringContainsString('data-price-list-deactivation-open', $view);
        $this->assertStringContainsString('id="price-list-deactivation-dialog"', $view);
        $this->assertStringContainsString('name="deactivation_reason"', $view);
        $this->assertStringContainsString('Chấp nhận ngừng kích hoạt', $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.activate',\$priceList->id)", $view);
        $this->assertStringContainsString("priceList->status==='inactive' && \$canApprove", $view);
        $this->assertStringContainsString('Kích hoạt trở lại', $view);
        $this->assertStringContainsString('Xóa vĩnh viễn bảng giá Ngưng này?', $view);
        $this->assertStringContainsString('Toàn bộ file Excel và PDF đã xuất cũng sẽ bị xóa.', $view);
        $this->assertStringContainsString('public function activatePriceList(', $controller);
        $this->assertStringContainsString('PriceListManager $manager', $controller);
        $this->assertStringContainsString('abort_unless($list->status === PriceList::STATUS_INACTIVE, 404);', $controller);
        $this->assertStringContainsString('$manager->activate($list, (int) $user->id);', $controller);
        $this->assertStringNotContainsString("#price-list-actions", $view);
        $this->assertStringContainsString("redirect()->route('client.pharma.price-lists')", $controller);
        $this->assertStringNotContainsString('Yêu cầu ngừng kích hoạt', $detail);
        $this->assertStringNotContainsString('Chấp nhận ngừng kích hoạt', $detail);
        $this->assertStringNotContainsString('Ngừng kích hoạt…', $detail);
        $this->assertStringContainsString('class PriceListShareExportService', $shareExport);
        $this->assertStringContainsString("PriceList::STATUS_ACTIVE", $shareExport);
        $this->assertStringContainsString("'Pharma/price-lists/exports/'", $shareExport);
        $this->assertStringContainsString("hash('sha256',\$token)", $shareExport);
        $this->assertStringContainsString("now()->addDays(30)", $shareExport);
        $this->assertStringContainsString("Crypt::encryptString(\$token)", $shareExport);
        $this->assertStringContainsString('public function latestForUser(int $priceListId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function latestForUserByPriceLists(array $priceListIds, int $userId)', $shareExport);
        $this->assertStringContainsString("where('created_by', \$userId)", $shareExport);
        $this->assertStringContainsString("whereNull('revoked_at')", $shareExport);
        $this->assertStringContainsString("Crypt::decryptString(\$share->token_encrypted)", $shareExport);
        $this->assertStringContainsString('use Illuminate\\Contracts\\Encryption\\DecryptException;', $shareExport);
        $this->assertStringContainsString('private function presentSafely(PriceListExportShare $share): ?array', $shareExport);
        $this->assertStringContainsString('catch (DecryptException)', $shareExport);
        $this->assertStringContainsString('->map(fn (PriceListExportShare $share) => $this->presentSafely($share))', $shareExport);
        $this->assertStringContainsString('return $share ? $this->presentSafely($share) : null;', $shareExport);
        $this->assertStringContainsString('$presented = $this->presentSafely($share);', $shareExport);
        $this->assertStringNotContainsString('catch (\\Throwable)', $shareExport);
        $this->assertStringContainsString('PriceListExcelDocumentLayout', $shareExport);
        $this->assertStringContainsString('PriceListExcelTypography', $shareExport);
        $this->assertStringContainsString('PriceListExportProfileService', $shareExport);
        $this->assertStringContainsString('exportPriceListShare(', $controller);
        $this->assertStringContainsString('downloadPriceListShare(', $controller);
        $this->assertStringContainsString('revokePriceListShare(', $controller);
        $this->assertStringContainsString('queuePriceListSharePdf(', $controller);
        $this->assertStringContainsString('priceListShareStatus(', $controller);
        $this->assertStringContainsString('downloadPriceListSharePdf(', $controller);
        $this->assertStringContainsString('public function queuePdf(int $shareId, int $userId)', $shareExport);
        $this->assertStringContainsString('GeneratePriceListSharePdf::dispatch', $shareExport);
        $this->assertStringContainsString('public function resolvePdf(string $token)', $shareExport);
        $this->assertStringContainsString("'pdf_status' => 'queued'", $shareExport);
        $this->assertStringContainsString("'pdf_completed_at' => 'datetime'", $shareModel);
        $this->assertStringContainsString('class GeneratePriceListSharePdf implements ShouldQueue', $pdfJob);
        $this->assertStringContainsString("'libreoffice'", $pdfJob);
        $this->assertStringContainsString("'Pharma/price-lists/exports/'", $shareExport);
        $this->assertStringContainsString("\$table->string('pdf_status', 20)", $pdfMigration);
        $this->assertStringContainsString("'currentExportShare' =>", $controller);
        $this->assertStringContainsString("'exportShares' => \$exportShares", $controller);
        $this->assertStringNotContainsString("session('price_list_share') ?? \$currentExportShare", $detail);
        $this->assertStringContainsString('Tải Excel đã xuất', $view);
        $this->assertStringNotContainsString('title="Tải Excel đã xuất"', $view);
        $this->assertStringContainsString('data-pwa-file-handoff', $view);
        $this->assertStringContainsString('id="price-list-pwa-file-handoff"', $view);
        $this->assertStringContainsString("matchMedia('(display-mode: standalone)')", $view);
        $this->assertStringContainsString("credentials:'same-origin'", $view);
        $this->assertStringContainsString("cache:'no-store'", $view);
        $this->assertStringContainsString('new File([blob]', $view);
        $this->assertStringContainsString('navigator.canShare', $view);
        $this->assertStringContainsString("navigator.share({files:[preparedPwaFile]", $view);
        $this->assertStringContainsString('URL.createObjectURL(preparedPwaFile)', $view);
        $this->assertStringContainsString('Tệp đã sẵn sàng', $view);
        $this->assertStringContainsString('Màn hình PWA vẫn được giữ nguyên', $view);
        $this->assertStringNotContainsString("window.open(anchor.href", $view);
        $this->assertStringNotContainsString("window.location=anchor.href", $view);
        $this->assertStringContainsString('price-list-search-input', $view);
        $this->assertStringContainsString('price-list-advanced-filters', $view);
        $this->assertStringContainsString('Bộ lọc nâng cao', $view);
        $this->assertStringContainsString('$hasAdvancedFilters', $view);
        $this->assertStringContainsString('@if($hasAnyFilters)', $view);
        $this->assertStringContainsString('Đặt lại bộ lọc', $view);
        $this->assertStringContainsString('grid grid-cols-2 gap-2 lg:contents', $view);
        $this->assertStringContainsString('data-status-rail', $view);
        $this->assertStringContainsString('overflow-x-auto', $view);
        $this->assertStringContainsString('flex w-max flex-nowrap', $view);
        $this->assertStringContainsString('$statusCount', $view);
        $this->assertStringContainsString('$disabled = !$active && $statusCount < 1', $view);
        $this->assertStringContainsString('aria-disabled="true"', $view);
        $this->assertStringContainsString('cursor-not-allowed select-none', $view);
        $this->assertStringContainsString("'active' => ['label' => 'Đang hiệu lực'", $view);
        $this->assertStringContainsString('block min-w-0 max-w-full rounded-3xl p-4 pr-[4.25rem]', $view);
        $this->assertStringContainsString('line-clamp-2', $view);
        $this->assertStringContainsString('{{ $priceList->items_count }} sản phẩm', $view);
        $this->assertStringContainsString('h-11 w-11', $view);
        $this->assertStringContainsString("matchMedia('(min-width: 1024px)')", $view);
        $this->assertStringNotContainsString('PDF ✓', $detail);
        $this->assertStringNotContainsString('Đang tạo PDF...', $detail);
        $this->assertStringNotContainsString('PDF đã sẵn sàng@elseif', $detail);
        $this->assertStringContainsString('prepareForLibreOffice', $pdfJob);
        $this->assertStringContainsString('freezeWrappedTableRowHeights', $pdfJob);
        $this->assertStringContainsString('stabilizePrintLayout', $pdfJob);
        $this->assertStringContainsString('setFitToWidth(1)', $pdfJob);
        $this->assertStringContainsString('setFitToHeight(0)', $pdfJob);
        $layout = file_get_contents(base_path('Modules/Pharma/Services/PriceListExcelDocumentLayout.php'));
        $this->assertStringNotContainsString('__PHARMA_PRICE_LIST_FOOTER__', $layout);
        $this->assertStringNotContainsString('setasign\\Fpdi', $pdfJob);
        $this->assertStringNotContainsString('stampPdfFooter', $pdfJob);
        $this->assertStringNotContainsString('extractPdfFooter', $pdfJob);
        $this->assertStringNotContainsString('new Fpdi()', $pdfJob);
        $this->assertStringNotContainsString('rasterizeSignatureFooterForLibreOffice', $pdfJob);
        $this->assertStringNotContainsString("setEditAs('twoCell')", $pdfJob);
        $this->assertStringNotContainsString('keepSignatureFooterTogether', $pdfJob);
        $this->assertStringNotContainsString('Worksheet::BREAK_ROW', $pdfJob);
        $this->assertStringNotContainsString('setBreak("A{$markerRow}"', $pdfJob);
        $this->assertStringContainsString("\$exportShares[(int)\$priceList->id]", $view);
        $this->assertStringContainsString("'exportHistory' =>", $controller);
        $this->assertStringContainsString('public function historyForUser(int $priceListId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function regeneratePdf(int $shareId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function deleteExport(int $shareId, int $userId)', $shareExport);
        $priceListManager = file_get_contents(base_path('Modules/Pharma/Services/PriceListManager.php'));
        $this->assertStringContainsString('private function deletePriceListWithArtifacts(PriceList $priceList): void', $priceListManager);
        $this->assertStringContainsString("PriceListExportShare::query()->where('price_list_id', \$priceList->id)->get()", $priceListManager);
        $this->assertStringContainsString("Storage::disk('local')->delete(\$path)", $priceListManager);
        $this->assertStringContainsString('PriceListManager $manager', $controller);
        $this->assertStringContainsString('$manager->deleteRemovable($list);', $controller);
        $this->assertStringContainsString('Đã xóa bảng giá Ngưng và toàn bộ tệp Excel / PDF liên quan.', $controller);
        $this->assertStringContainsString('if ($share === null)', $pdfJob);
        $this->assertStringContainsString('regeneratePriceListSharePdf(', $controller);
        $this->assertStringContainsString('deletePriceListExportShare(', $controller);
        $this->assertStringContainsString('emailPriceListExportShare(', $controller);
        $this->assertStringContainsString('queueEmail(', $shareExport);
        $emailJob = file_get_contents(base_path('Modules/Pharma/Jobs/SendPriceListExportEmail.php'));
        $this->assertStringContainsString('implements ShouldQueue', $emailJob);
        $this->assertStringContainsString('Mail::raw', $emailJob);
        $this->assertStringContainsString("->attach(", $emailJob);
        $this->assertStringNotContainsString('Gửi email', $detail);
        $this->assertStringNotContainsString("name=\"recipients\"", $detail);
        $this->assertStringNotContainsString("name=\"subject\"", $detail);
        $this->assertStringNotContainsString("name=\"message\"", $detail);
        $this->assertStringNotContainsString("name=\"attach_excel\"", $detail);
        $this->assertStringNotContainsString("name=\"attach_pdf\"", $detail);
        $this->assertStringNotContainsString('Gửi email →', $detail);
        $this->assertStringNotContainsString('copyExportUrl', $detail);
        $this->assertStringNotContainsString('navigator.clipboard', $detail);
        $this->assertStringNotContainsString('Đã sao chép', $detail);
        $this->assertStringContainsString('min-h-11', $detail);
        $this->assertStringContainsString('grid grid-cols-2 gap-x-4 gap-y-5', $detail);
        $this->assertStringContainsString("['Người phụ trách',\$priceList->manager?->name]", $detail);
        $this->assertStringNotContainsString("['Mã bảng giá',\$priceList->code]", $detail);
        $this->assertStringNotContainsString('id="price-list-actions"', $detail);
        $this->assertStringNotContainsString('+ Xuất tài liệu', $detail);
        $this->assertStringNotContainsString('break-all text-xs', $detail);
        $this->assertStringContainsString('id="price-list-product-search"', $detail);
        $this->assertStringContainsString('Tìm tên thuốc, mã thuốc, quy cách...', $detail);
        $this->assertStringContainsString('data-price-list-product', $detail);
        $this->assertStringContainsString('data-search=', $detail);
        $this->assertStringContainsString('data-search="{{ $productSearchText }}"', $detail);
        $this->assertStringNotContainsString('IlluminateSupportStr', $detail);
        $this->assertStringNotContainsString('Illuminate\\Support\\Str::', $detail);
        $this->assertStringContainsString("toLocaleLowerCase('vi')", $detail);
        $this->assertStringContainsString("normalize('NFD')", $detail);
        $this->assertStringContainsString("item.hidden=!matched", $detail);
        $this->assertStringContainsString("visible+' / '+items.length", $detail);
        $this->assertStringContainsString('Không tìm thấy sản phẩm phù hợp.', $detail);
        $this->assertStringContainsString('Phê duyệt & kích hoạt', $detail);
        $this->assertStringContainsString('Kích hoạt ngay', $detail);
        $this->assertStringContainsString('public function activateOwnDraft(int $approverUserId, int $priceListId)', $approval);
        $this->assertStringContainsString('activateOwnDraftPriceList(', $controller);
        $this->assertStringContainsString('$this->assertPending($list);', $approval);
        $this->assertStringContainsString('Phê duyệt & Kích hoạt', $approvalDetail);
        $this->assertStringContainsString('name="rejection_reason"', $approvalDetail);
        $this->assertStringContainsString('$selfApprovalBlocked', $approvalDetail);
        $this->assertStringNotContainsString('Admin::', $approvalQueue);
        $this->assertStringNotContainsString('Admin::', $approvalDetail);
        $this->assertStringNotContainsString('Admin::', $detail);
    }
}
