<?php

namespace Tests\Feature\ClientApps;

use Tests\TestCase;

class PharmaPriceListsCapabilityTest extends TestCase
{
    public function test_client_price_lists_are_scoped_to_managed_lists_without_admin_reuse(): void
    {
        $manifest = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/manifest.php'));
        $routes = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/routes.php'));
        $controller = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/Http/Controllers/PharmaApplicationController.php'));
        $service = file_get_contents(base_path('Modules/Pharma/Services/UserPriceListWorkspace.php'));
        $view = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-lists.blade.php'));
        $detail = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-show.blade.php'));
        $create = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-create.blade.php'));
        $workflow = file_get_contents(base_path('Modules/Pharma/Services/UserPriceListWorkflow.php'));
        $model = file_get_contents(base_path('Modules/Pharma/Models/PriceList.php'));
        $approval = file_get_contents(base_path('Modules/Pharma/Services/PriceListApprovalWorkflow.php'));
        $approvalQueue = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-approvals.blade.php'));
        $approvalDetail = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-approval-show.blade.php'));
        $globalWorkflow = file_get_contents(base_path('Modules/Pharma/Services/ApproverGlobalPriceListWorkflow.php'));
        $deactivation = file_get_contents(base_path('Modules/Pharma/Services/PriceListDeactivationWorkflow.php'));
        $shareExport = file_get_contents(base_path('Modules/Pharma/Services/PriceListShareExportService.php'));

        $this->assertStringContainsString("'route' => 'client.pharma.price-lists'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.view'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.create'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.submit'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.approve'", $manifest);
        $priceListFeature = require base_path('Modules/ClientPortal/Applications/Pharma/manifest.php');
        $priceListActions = $priceListFeature['features']['price-lists']['actions'] ?? [];
        $this->assertSame('client.pharma.price-lists.create', $priceListActions['create']['permission'] ?? null);
        $this->assertSame('client.pharma.price-lists.submit', $priceListActions['submit']['permission'] ?? null);
        $this->assertSame('client.pharma.price-lists.approve', $priceListActions['approve']['permission'] ?? null);

        $this->assertStringContainsString("->name('price-lists')", $routes);
        $this->assertStringContainsString("->name('price-lists.show')", $routes);
        $this->assertStringContainsString("->name('price-lists.create')", $routes);
        $this->assertStringContainsString("->name('price-lists.store')", $routes);
        $this->assertStringContainsString("->name('price-lists.global.store')", $routes);
        $this->assertStringContainsString("->name('price-lists.submit')", $routes);
        $this->assertStringContainsString("->name('price-lists.edit')", $routes);
        $this->assertStringContainsString("->name('price-lists.update')", $routes);
        $this->assertStringContainsString("->name('price-lists.delete')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivation.request')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivation.approve')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivate')", $routes);
        $this->assertStringContainsString("->name('price-lists.export-share')", $routes);
        $this->assertStringContainsString("->name('client.pharma.price-lists.share.download')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.revoke')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.show')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.approve')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.reject')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.items.update')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.items.delete')", $routes);
        $this->assertStringContainsString('client.feature:pharma,price-lists', $routes);
        $this->assertStringNotContainsString('auth:admin', $routes);

        $this->assertStringContainsString('UserPriceListWorkspace $workspace', $controller);
        $this->assertStringContainsString('$workspace->browse(', $controller);
        $this->assertStringContainsString('$workspace->findVisible(', $controller);
        $this->assertStringContainsString('findVisible((int) $user->id, $priceList, $canApprove)', $controller);
        $this->assertStringContainsString('abort_if($list === null, 404)', $controller);

        $this->assertStringContainsString("where('manager_user_id', \$userId)", $service);
        $this->assertStringContainsString('public function findManaged(int $userId, int $priceListId)', $service);
        $this->assertStringContainsString('public function findVisible(int $userId, int $priceListId, bool $approverScope = false)', $service);
        $this->assertStringNotContainsString('auth(', $service);

        $this->assertStringContainsString('Bảng giá của tôi', $view);
        $this->assertStringContainsString('Chỉ hiển thị các bảng giá bạn là người phụ trách', $view);
        $this->assertStringContainsString('25,50,100', $view);
        $this->assertStringContainsString("setTimeout(()=>f.requestSubmit(),350)", $view);
        $this->assertStringContainsString('name="from_date"', $view);
        $this->assertStringContainsString('name="to_date"', $view);
        $this->assertStringContainsString('Đặt lại', $view);
        $this->assertStringContainsString("'from_date' => \$fromDate", $view);
        $this->assertStringContainsString("'to_date' => \$toDate", $view);
        $this->assertStringContainsString("whereDate('effective_from', '>='", $service);
        $this->assertStringContainsString("whereDate('effective_from', '<='", $service);
        $this->assertStringContainsString('?int $managerUserId = null', $service);
        $this->assertStringContainsString('bool $approverScope = false', $service);
        $this->assertStringContainsString("->where('manager_user_id', \$managerUserId)", $service);
        $this->assertStringContainsString("'manager_user_id' => ['nullable', 'integer']", $controller);
        $this->assertStringContainsString('managerUserId: $managerUserId', $controller);
        $this->assertStringContainsString('approverScope: $canApprove', $controller);
        $this->assertStringContainsString('name="manager_user_id"', $view);
        $this->assertStringContainsString('Tất cả User', $view);
        $this->assertStringContainsString('Người phụ trách', $view);
        $this->assertStringContainsString("'manager_user_id' => \$managerUserId", $view);
        $this->assertStringNotContainsString('Admin::', $view);

        $this->assertStringContainsString('Giá kê khai', $detail);
        $this->assertStringContainsString('Giá bán CT', $detail);
        $this->assertStringContainsString('Giá thu / Giá HĐ', $detail);
        $this->assertStringContainsString('Gửi duyệt', $detail);
        $this->assertStringContainsString('Sửa Nháp', $detail);
        $this->assertStringContainsString('Xóa', $detail);
        $this->assertStringContainsString("route('client.pharma.price-lists.edit'", $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.delete'", $view);
        $this->assertStringContainsString("'draft' => 'Nháp'", $view);
        $this->assertStringContainsString('STATUS_PENDING_APPROVAL', $detail);

        $this->assertStringContainsString('Tạo bảng giá cho khách hàng', $create);
        $this->assertStringContainsString('<x-select-search', $create);
        $this->assertStringNotContainsString('<x-search-select', $create);
        $this->assertStringContainsString("document.getElementById('client-price-list-customer')", $create);
        $this->assertStringContainsString('window.TomSelect', $create);
        $this->assertStringContainsString('!customer.tomselect', $create);
        $this->assertStringContainsString("plugins: ['dropdown_input']", $create);
        $this->assertStringContainsString('02 · Bảng giá gốc', $create);
        $this->assertStringContainsString('03 · Sản phẩm & giá', $create);
        $this->assertStringContainsString('04 · Kiểm tra & lưu', $create);
        $this->assertStringContainsString('select-all-source-products', $create);
        $this->assertStringContainsString('source-product-search', $create);
        $this->assertStringContainsString('clear-source-product-search', $create);
        $this->assertStringContainsString('sessionStorage.setItem', $create);
        $this->assertStringContainsString('sessionStorage.getItem', $create);
        $this->assertStringContainsString('source_price_list_id', $create);
        $this->assertStringNotContainsString('sticky bottom-4', $create);
        $this->assertStringContainsString('Lưu bảng giá Nháp', $create);
        $this->assertStringContainsString('name="selected[', $create);
        $this->assertStringContainsString('name="company_price[', $create);
        $this->assertStringContainsString('Giá Bán (VAT) *', $create);
        $this->assertStringContainsString('Bảng giá chung', $create);
        $this->assertStringContainsString("name=\"manager_user_id\"", $create);
        $this->assertStringContainsString('Kích hoạt bảng giá chung', $create);
        $this->assertStringNotContainsString('>Giá gốc<', $create);
        $this->assertStringContainsString('data-money-input', $create);
        $this->assertStringContainsString("replace(/\\D/g, '')", $create);

        $this->assertStringContainsString("public const STATUS_PENDING_APPROVAL = 'pending_approval'", $model);
        $this->assertStringContainsString("public const STATUS_REJECTED = 'rejected'", $model);
        $this->assertStringContainsString("public const STATUS_PENDING_DEACTIVATION = 'pending_deactivation'", $model);
        $this->assertStringContainsString("'deactivation_reason'", $model);
        $this->assertStringContainsString("'rejection_reason'", $model);
        $this->assertStringContainsString('public function createDraft(int $userId', $workflow);
        $this->assertStringContainsString('public function sourcePriceLists(int $userId)', $workflow);
        $this->assertStringContainsString('public function sourceProducts(int $userId, int $sourcePriceListId)', $workflow);
        $this->assertStringContainsString("->where('type', PriceList::TYPE_GLOBAL)", $workflow);
        $this->assertStringContainsString('->activeAt(now())', $workflow);
        $this->assertStringContainsString("whereDoesntHave('globalUsers')", $workflow);
        $this->assertStringContainsString("orWhereHas('globalUsers'", $workflow);
        $this->assertStringContainsString("'source_price_list_id'", $workflow);
        $this->assertStringContainsString("'declared_price_snapshot'", $workflow);
        $this->assertStringContainsString('public function updateDraft(int $userId', $workflow);
        $this->assertStringContainsString('public function deleteDraft(int $userId', $workflow);
        $this->assertStringContainsString('private function draftForUser(int $userId', $workflow);
        $this->assertStringContainsString('private function editableForUser(int $userId', $workflow);
        $this->assertStringContainsString("->whereIn('status', [PriceList::STATUS_DRAFT, PriceList::STATUS_REJECTED])", $workflow);
        $this->assertStringContainsString("->where('status', PriceList::STATUS_DRAFT)", $workflow);
        $this->assertStringContainsString('public function submit(int $userId', $workflow);
        $this->assertStringContainsString("'manager_user_id'", $workflow);
        $this->assertStringContainsString("'submitted_by'", $workflow);
        $this->assertStringContainsString("'status' => PriceList::STATUS_PENDING_APPROVAL", $workflow);
        $this->assertStringContainsString('Chỉ bảng giá Nháp hoặc đã bị từ chối mới được gửi duyệt.', $workflow);
        $this->assertStringContainsString("'rejection_reason' => null", $workflow);
        $this->assertStringContainsString('STATUS_REJECTED', $detail);
        $this->assertStringContainsString('Bảng giá đã bị từ chối', $detail);
        $this->assertStringContainsString('Gửi duyệt lại', $detail);
        $this->assertStringContainsString("['draft', 'rejected']", $view);
        $this->assertStringContainsString('class ApproverGlobalPriceListWorkflow', $globalWorkflow);
        $this->assertStringContainsString('public function createAndActivate(int $approverUserId, int $managerUserId', $globalWorkflow);
        $this->assertStringContainsString("'type' => PriceList::TYPE_GLOBAL", $globalWorkflow);
        $this->assertStringContainsString('$list->globalUsers()->sync([$managerUserId])', $globalWorkflow);
        $this->assertStringContainsString('$this->manager->activate($list, $approverUserId)', $globalWorkflow);
        $this->assertStringContainsString("userCan(\$user, 'client.pharma.price-lists.approve')", $controller);
        $this->assertStringContainsString('storeGlobalPriceList(', $controller);
        $this->assertStringContainsString('class PriceListApprovalWorkflow', $approval);
        $this->assertStringContainsString("->where('status', PriceList::STATUS_PENDING_APPROVAL)", $approval);
        $this->assertStringContainsString('assertPendingAndIndependent', $approval);
        $this->assertStringContainsString("'status' => PriceList::STATUS_REJECTED", $approval);
        $this->assertStringContainsString('$this->manager->activate($list, $approverUserId)', $approval);
        $this->assertStringContainsString('Người tạo, người phụ trách hoặc người gửi không được tự phê duyệt', $approval);
        $this->assertStringContainsString('public function pendingCount(): int', $approval);
        $this->assertStringContainsString("'pendingApprovalCount' => \$canApprove ? \$approval->pendingCount() : null", $controller);
        $this->assertStringContainsString("route('client.pharma.price-list-approvals')", $view);
        $this->assertStringContainsString('Yêu cầu cần tôi duyệt', $view);
        $this->assertStringContainsString('$pendingApprovalCount ?? 0', $view);
        $this->assertStringNotContainsString('>Hàng chờ duyệt</a>', $view);
        $this->assertStringContainsString('Hàng chờ phê duyệt', $approvalQueue);
        $this->assertStringContainsString('public function updateItemPrice(', $approval);
        $this->assertStringContainsString('public function removeItem(', $approval);
        $this->assertStringContainsString("pharma_price_list_approval_item_audits", $approval);
        $this->assertStringContainsString("'action' => 'price_changed'", $approval);
        $this->assertStringContainsString("'action' => 'removed'", $approval);
        $this->assertStringContainsString('Bảng giá phải còn ít nhất một sản phẩm', $approval);
        $this->assertStringContainsString('updatePriceListApprovalItem(', $controller);
        $this->assertStringContainsString('deletePriceListApprovalItem(', $controller);
        $this->assertStringContainsString('name="company_sale_price"', $approvalDetail);
        $this->assertStringContainsString('data-approval-money', $approvalDetail);
        $this->assertStringContainsString('>Cập nhật</button>', $approvalDetail);
        $this->assertStringContainsString('>Xóa</button>', $approvalDetail);
        $this->assertStringContainsString('Mọi thay đổi đều được ghi audit', $approvalDetail);
        $this->assertStringContainsString('class PriceListDeactivationWorkflow', $deactivation);
        $this->assertStringContainsString('public function request(int $userId', $deactivation);
        $this->assertStringContainsString('public function approveRequest(int $approverUserId', $deactivation);
        $this->assertStringContainsString('public function deactivateDirectly(int $approverUserId', $deactivation);
        $this->assertStringContainsString("'status' => PriceList::STATUS_PENDING_DEACTIVATION", $deactivation);
        $this->assertStringContainsString("'status' => PriceList::STATUS_INACTIVE", $deactivation);
        $this->assertStringContainsString('Yêu cầu ngừng kích hoạt', $detail);
        $this->assertStringContainsString('Chấp nhận ngừng kích hoạt', $detail);
        $this->assertStringContainsString('Ngừng kích hoạt', $detail);
        $this->assertStringContainsString('class PriceListShareExportService', $shareExport);
        $this->assertStringContainsString("PriceList::STATUS_ACTIVE", $shareExport);
        $this->assertStringContainsString("'Pharma/price-lists/exports/'", $shareExport);
        $this->assertStringContainsString("hash('sha256',\$token)", $shareExport);
        $this->assertStringContainsString("now()->addDays(30)", $shareExport);
        $this->assertStringContainsString("Crypt::encryptString(\$token)", $shareExport);
        $this->assertStringContainsString('public function latestForUser(int $priceListId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function latestForUserByPriceLists(array $priceListIds, int $userId)', $shareExport);
        $this->assertStringContainsString("where('created_by', \$userId)", $shareExport);
        $this->assertStringContainsString("whereNull('revoked_at')", $shareExport);
        $this->assertStringContainsString("Crypt::decryptString(\$share->token_encrypted)", $shareExport);
        $this->assertStringContainsString('PriceListExcelDocumentLayout', $shareExport);
        $this->assertStringContainsString('PriceListExcelTypography', $shareExport);
        $this->assertStringContainsString('PriceListExportProfileService', $shareExport);
        $this->assertStringContainsString('exportPriceListShare(', $controller);
        $this->assertStringContainsString('downloadPriceListShare(', $controller);
        $this->assertStringContainsString('revokePriceListShare(', $controller);
        $this->assertStringContainsString("'currentExportShare' =>", $controller);
        $this->assertStringContainsString("'exportShares' => \$exportShares", $controller);
        $this->assertStringContainsString("session('price_list_share') ?? \$currentExportShare", $detail);
        $this->assertStringContainsString('title="Tải Excel đã xuất"', $view);
        $this->assertStringContainsString("\$exportShares[(int)\$priceList->id]", $view);
        $this->assertStringContainsString('Xuất & chia sẻ bảng giá Excel', $detail);
        $this->assertStringContainsString('Mẫu bảng giá', $detail);
        $this->assertStringContainsString('Sao chép liên kết', $detail);
        $this->assertStringContainsString('navigator.share', $detail);
        $this->assertStringContainsString('Thu hồi link', $detail);
        $this->assertStringContainsString('Phê duyệt & Kích hoạt', $approvalDetail);
        $this->assertStringContainsString('name="rejection_reason"', $approvalDetail);
        $this->assertStringContainsString('$selfApprovalBlocked', $approvalDetail);
        $this->assertStringNotContainsString('Admin::', $approvalQueue);
        $this->assertStringNotContainsString('Admin::', $approvalDetail);
        $this->assertStringNotContainsString('Admin::', $detail);
    }
}
