<?php

namespace Tests\Feature\ClientApps;

use Tests\TestCase;

class PharmaPriceListsCapabilityTest extends TestCase
{
    public function test_client_price_lists_are_scoped_to_managed_lists_without_admin_reuse(): void
    {
        $manifest = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/manifest.php'));
        $routes = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/routes.php'));
        $controller = file_get_contents(base_path('Modules/ClientPortal/Applications/Pharma/Http/Controllers/PharmaApplicationController.php'));
        $service = file_get_contents(base_path('Modules/Pharma/Services/UserPriceListWorkspace.php'));
        $view = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-lists.blade.php'));
        $detail = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-show.blade.php'));
        $create = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-create.blade.php'));
        $workflow = file_get_contents(base_path('Modules/Pharma/Services/UserPriceListWorkflow.php'));
        $model = file_get_contents(base_path('Modules/Pharma/Models/PriceList.php'));
        $approval = file_get_contents(base_path('Modules/Pharma/Services/PriceListApprovalWorkflow.php'));
        $approvalQueue = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-approvals.blade.php'));
        $approvalDetail = file_get_contents(base_path('Modules/ClientPortal/resources/views/applications/pharma/price-list-approval-show.blade.php'));
        $globalWorkflow = file_get_contents(base_path('Modules/Pharma/Services/ApproverGlobalPriceListWorkflow.php'));
        $deactivation = file_get_contents(base_path('Modules/Pharma/Services/PriceListDeactivationWorkflow.php'));
        $shareExport = file_get_contents(base_path('Modules/Pharma/Services/PriceListShareExportService.php'));
        $shareModel = file_get_contents(base_path('Modules/Pharma/Models/PriceListExportShare.php'));
        $pdfJob = file_get_contents(base_path('Modules/Pharma/Jobs/GeneratePriceListSharePdf.php'));
        $pdfMigration = file_get_contents(base_path('Modules/Pharma/database/migrations/2026_09_27_204000_add_pdf_fields_to_price_list_export_shares.php'));

        $this->assertStringContainsString("'route' => 'client.pharma.price-lists'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.view'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.create'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.submit'", $manifest);
        $this->assertStringContainsString("'permission' => 'client.pharma.price-lists.approve'", $manifest);
        $priceListFeature = require base_path('Modules/ClientPortal/Applications/Pharma/manifest.php');
        $priceListActions = $priceListFeature['features']['price-lists']['actions'] ?? [];
        $this->assertSame('client.pharma.price-lists.create', $priceListActions['create']['permission'] ?? null);
        $this->assertSame('client.pharma.price-lists.submit', $priceListActions['submit']['permission'] ?? null);
        $this->assertSame('client.pharma.price-lists.approve', $priceListActions['approve']['permission'] ?? null);

        $this->assertStringContainsString("->name('price-lists')", $routes);
        $this->assertStringContainsString("->name('price-lists.show')", $routes);
        $this->assertStringContainsString("->name('price-lists.create')", $routes);
        $this->assertStringContainsString("->name('price-lists.store')", $routes);
        $this->assertStringContainsString("->name('price-lists.global.store')", $routes);
        $this->assertStringContainsString("->name('price-lists.submit')", $routes);
        $this->assertStringContainsString("->name('price-lists.activate-own-draft')", $routes);
        $this->assertStringContainsString("->name('price-lists.edit')", $routes);
        $this->assertStringContainsString("->name('price-lists.update')", $routes);
        $this->assertStringContainsString("->name('price-lists.delete')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivation.request')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivation.approve')", $routes);
        $this->assertStringContainsString("->name('price-lists.deactivate')", $routes);
        $this->assertStringContainsString("->name('price-lists.export-share')", $routes);
        $this->assertStringContainsString("->name('client.pharma.price-lists.share.download')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.revoke')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.pdf.queue')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.status')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.email')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.pdf.regenerate')", $routes);
        $this->assertStringContainsString("->name('price-lists.share.export.delete')", $routes);
        $this->assertStringContainsString("->name('client.pharma.price-lists.share.pdf')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.show')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.approve')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.reject')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.items.update')", $routes);
        $this->assertStringContainsString("->name('price-list-approvals.items.delete')", $routes);
        $this->assertStringContainsString('client.feature:pharma,price-lists', $routes);
        $this->assertStringNotContainsString('auth:admin', $routes);

        $this->assertStringContainsString('UserPriceListWorkspace $workspace', $controller);
        $this->assertStringContainsString('$workspace->browse(', $controller);
        $this->assertStringContainsString('$workspace->findVisible(', $controller);
        $this->assertStringContainsString('findVisible((int) $user->id, $priceList, $canApprove)', $controller);
        $this->assertStringContainsString('abort_if($list === null, 404)', $controller);

        $this->assertStringContainsString("where('manager_user_id', \$userId)", $service);
        $this->assertStringContainsString('public function findManaged(int $userId, int $priceListId)', $service);
        $this->assertStringContainsString('public function findVisible(int $userId, int $priceListId, bool $approverScope = false)', $service);
        $this->assertStringNotContainsString('auth(', $service);

        $this->assertStringContainsString('Bảng giá của tôi', $view);
        $this->assertStringContainsString('Chỉ hiển thị các bảng giá bạn là người phụ trách', $view);
        $this->assertStringContainsString('25,50,100', $view);
        $this->assertStringContainsString("setTimeout(()=>f.requestSubmit(),350)", $view);
        $this->assertStringContainsString('name="from_date"', $view);
        $this->assertStringContainsString('name="to_date"', $view);
        $this->assertStringContainsString('Đặt lại', $view);
        $this->assertStringContainsString("'from_date' => \$fromDate", $view);
        $this->assertStringContainsString("'to_date' => \$toDate", $view);
        $this->assertStringContainsString("whereDate('effective_from', '>='", $service);
        $this->assertStringContainsString("whereDate('effective_from', '<='", $service);
        $this->assertStringContainsString('?int $managerUserId = null', $service);
        $this->assertStringContainsString('bool $approverScope = false', $service);
        $this->assertStringContainsString("->where('manager_user_id', \$managerUserId)", $service);
        $this->assertStringContainsString("'manager_user_id' => ['nullable', 'integer']", $controller);
        $this->assertStringContainsString('managerUserId: $managerUserId', $controller);
        $this->assertStringContainsString('approverScope: $canApprove', $controller);
        $this->assertStringContainsString('name="manager_user_id"', $view);
        $this->assertStringContainsString('Tất cả User', $view);
        $this->assertStringContainsString('Người phụ trách', $view);
        $this->assertStringContainsString("'manager_user_id' => \$managerUserId", $view);
        $this->assertStringNotContainsString('Admin::', $view);

        $this->assertStringContainsString('Giá kê khai', $detail);
        $this->assertStringContainsString('Giá bán CT', $detail);
        $this->assertStringContainsString('Giá thu / Giá HĐ', $detail);
        $this->assertStringContainsString('Gửi duyệt', $detail);
        $this->assertStringContainsString('Sửa Nháp', $detail);
        $this->assertStringContainsString('Xóa', $detail);
        $this->assertStringContainsString("route('client.pharma.price-lists.edit'", $view);
        $this->assertStringContainsString("route('client.pharma.price-lists.delete'", $view);
        $this->assertStringContainsString("'draft' => 'Nháp'", $view);
        $this->assertStringContainsString('STATUS_PENDING_APPROVAL', $detail);

        $this->assertStringContainsString('Tạo bảng giá cho khách hàng', $create);
        $this->assertStringContainsString('<x-select-search', $create);
        $this->assertStringNotContainsString('<x-search-select', $create);
        $this->assertStringContainsString("document.getElementById('client-price-list-customer')", $create);
        $this->assertStringContainsString('window.TomSelect', $create);
        $this->assertStringContainsString('!customer.tomselect', $create);
        $this->assertStringContainsString("plugins: ['dropdown_input']", $create);
        $this->assertStringContainsString('01 · Khởi tạo bảng giá', $create);
        $this->assertStringContainsString('02 · Khách hàng & mục đích', $create);
        $this->assertStringContainsString('03 · Sản phẩm & giá', $create);
        $this->assertStringContainsString('04 · Xem lại & lưu', $create);
        $this->assertStringContainsString('id="source-product-search"', $create);
        $this->assertStringContainsString("new TomSelect(search, { plugins: ['dropdown_input']", $create);
        $this->assertStringContainsString('select-all-source-products', $create);
        $this->assertStringContainsString('source-product-search', $create);
        $this->assertStringNotContainsString('clear-source-product-search', $create);
        $this->assertStringContainsString("search?.tomselect?.on('change', filterRows)", $create);
        $this->assertStringContainsString("source.tomselect?.on('change', clearSourceError)", $create);
        $this->assertStringContainsString("bootstrapForm?.elements.namedItem('source_price_list_id')?.value", $create);
        $this->assertStringContainsString('source-price-list-error', $create);
        $this->assertStringContainsString("source?.tomselect?.getValue?.() || source?.value", $create);
        $this->assertStringContainsString('id="source-price-list" name="source_price_list_id"', $create);
        $this->assertStringContainsString('sessionStorage.setItem', $create);
        $this->assertStringContainsString('sessionStorage.getItem', $create);
        $this->assertStringContainsString('source_price_list_id', $create);
        $this->assertStringNotContainsString('sticky bottom-4', $create);
        $this->assertStringContainsString('Lưu bảng giá Nháp', $create);
        $this->assertStringContainsString('name="selected[', $create);
        $this->assertStringContainsString('name="company_price[', $create);
        $this->assertStringContainsString('Giá Bán (VAT) *', $create);
        $this->assertStringContainsString('Bảng giá chung', $create);
        $this->assertStringContainsString("name=\"manager_user_id\"", $create);
        $this->assertStringContainsString('Kích hoạt bảng giá chung', $create);
        $this->assertStringNotContainsString('>Giá gốc<', $create);
        $this->assertStringContainsString('data-money-input', $create);
        $this->assertStringContainsString("replace(/\\D/g, '')", $create);

        $this->assertStringContainsString("public const STATUS_PENDING_APPROVAL = 'pending_approval'", $model);
        $this->assertStringContainsString("public const STATUS_REJECTED = 'rejected'", $model);
        $this->assertStringContainsString("public const STATUS_PENDING_DEACTIVATION = 'pending_deactivation'", $model);
        $this->assertStringContainsString("'deactivation_reason'", $model);
        $this->assertStringContainsString("'rejection_reason'", $model);
        $this->assertStringContainsString('public function createDraft(int $userId', $workflow);
        $this->assertStringContainsString('public function sourcePriceLists(int $userId)', $workflow);
        $this->assertStringContainsString('public function sourceProducts(int $userId, int $sourcePriceListId)', $workflow);
        $this->assertStringContainsString("->where('type', PriceList::TYPE_GLOBAL)", $workflow);
        $this->assertStringContainsString('->activeAt(now())', $workflow);
        $this->assertStringContainsString("whereDoesntHave('globalUsers')", $workflow);
        $this->assertStringContainsString("orWhereHas('globalUsers'", $workflow);
        $this->assertStringContainsString("'source_price_list_id'", $workflow);
        $this->assertStringContainsString("'declared_price_snapshot'", $workflow);
        $this->assertStringContainsString('public function updateDraft(int $userId', $workflow);
        $this->assertStringContainsString('public function deleteDraft(int $userId', $workflow);
        $this->assertStringContainsString('private function draftForUser(int $userId', $workflow);
        $this->assertStringContainsString('private function editableForUser(int $userId', $workflow);
        $this->assertStringContainsString("->whereIn('status', [PriceList::STATUS_DRAFT, PriceList::STATUS_REJECTED])", $workflow);
        $this->assertStringContainsString("->where('status', PriceList::STATUS_DRAFT)", $workflow);
        $this->assertStringContainsString('public function submit(int $userId', $workflow);
        $this->assertStringContainsString("'manager_user_id'", $workflow);
        $this->assertStringContainsString("'submitted_by'", $workflow);
        $this->assertStringContainsString("'status' => PriceList::STATUS_PENDING_APPROVAL", $workflow);
        $this->assertStringContainsString('Chỉ bảng giá Nháp hoặc đã bị từ chối mới được gửi duyệt.', $workflow);
        $this->assertStringContainsString("'rejection_reason' => null", $workflow);
        $this->assertStringContainsString('STATUS_REJECTED', $detail);
        $this->assertStringContainsString('Bảng giá đã bị từ chối', $detail);
        $this->assertStringContainsString('Gửi duyệt lại', $detail);
        $this->assertStringContainsString("['draft', 'rejected']", $view);
        $this->assertStringContainsString('class ApproverGlobalPriceListWorkflow', $globalWorkflow);
        $this->assertStringContainsString('public function createAndActivate(int $approverUserId, int $managerUserId', $globalWorkflow);
        $this->assertStringContainsString("'type' => PriceList::TYPE_GLOBAL", $globalWorkflow);
        $this->assertStringContainsString('$list->globalUsers()->sync([$managerUserId])', $globalWorkflow);
        $this->assertStringContainsString('$this->manager->activate($list, $approverUserId)', $globalWorkflow);
        $this->assertStringContainsString("userCan(\$user, 'client.pharma.price-lists.approve')", $controller);
        $this->assertStringContainsString('storeGlobalPriceList(', $controller);
        $this->assertStringContainsString('class PriceListApprovalWorkflow', $approval);
        $this->assertStringContainsString("->where('status', PriceList::STATUS_PENDING_APPROVAL)", $approval);
        $this->assertStringContainsString('assertPendingAndIndependent', $approval);
        $this->assertStringContainsString("'status' => PriceList::STATUS_REJECTED", $approval);
        $this->assertStringContainsString('$this->manager->activate($list, $approverUserId)', $approval);
        $this->assertStringContainsString('Người tạo, người phụ trách hoặc người gửi không được tự phê duyệt', $approval);
        $this->assertStringContainsString('public function pendingCount(): int', $approval);
        $this->assertStringContainsString("'pendingApprovalCount' => \$canApprove ? \$approval->pendingCount() : null", $controller);
        $this->assertStringContainsString("route('client.pharma.price-list-approvals')", $view);
        $this->assertStringContainsString('Yêu cầu cần tôi duyệt', $view);
        $this->assertStringContainsString('$pendingApprovalCount ?? 0', $view);
        $this->assertStringNotContainsString('>Hàng chờ duyệt</a>', $view);
        $this->assertStringContainsString('Hàng chờ phê duyệt', $approvalQueue);
        $this->assertStringContainsString('public function updateItemPrice(', $approval);
        $this->assertStringContainsString('public function removeItem(', $approval);
        $this->assertStringContainsString("pharma_price_list_approval_item_audits", $approval);
        $this->assertStringContainsString("'action' => 'price_changed'", $approval);
        $this->assertStringContainsString("'action' => 'removed'", $approval);
        $this->assertStringContainsString('Bảng giá phải còn ít nhất một sản phẩm', $approval);
        $this->assertStringContainsString('updatePriceListApprovalItem(', $controller);
        $this->assertStringContainsString('deletePriceListApprovalItem(', $controller);
        $this->assertStringContainsString('name="company_sale_price"', $approvalDetail);
        $this->assertStringContainsString('data-approval-money', $approvalDetail);
        $this->assertStringContainsString('>Cập nhật</button>', $approvalDetail);
        $this->assertStringContainsString('>Xóa</button>', $approvalDetail);
        $this->assertStringContainsString('Mọi thay đổi đều được ghi audit', $approvalDetail);
        $this->assertStringContainsString('class PriceListDeactivationWorkflow', $deactivation);
        $this->assertStringContainsString('public function request(int $userId', $deactivation);
        $this->assertStringContainsString('public function approveRequest(int $approverUserId', $deactivation);
        $this->assertStringContainsString('public function deactivateDirectly(int $approverUserId', $deactivation);
        $this->assertStringContainsString("'status' => PriceList::STATUS_PENDING_DEACTIVATION", $deactivation);
        $this->assertStringContainsString("'status' => PriceList::STATUS_INACTIVE", $deactivation);
        $this->assertStringContainsString('Yêu cầu ngừng kích hoạt', $detail);
        $this->assertStringContainsString('Chấp nhận ngừng kích hoạt', $detail);
        $this->assertStringContainsString('Ngừng kích hoạt', $detail);
        $this->assertStringContainsString('class PriceListShareExportService', $shareExport);
        $this->assertStringContainsString("PriceList::STATUS_ACTIVE", $shareExport);
        $this->assertStringContainsString("'Pharma/price-lists/exports/'", $shareExport);
        $this->assertStringContainsString("hash('sha256',\$token)", $shareExport);
        $this->assertStringContainsString("now()->addDays(30)", $shareExport);
        $this->assertStringContainsString("Crypt::encryptString(\$token)", $shareExport);
        $this->assertStringContainsString('public function latestForUser(int $priceListId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function latestForUserByPriceLists(array $priceListIds, int $userId)', $shareExport);
        $this->assertStringContainsString("where('created_by', \$userId)", $shareExport);
        $this->assertStringContainsString("whereNull('revoked_at')", $shareExport);
        $this->assertStringContainsString("Crypt::decryptString(\$share->token_encrypted)", $shareExport);
        $this->assertStringContainsString('use Illuminate\\Contracts\\Encryption\\DecryptException;', $shareExport);
        $this->assertStringContainsString('private function presentSafely(PriceListExportShare $share): ?array', $shareExport);
        $this->assertStringContainsString('catch (DecryptException)', $shareExport);
        $this->assertStringContainsString('->map(fn (PriceListExportShare $share) => $this->presentSafely($share))', $shareExport);
        $this->assertStringContainsString('return $share ? $this->presentSafely($share) : null;', $shareExport);
        $this->assertStringContainsString('$presented = $this->presentSafely($share);', $shareExport);
        $this->assertStringNotContainsString('catch (\\Throwable)', $shareExport);
        $this->assertStringContainsString('PriceListExcelDocumentLayout', $shareExport);
        $this->assertStringContainsString('PriceListExcelTypography', $shareExport);
        $this->assertStringContainsString('PriceListExportProfileService', $shareExport);
        $this->assertStringContainsString('exportPriceListShare(', $controller);
        $this->assertStringContainsString('downloadPriceListShare(', $controller);
        $this->assertStringContainsString('revokePriceListShare(', $controller);
        $this->assertStringContainsString('queuePriceListSharePdf(', $controller);
        $this->assertStringContainsString('priceListShareStatus(', $controller);
        $this->assertStringContainsString('downloadPriceListSharePdf(', $controller);
        $this->assertStringContainsString('public function queuePdf(int $shareId, int $userId)', $shareExport);
        $this->assertStringContainsString('GeneratePriceListSharePdf::dispatch', $shareExport);
        $this->assertStringContainsString('public function resolvePdf(string $token)', $shareExport);
        $this->assertStringContainsString("'pdf_status' => 'queued'", $shareExport);
        $this->assertStringContainsString("'pdf_completed_at' => 'datetime'", $shareModel);
        $this->assertStringContainsString('class GeneratePriceListSharePdf implements ShouldQueue', $pdfJob);
        $this->assertStringContainsString("'libreoffice'", $pdfJob);
        $this->assertStringContainsString("'Pharma/price-lists/exports/'", $shareExport);
        $this->assertStringContainsString("\$table->string('pdf_status', 20)", $pdfMigration);
        $this->assertStringContainsString("'currentExportShare' =>", $controller);
        $this->assertStringContainsString("'exportShares' => \$exportShares", $controller);
        $this->assertStringContainsString("session('price_list_share') ?? \$currentExportShare", $detail);
        $this->assertStringContainsString('title="Tải Excel đã xuất"', $view);
        $this->assertStringContainsString('price-list-search-input', $view);
        $this->assertStringContainsString('price-list-advanced-filters', $view);
        $this->assertStringContainsString('Bộ lọc nâng cao', $view);
        $this->assertStringContainsString('$hasAdvancedFilters', $view);
        $this->assertStringContainsString('@if($hasAnyFilters)', $view);
        $this->assertStringContainsString('Đặt lại bộ lọc', $view);
        $this->assertStringContainsString('grid grid-cols-2 gap-2 lg:contents', $view);
        $this->assertStringContainsString('data-status-rail', $view);
        $this->assertStringContainsString('overflow-x-auto', $view);
        $this->assertStringContainsString('flex w-max flex-nowrap', $view);
        $this->assertStringContainsString('$statusCount', $view);
        $this->assertStringContainsString('$disabled = !$active && $statusCount < 1', $view);
        $this->assertStringContainsString('aria-disabled="true"', $view);
        $this->assertStringContainsString('cursor-not-allowed select-none', $view);
        $this->assertStringContainsString("'active' => ['label' => 'Đang hiệu lực'", $view);
        $this->assertStringContainsString('rounded-3xl p-4 pr-16', $view);
        $this->assertStringContainsString('line-clamp-2', $view);
        $this->assertStringContainsString('{{ $priceList->items_count }} sản phẩm', $view);
        $this->assertStringContainsString('h-11 w-11', $view);
        $this->assertStringContainsString("matchMedia('(min-width: 1024px)')", $view);
        $this->assertStringContainsString('PDF ✓', $detail);
        $this->assertStringContainsString('Đang tạo PDF...', $detail);
        $this->assertStringNotContainsString('PDF đã sẵn sàng@elseif', $detail);
        $this->assertStringContainsString('prepareForLibreOffice', $pdfJob);
        $this->assertStringContainsString('freezeWrappedTableRowHeights', $pdfJob);
        $this->assertStringContainsString('stabilizePrintLayout', $pdfJob);
        $this->assertStringContainsString('setFitToWidth(1)', $pdfJob);
        $this->assertStringContainsString('setFitToHeight(0)', $pdfJob);
        $layout = file_get_contents(base_path('Modules/Pharma/Services/PriceListExcelDocumentLayout.php'));
        $this->assertStringNotContainsString('__PHARMA_PRICE_LIST_FOOTER__', $layout);
        $this->assertStringNotContainsString('setasign\\Fpdi', $pdfJob);
        $this->assertStringNotContainsString('stampPdfFooter', $pdfJob);
        $this->assertStringNotContainsString('extractPdfFooter', $pdfJob);
        $this->assertStringNotContainsString('new Fpdi()', $pdfJob);
        $this->assertStringNotContainsString('rasterizeSignatureFooterForLibreOffice', $pdfJob);
        $this->assertStringNotContainsString("setEditAs('twoCell')", $pdfJob);
        $this->assertStringNotContainsString('keepSignatureFooterTogether', $pdfJob);
        $this->assertStringNotContainsString('Worksheet::BREAK_ROW', $pdfJob);
        $this->assertStringNotContainsString('setBreak("A{$markerRow}"', $pdfJob);
        $this->assertStringContainsString("\$exportShares[(int)\$priceList->id]", $view);
        $this->assertStringContainsString('+ Xuất tài liệu', $detail);
        $this->assertStringContainsString('Tài liệu đã xuất', $detail);
        $this->assertStringContainsString('Xuất Excel mới', $detail);
        $this->assertStringContainsString('Mẫu bảng giá', $detail);
        $this->assertStringContainsString('navigator.share', $detail);
        $this->assertStringContainsString('<details class="group', $detail);
        $this->assertStringContainsString('Tạo lại PDF', $detail);
        $this->assertStringContainsString('Xóa bản xuất', $detail);
        $this->assertStringContainsString('Tải PDF', $detail);
        $this->assertStringContainsString("price-lists.share.status", $detail);
        $this->assertStringContainsString("'exportHistory' =>", $controller);
        $this->assertStringContainsString('public function historyForUser(int $priceListId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function regeneratePdf(int $shareId, int $userId)', $shareExport);
        $this->assertStringContainsString('public function deleteExport(int $shareId, int $userId)', $shareExport);
        $this->assertStringContainsString('regeneratePriceListSharePdf(', $controller);
        $this->assertStringContainsString('deletePriceListExportShare(', $controller);
        $this->assertStringContainsString('emailPriceListExportShare(', $controller);
        $this->assertStringContainsString('queueEmail(', $shareExport);
        $emailJob = file_get_contents(base_path('Modules/Pharma/Jobs/SendPriceListExportEmail.php'));
        $this->assertStringContainsString('implements ShouldQueue', $emailJob);
        $this->assertStringContainsString('Mail::raw', $emailJob);
        $this->assertStringContainsString("->attach(", $emailJob);
        $this->assertStringContainsString('Gửi email', $detail);
        $this->assertStringContainsString("name=\"recipients\"", $detail);
        $this->assertStringContainsString("name=\"subject\"", $detail);
        $this->assertStringContainsString("name=\"message\"", $detail);
        $this->assertStringContainsString("name=\"attach_excel\"", $detail);
        $this->assertStringContainsString("name=\"attach_pdf\"", $detail);
        $this->assertStringContainsString('Gửi email →', $detail);
        $this->assertStringContainsString('copyExportUrl', $detail);
        $this->assertStringContainsString('navigator.clipboard', $detail);
        $this->assertStringContainsString('Đã sao chép', $detail);
        $this->assertStringContainsString('min-h-11', $detail);
        $this->assertStringContainsString('data-pwa-file-handoff', $detail);
        $this->assertStringContainsString("matchMedia('(display-mode: standalone)')", $detail);
        $this->assertStringContainsString("credentials:'same-origin'", $detail);
        $this->assertStringContainsString("cache:'no-store'", $detail);
        $this->assertStringContainsString('new File([blob]', $detail);
        $this->assertStringContainsString('navigator.canShare', $detail);
        $this->assertStringContainsString("navigator.share({files:[preparedPwaFile]", $detail);
        $this->assertStringContainsString('URL.createObjectURL(preparedPwaFile)', $detail);
        $this->assertStringContainsString('download.download=preparedPwaFile.name', $detail);
        $this->assertStringContainsString('download.click()', $detail);
        $this->assertStringContainsString('URL.revokeObjectURL(objectUrl)', $detail);
        $this->assertStringContainsString('Đã chuyển tệp sang trình tải xuống', $detail);
        $this->assertStringNotContainsString("window.open(anchor.href", $detail);
        $this->assertStringNotContainsString("window.location=anchor.href", $detail);
        $this->assertStringContainsString('Tệp đã sẵn sàng', $detail);
        $this->assertStringContainsString('Màn hình PWA vẫn được giữ nguyên', $detail);
        $this->assertStringContainsString('rounded-t-[28px]', $detail);
        $this->assertStringContainsString('max-h-[92dvh]', $detail);
        $this->assertStringContainsString('grid grid-cols-2 gap-x-4 gap-y-5', $detail);
        $this->assertStringContainsString('id="price-list-documents"', $detail);
        $this->assertStringContainsString('Tài liệu đã xuất · {{ count($exportHistory) }}', $detail);
        $this->assertStringContainsString("matchMedia('(min-width: 1024px)')", $detail);
        $this->assertStringContainsString('min-w-0 overflow-hidden rounded-3xl', $detail);
        $this->assertStringContainsString('group min-w-0 basis-full w-full lg:basis-auto lg:flex-1', $detail);
        $this->assertStringContainsString('id="price-list-export-dialog"', $detail);
        $this->assertStringContainsString("document.getElementById('price-list-export-dialog').showModal()", $detail);
        $this->assertStringContainsString('m-auto w-[calc(100%-24px)] max-w-[520px] rounded-[28px]', $detail);
        $this->assertStringNotContainsString('id="price-list-export-dialog" class="mb-0 mt-auto', $detail);
        $this->assertStringNotContainsString('absolute right-0 z-20 mt-2 w-[min(92vw,430px)]', $detail);
        $this->assertStringContainsString('id="price-list-secondary-actions-dialog"', $detail);
        $this->assertStringContainsString("document.getElementById('price-list-secondary-actions-dialog').showModal()", $detail);
        $this->assertStringContainsString('max-w-[440px] rounded-[28px]', $detail);
        $this->assertStringNotContainsString('absolute right-0 z-20 mt-2 w-80', $detail);
        $this->assertStringContainsString('break-all text-xs', $detail);
        $this->assertStringContainsString('id="price-list-product-search"', $detail);
        $this->assertStringContainsString('Tìm tên thuốc, mã thuốc, quy cách...', $detail);
        $this->assertStringContainsString('data-price-list-product', $detail);
        $this->assertStringContainsString('data-search=', $detail);
        $this->assertStringContainsString('data-search="{{ $productSearchText }}"', $detail);
        $this->assertStringNotContainsString('IlluminateSupportStr', $detail);
        $this->assertStringNotContainsString('Illuminate\\Support\\Str::', $detail);
        $this->assertStringContainsString("toLocaleLowerCase('vi')", $detail);
        $this->assertStringContainsString("normalize('NFD')", $detail);
        $this->assertStringContainsString("item.hidden=!matched", $detail);
        $this->assertStringContainsString("visible+' / '+items.length", $detail);
        $this->assertStringContainsString('Không tìm thấy sản phẩm phù hợp.', $detail);
        $this->assertStringContainsString('Phê duyệt & kích hoạt', $detail);
        $this->assertStringContainsString('Kích hoạt ngay', $detail);
        $this->assertStringContainsString('public function activateOwnDraft(int $approverUserId, int $priceListId)', $approval);
        $this->assertStringContainsString('activateOwnDraftPriceList(', $controller);
        $this->assertStringContainsString('$this->assertPending($list);', $approval);
        $this->assertStringContainsString('Phê duyệt & Kích hoạt', $approvalDetail);
        $this->assertStringContainsString('name="rejection_reason"', $approvalDetail);
        $this->assertStringContainsString('$selfApprovalBlocked', $approvalDetail);
        $this->assertStringNotContainsString('Admin::', $approvalQueue);
        $this->assertStringNotContainsString('Admin::', $approvalDetail);
        $this->assertStringNotContainsString('Admin::', $detail);
    }
}
