<div class="bg-white border border-gray-200 rounded-lg shadow-sm" @if($hasActiveDriveJobs) wire:poll.3s @endif>
    @if (session('success'))<div class="m-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    <div class="border-b border-gray-200 p-4">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div class="flex items-center gap-2"><h3 class="text-sm font-bold text-gray-900">Google Drive Backup</h3>@if($driveStatus['connected']??false)<span class="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">ĐÃ KẾT NỐI</span>@else<span class="rounded-full border border-gray-200 bg-gray-50 px-2 py-0.5 text-[10px] font-bold text-gray-500">CHƯA KẾT NỐI</span>@endif</div>@if($driveStatus['connected']??false)<p class="mt-1 text-xs text-gray-500">{{ $driveStatus['email']?:'Google Drive' }} · {{ $driveStatus['folder_name']??'Laravel-Backup' }}/database/YYYY/MM</p>@else<p class="mt-1 text-xs text-gray-500">Kết nối tại Cấu hình hệ thống → Quản lý ENV → Lưu trữ Cloud.</p>@endif</div>
        @if($driveStatus['connected']??false)<button type="button" wire:click="backupAndUpload" wire:loading.attr="disabled" wire:target="backupAndUpload" wire:confirm="Tạo backup database mới và đưa vào hàng đợi Google Drive?" class="inline-flex items-center justify-center rounded-lg bg-emerald-600 px-4 py-2 text-xs font-bold text-white hover:bg-emerald-700 disabled:opacity-50"><span wire:loading.remove wire:target="backupAndUpload">BACKUP & UPLOAD GOOGLE DRIVE</span><span wire:loading wire:target="backupAndUpload">ĐANG TẠO BACKUP...</span></button>@endif</div>
        @if($driveStatus['connected']??false)<div class="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><div class="rounded-lg border bg-gray-50 p-3"><div class="text-[10px] font-bold uppercase text-gray-400">Đang chờ</div><div class="mt-1 text-lg font-black text-gray-700">{{ $driveCounts['queued'] }}</div></div><div class="rounded-lg border border-blue-100 bg-blue-50 p-3"><div class="text-[10px] font-bold uppercase text-blue-500">Đang xử lý</div><div class="mt-1 text-lg font-black text-blue-700">{{ $driveCounts['processing'] }}</div></div><div class="rounded-lg border border-emerald-100 bg-emerald-50 p-3"><div class="text-[10px] font-bold uppercase text-emerald-500">Thành công</div><div class="mt-1 text-lg font-black text-emerald-700">{{ $driveCounts['uploaded'] }}</div></div><div class="rounded-lg border border-red-100 bg-red-50 p-3"><div class="text-[10px] font-bold uppercase text-red-500">Thất bại</div><div class="mt-1 text-lg font-black text-red-700">{{ $driveCounts['failed'] }}</div></div></div>@endif
        <p class="mt-3 text-xs text-amber-700">Backup local luôn độc lập. Cloud thất bại không xóa file local. Khi có job đang chạy, trang tự cập nhật trạng thái mỗi 3 giây.</p>
    </div>

    @if($driveStatus['connected']??false)
        <div class="border-b border-gray-200 p-4 bg-sky-50/40">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div><h3 class="text-sm font-bold text-gray-900">Backup đang có trên Google Drive</h3><p class="mt-1 text-xs text-gray-500">Hiển thị tối đa 100 file trong cây <code>database/YYYY/MM</code>. Có thể mở URL Drive hoặc tải về local rồi restore.</p></div>
                <button type="button" wire:click="$toggle('showDriveBackups')" class="rounded-lg border border-sky-200 bg-white px-3 py-2 text-xs font-bold text-sky-700">{{ $showDriveBackups ? 'ẨN DANH SÁCH' : 'HIỆN DANH SÁCH' }}</button>
            </div>
            @if($showDriveBackups)
                @if($remoteBackupsError)<div class="mt-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{{ $remoteBackupsError }}</div>@endif
                <div class="mt-4 max-h-[360px] overflow-y-auto rounded-xl border border-sky-100 bg-white divide-y divide-gray-100">
                    @forelse($remoteBackups as $remote)
                        <div class="p-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
                            <div class="min-w-0"><div class="text-sm font-semibold text-gray-900 break-all">{{ $remote['name'] }}</div><div class="mt-1 flex flex-wrap gap-2 text-xs text-gray-500"><span>{{ $remote['year'] }}/{{ $remote['month'] }}</span><span>{{ number_format(($remote['size'] ?? 0)/1024, 2) }} KB</span>@if(!empty($remote['modified_at']))<span>{{ \Carbon\Carbon::parse($remote['modified_at'])->diffForHumans() }}</span>@endif</div><a href="{{ $remote['url'] }}" target="_blank" rel="noopener noreferrer" class="mt-1 block text-xs text-sky-600 hover:underline break-all">{{ $remote['url'] }}</a></div>
                            <div class="flex shrink-0 gap-2"><a href="{{ $remote['url'] }}" target="_blank" rel="noopener noreferrer" class="rounded-lg border border-gray-300 bg-white px-3 py-2 text-xs font-semibold text-gray-700">Mở Drive</a><button wire:click="restoreFromGoogleDrive('{{ $remote['id'] }}','{{ $remote['name'] }}')" wire:confirm="CẢNH BÁO: Hệ thống sẽ tải '{{ $remote['name'] }}' từ Google Drive về local, tạo cơ chế backup an toàn theo luồng restore hiện tại rồi ghi đè database. Tiếp tục?" wire:loading.attr="disabled" class="rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">TẢI & RESTORE</button></div>
                        </div>
                    @empty<div class="p-6 text-center text-sm text-gray-400">Chưa tìm thấy backup nào trên Google Drive.</div>@endforelse
                </div>
            @endif
        </div>
    @endif

    <div class="grid gap-4 border-b border-gray-200 p-4 lg:grid-cols-2"><div class="rounded-lg border border-dashed border-gray-300 p-4"><h3 class="text-sm font-semibold text-gray-800">Upload backup từ máy tính</h3><p class="mt-1 text-xs text-gray-500">File .sql, tối đa 20 MB.</p><input type="file" wire:model="sqlFile" accept=".sql,application/sql,text/plain" class="mt-3 block w-full text-sm text-gray-600">@error('sqlFile')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror<button type="button" wire:click="uploadSql" wire:loading.attr="disabled" class="mt-3 rounded bg-indigo-600 px-4 py-2 text-xs font-semibold text-white">TẢI FILE LÊN</button></div><div class="rounded-lg border border-dashed border-gray-300 p-4"><h3 class="text-sm font-semibold text-gray-800">Nhập backup từ link Google Drive</h3><p class="mt-1 text-xs text-gray-500">Tương thích cũ: file chia sẻ “Bất kỳ ai có liên kết”.</p><input type="url" wire:model="googleDriveUrl" placeholder="https://drive.google.com/file/d/.../view" class="mt-3 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm">@error('googleDriveUrl')<p class="mt-2 text-sm text-red-600">{{ $message }}</p>@enderror<button type="button" wire:click="importFromGoogleDrive" class="mt-3 rounded bg-emerald-600 px-4 py-2 text-xs font-semibold text-white">TẢI TỪ GOOGLE DRIVE</button></div></div>
    <div class="p-4 border-b border-gray-200 bg-gray-50/50"><h3 class="font-semibold text-gray-700">Lịch sử Backup gần đây</h3><div class="mt-2 flex flex-wrap gap-2 text-xs text-gray-500">@foreach($backupDirectories as $directory)<code class="rounded bg-white px-2 py-1 ring-1 ring-gray-200">{{ $directory }}</code>@endforeach</div>@if($backupHistoryTruncated)<p class="mt-2 text-xs text-amber-700">Đang hiển thị {{ $backupHistoryLimit }} bản backup gần nhất. Các file cũ hơn vẫn được giữ theo chính sách storage hiện tại.</p>@else<p class="mt-2 text-xs text-gray-500">Hiển thị tối đa {{ $backupHistoryLimit }} bản backup gần nhất.</p>@endif</div>
    <div class="divide-y divide-gray-100 max-h-[600px] overflow-y-auto">@forelse($backups as $file) @php($gs=$file['google_drive']??[]) @php($state=$gs['status']??(!empty($gs['id'])?'uploaded':''))
        <div class="p-4 hover:bg-gray-50 group"><p class="text-sm font-medium text-gray-900 break-all">{{ $file['name'] }}</p><div class="mt-1 flex flex-wrap items-center gap-2 text-xs text-gray-500"><span>{{ number_format($file['size']/1024,2) }} KB</span><span>{{ \Carbon\Carbon::createFromTimestamp($file['time'])->diffForHumans() }}</span>
        @if($state==='queued')<span class="rounded-full bg-amber-50 px-2 py-0.5 font-semibold text-amber-700">⏳ Chờ upload Drive</span>@elseif($state==='processing')<span class="rounded-full bg-blue-50 px-2 py-0.5 font-semibold text-blue-700">↻ Đang upload...</span>@elseif($state==='uploaded')<span class="rounded-full bg-emerald-50 px-2 py-0.5 font-semibold text-emerald-700">Google Drive ✓</span>@if(!empty($gs['uploaded_at']))<span>{{ \Carbon\Carbon::parse($gs['uploaded_at'])->diffForHumans() }}</span>@endif @elseif($state==='failed')<span class="rounded-full bg-red-50 px-2 py-0.5 font-semibold text-red-700">✕ Upload thất bại</span>@elseif($driveStatus['connected']??false)<span class="rounded-full bg-gray-100 px-2 py-0.5 text-gray-500">Chưa upload Drive</span>@endif</div>
        @if($state==='failed'&&!empty($gs['error']))<div class="mt-2 rounded-lg border border-red-100 bg-red-50 px-3 py-2 text-xs text-red-700 break-words">{{ $gs['error'] }}</div>@endif
        <div class="mt-3 flex flex-wrap gap-2 opacity-100 transition-opacity lg:opacity-80 lg:group-hover:opacity-100"><a href="{{ route('admin.system.database.download',$file['name']) }}" class="px-2 py-1 bg-blue-50 text-blue-600 rounded text-xs font-medium">Download</a>@if($driveStatus['connected']??false&&$state!=='queued'&&$state!=='processing')<button wire:click="{{ $state==='failed'?'retryGoogleDriveUpload':'uploadToGoogleDrive' }}('{{ $file['name'] }}')" class="rounded bg-emerald-50 px-2 py-1 text-xs font-medium text-emerald-700">{{ $state==='failed'?'Thử lại':'Upload Drive' }}</button>@endif @if($file['size']<=\Modules\System\Jobs\SendDatabaseBackupEmail::MAX_ATTACHMENT_BYTES)<button wire:click="openEmailModal('{{ $file['name'] }}')" class="rounded bg-violet-50 px-2 py-1 text-xs text-violet-700">Gửi email</button>@endif @if($file['is_full'])<button wire:click="restoreBackup('{{ $file['name'] }}')" wire:confirm="CẢNH BÁO: restore database từ '{{ $file['name'] }}'?" class="rounded bg-red-600 px-2 py-1 text-[10px] font-bold text-white">RESTORE</button>@endif<button wire:click="deleteBackup('{{ $file['name'] }}')" wire:confirm="Xóa vĩnh viễn file local? Bản Drive không bị xóa." class="rounded bg-gray-100 px-2 py-1 text-xs text-red-600">Xóa local</button></div></div>
    @empty<div class="p-8 text-center text-sm text-gray-400">Chưa có bản backup nào.</div>@endforelse</div>
    @if($showEmailModal)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div class="w-full max-w-md rounded-xl bg-white p-6"><h2 class="text-lg font-bold">Gửi backup qua email</h2><p class="mt-1 break-all text-sm text-gray-500">{{ $emailBackupFile }}</p><input type="email" wire:model="backupEmail" class="mt-4 w-full rounded-lg border px-3 py-2">@error('backupEmail')<p class="text-sm text-red-600">{{ $message }}</p>@enderror<div class="mt-5 flex justify-end gap-2"><button wire:click="$set('showEmailModal',false)" class="rounded border px-4 py-2 text-sm">Hủy</button><button wire:click="sendBackupEmail" class="rounded bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Gửi file SQL</button></div></div></div>@endif
</div>
