@extends('ClientPortal::layouts.application')
@section('title','CSKD bệnh viện')
@section('app-dashboard-route', route('client.pharma.dashboard'))
@section('hide-application-header', true)
@section('hide-mobile-navigation', true)
@section('content')
<div class="mx-auto w-full max-w-4xl space-y-4 px-1 pb-24 sm:px-3 lg:px-4"><div class="flex min-h-16 items-center gap-3 border-b border-slate-200 bg-white pb-4"><a href="{{ route('client.pharma.bid-awards.allocation.hospital',[$scope,$hospital->id]) }}" aria-label="Quay lại phân bổ bệnh viện" class="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-slate-200 bg-white text-lg font-black text-slate-700 shadow-sm">←</a><div class="min-w-0"><h1 class="truncate text-lg font-black text-slate-950">CSKD bệnh viện</h1><p class="truncate text-xs text-slate-500">{{ $hospital->name }} · {{ $award->bidding_notice_code }}</p></div></div><section class="rounded-[28px] bg-slate-950 p-5 text-white"><p class="text-[11px] font-black uppercase tracking-[.18em] text-slate-300">Hospital Commercial Policy</p><h1 class="mt-1 text-xl font-black">{{ $hospital->name }}</h1><p class="mt-2 text-sm text-slate-300">Chỉ sản phẩm đã phân bổ mới được thiết lập CSKD.</p></section>
@if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('client.pharma.bid-awards.allocation.hospital.policy.store',[$scope,$hospital->id]) }}" class="space-y-3">@csrf
<div class="relative"><input type="search" data-hospital-policy-search data-pwa-local-filter data-pwa-local-filter-items="[data-hospital-policy-product]" data-pwa-local-filter-clear="[data-hospital-policy-clear]" data-pwa-local-filter-empty="[data-hospital-policy-empty]" placeholder="Tìm sản phẩm..." autocomplete="off" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 pr-11 text-sm"><button type="button" data-hospital-policy-clear class="absolute right-1 top-1 hidden h-9 w-9 rounded-lg text-slate-400" aria-label="Xóa tìm sản phẩm">×</button></div><p data-hospital-policy-empty class="hidden rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Không có sản phẩm phù hợp.</p>
@foreach($products as $product)@php($row=$allocations->get($product->id))@php($basePolicy=$productPolicies->get($product->id))<article data-hospital-policy-product data-search="{{ str($product->medicine_name.' '.$product->active_ingredient.' '.$product->concentration)->lower() }}" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm {{ $row ? '' : 'opacity-55' }}"><h2 class="font-black">{{ $product->medicine_name }}</h2>@if($row)<div class="mt-3 grid grid-cols-2 gap-2"><div class="rounded-xl bg-slate-50 p-3"><span class="block text-xs text-slate-500">Đã phân bổ</span><b class="mt-1 block">{{ number_format((float)$row->allocated_quantity,0,',','.') }}</b></div><div class="rounded-xl bg-slate-50 p-3"><span class="block text-xs text-slate-500">CSKD gốc</span><b class="mt-1 block">{{ $basePolicy ? rtrim(rtrim(number_format((float)$basePolicy->commission_percentage,4,'.',''), '0'), '.') . '%' : 'Chưa thiết lập' }}</b></div></div><label class="mt-3 block text-xs font-bold text-slate-600">CSKD riêng bệnh viện (%)<input inputmode="decimal" name="percentages[{{ $product->id }}]" value="{{ old('percentages.'.$product->id,$row->commercial_policy_percentage !== null ? rtrim(rtrim(number_format((float)$row->commercial_policy_percentage,4,'.',''),'0'),'.') : '') }}" placeholder="{{ $basePolicy ? 'Để trống = dùng CSKD gốc' : '0 - 100' }}" class="mt-1.5 h-12 w-full rounded-xl border px-3 text-base"><span class="mt-1.5 block font-normal text-slate-400">Để trống để dùng chính sách gốc.</span></label>@else<p class="mt-2 text-xs font-bold text-slate-400">Chưa phân bổ · CSKD bị khóa</p>@endif</article>@endforeach
<div class="sticky bottom-3 z-20 rounded-2xl bg-white/95 p-2 shadow-xl ring-1 ring-slate-200 backdrop-blur"><button class="min-h-12 w-full rounded-2xl bg-slate-950 px-5 text-sm font-black text-white sm:w-auto sm:float-right">Lưu CSKD bệnh viện</button><div class="clear-both"></div></div></form></div>

@endsection