@extends('ClientPortal::layouts.application')
@section('title','Phân bổ cho bệnh viện')
@section('app-dashboard-route', route('client.pharma.dashboard'))
@section('hide-application-header', true)
@section('hide-mobile-navigation', true)
@section('content')
<div class="mx-auto w-full max-w-4xl space-y-4 px-1 pb-24 sm:px-3 lg:px-4"><header class="flex min-h-16 items-center gap-3 border-b border-slate-200 bg-white pb-4"><a href="{{ route('client.pharma.bid-awards.allocation',$scope) }}" aria-label="Quay lại danh sách bệnh viện" class="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-slate-200 bg-white text-lg font-black text-slate-700 shadow-sm">←</a><div class="min-w-0"><h1 class="truncate text-lg font-black text-slate-950">Nhận phân bổ số lượng</h1><p class="truncate text-xs text-slate-500">{{ $hospital->name }}</p></div></header>
<section class="rounded-[28px] bg-slate-950 p-5 text-white"><p class="text-[11px] font-black uppercase tracking-[.18em] text-slate-300">Hospital Allocation</p><h1 class="mt-1 text-xl font-black">{{ $hospital->name }}</h1><p class="mt-2 text-sm text-slate-300">Cập nhật số lượng theo từng sản phẩm KQLCNT.</p></section>
@if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('client.pharma.bid-awards.allocation.hospital.store',[$scope,$hospital->id]) }}" class="space-y-3">@csrf
<div class="relative"><input type="search" data-allocation-product-search data-pwa-local-filter data-pwa-local-filter-items="[data-allocation-product-card]" data-pwa-local-filter-clear="[data-allocation-product-clear]" data-pwa-local-filter-empty="[data-allocation-product-empty]" placeholder="Tìm sản phẩm..." autocomplete="off" class="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 pr-11 text-sm"><button type="button" data-allocation-product-clear class="absolute right-1 top-1 hidden h-9 w-9 rounded-lg text-slate-400" aria-label="Xóa tìm sản phẩm">×</button></div><p data-allocation-product-empty class="hidden rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Không có sản phẩm phù hợp.</p>
@foreach($products as $product)@php($row=$allocations->get($product->id))<article data-allocation-product-card data-name="{{ str($product->medicine_name.' '.$product->active_ingredient.' '.$product->concentration)->lower() }}" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div><h2 class="font-black">{{ $product->medicine_name }}</h2><p class="text-xs text-slate-500">{{ $product->active_ingredient }} {{ $product->concentration }}</p></div><div class="mt-3 grid grid-cols-3 gap-2 text-xs"><div class="rounded-xl bg-slate-50 p-2"><span class="block text-slate-500">SL trúng thầu</span><b class="mt-1 block">{{ number_format((float)$product->quantity,0,',','.') }}</b></div><div class="rounded-xl bg-slate-50 p-2"><span class="block text-slate-500">Đã phân bổ</span><b class="mt-1 block">{{ number_format((float)$product->pwa_allocated_quantity,0,',','.') }}</b></div><div class="rounded-xl bg-amber-50 p-2"><span class="block text-slate-500">Còn lại</span><b class="mt-1 block">{{ number_format((float)$product->pwa_remaining_quantity,0,',','.') }}</b></div></div>@if($row)<p class="mt-2 text-xs font-bold text-indigo-700">Bệnh viện hiện có: {{ number_format((float)$row->allocated_quantity,0,',','.') }}</p>@endif<label class="mt-3 block text-xs font-bold text-slate-600">Số lượng bệnh viện này<input inputmode="decimal" name="quantities[{{ $product->id }}]" value="{{ old('quantities.'.$product->id,$row ? number_format((float)$row->allocated_quantity,0,',','.') : '') }}" placeholder="Nhập số lượng" data-quantity-input class="mt-1.5 h-12 w-full rounded-xl border border-slate-200 px-3 text-base"></label></article>@endforeach
<div class="sticky bottom-3 z-20 flex gap-2 rounded-2xl bg-white/95 p-2 shadow-xl ring-1 ring-slate-200 backdrop-blur"><button class="min-h-12 flex-1 rounded-2xl bg-slate-950 px-5 text-sm font-black text-white shadow-lg">Lưu phân bổ</button>@if($canManageCommercialPolicy && $allocations->isNotEmpty())<a href="{{ route('client.pharma.bid-awards.allocation.hospital.policy',[$scope,$hospital->id]) }}" class="inline-flex min-h-12 items-center rounded-2xl bg-emerald-600 px-4 text-sm font-black text-white shadow-lg">Thiết lập CSKD</a>@endif</div></form></div>
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-quantity-input]').forEach(input=>{const format=()=>{const digits=input.value.replace(/\D/g,'');input.value=digits?Number(digits).toLocaleString('vi-VN'):''};input.addEventListener('input',format);format()})});</script>
@endsection