@extends('ClientPortal::layouts.application')
@section('title','Phân bổ số lượng')
@section('content')
@php($savedScope=$setup['scope'])
<div class="mx-auto w-full max-w-5xl space-y-4 px-3 py-4 sm:px-5 lg:px-6">
<a href="{{ route('client.pharma.bid-awards.show',$scope) }}" class="inline-flex min-h-11 items-center text-sm font-bold text-slate-600">← Quay lại kết quả trúng thầu</a>
<section class="rounded-[28px] bg-slate-950 p-5 text-white sm:p-6"><p class="text-[11px] font-black uppercase tracking-[.18em] text-slate-300">Allocation</p><h1 class="mt-1 text-2xl font-black">Phân bổ số lượng</h1><p class="mt-2 text-sm text-slate-300">{{ $award->investor_name }} · {{ $award->bidding_notice_code ?: $award->decision_number }}</p></section>
@if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif

<details class="rounded-[24px] border border-indigo-200 bg-white shadow-sm" @if(!$savedScope) open @endif>
<summary class="flex min-h-16 cursor-pointer list-none items-start justify-between gap-3 p-4 sm:p-5"><div><p class="text-[11px] font-black uppercase tracking-[.14em] text-indigo-600">Thiết lập chung</p><h2 class="mt-1 text-lg font-black">Phạm vi & hiệu lực phân bổ</h2>@if($savedScope)<p class="mt-1 text-xs text-slate-500">{{ implode(', ',$setup['provinces']) }} · {{ count($setup['facility_ids']) }} bệnh viện · {{ optional($savedScope->effective_from)->format('d/m/Y') }} → {{ optional($savedScope->effective_until)->format('d/m/Y') }}</p>@endif</div>@if($savedScope)<span class="shrink-0 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">Đã hoàn tất</span>@endif</summary>
<form method="POST" action="{{ route('client.pharma.bid-awards.allocation.setup',$scope) }}" class="space-y-2 border-t border-indigo-100 p-4 sm:p-5" id="distribution-setup-form">@csrf
<details class="rounded-2xl border border-slate-200" @if(!$savedScope) open @endif><summary class="flex min-h-14 cursor-pointer list-none items-center justify-between p-4"><span><b>① Phạm vi & hiệu lực</b><small class="mt-0.5 block text-slate-500">{{ count($draftProvinces) }} Tỉnh/Thành</small></span><span>⌄</span></summary><div class="border-t p-4"><input type="search" data-province-search placeholder="Tìm Tỉnh/Thành..." class="h-11 w-full rounded-xl border px-3"><div class="mt-2 max-h-48 overflow-y-auto">@foreach($provinceOptions as $province)<label data-province-card data-name="{{ str($province)->lower() }}" class="flex min-h-11 items-center gap-2"><input type="checkbox" name="province_names[]" value="{{ $province }}" @checked(in_array($province,$draftProvinces,true)) class="h-5 w-5"><span>{{ $province }}</span></label>@endforeach</div><div class="mt-3 grid grid-cols-2 gap-2"><label class="text-xs font-bold">Từ ngày<input type="date" name="effective_from" value="{{ old('effective_from',$savedScope?->effective_from?->format('Y-m-d') ?: $award->decision_date?->format('Y-m-d')) }}" class="mt-1 h-11 w-full rounded-xl border px-2"></label><label class="text-xs font-bold">Đến ngày<input type="date" name="effective_until" value="{{ old('effective_until',$savedScope?->effective_until?->format('Y-m-d')) }}" class="mt-1 h-11 w-full rounded-xl border px-2"></label></div></div></details>
<details class="rounded-2xl border border-slate-200"><summary class="flex min-h-14 cursor-pointer list-none items-center justify-between p-4"><span><b>② Chọn cơ sở KCB</b><small class="mt-0.5 block text-slate-500">{{ count($draftFacilityIds) }} bệnh viện đang chọn</small></span><span>⌄</span></summary><div class="border-t p-4"><button type="submit" formmethod="GET" formaction="{{ route('client.pharma.bid-awards.allocation',$scope) }}" class="min-h-10 rounded-xl border px-3 text-xs font-bold">Cập nhật theo Tỉnh/Thành</button><input type="search" data-facility-search placeholder="Tìm bệnh viện..." class="mt-3 h-11 w-full rounded-xl border px-3"><div class="mt-2 max-h-64 overflow-y-auto">@foreach($facilityOptions as $facility)<label data-facility-card data-name="{{ str($facility->facility_name.' '.$facility->external_id)->lower() }}" class="flex min-h-12 items-start gap-2 py-2"><input type="checkbox" name="facility_ids[]" value="{{ $facility->id }}" @checked(in_array((int)$facility->id,$draftFacilityIds,true)) class="mt-0.5 h-5 w-5"><span><b class="block text-sm">{{ $facility->facility_name }}</b><small class="text-slate-500">{{ $facility->external_id }} · {{ $facility->province_name }}</small></span></label>@endforeach</div></div></details>
<details class="rounded-2xl border border-slate-200"><summary class="flex min-h-14 cursor-pointer list-none items-center justify-between p-4"><span><b>③ Kiểm tra & lưu</b><small class="mt-0.5 block text-slate-500" data-review-count>{{ count($draftFacilityIds) }} bệnh viện</small></span><span>⌄</span></summary><div class="border-t p-4"><p class="mb-2 text-xs text-slate-500">Các bệnh viện đã chọn được checkbox sẵn. Bỏ chọn tại đây để loại trước khi lưu.</p><div class="max-h-64 space-y-2 overflow-y-auto" data-review-list>@foreach($facilityOptions->whereIn('id',$draftFacilityIds) as $facility)<label class="flex min-h-12 items-start gap-2 rounded-xl bg-slate-50 p-2.5"><input type="checkbox" checked data-review-checkbox value="{{ $facility->id }}" class="mt-0.5 h-5 w-5"><span><b class="block text-sm">{{ $facility->facility_name }}</b><small class="text-slate-500">{{ $facility->external_id }}</small></span></label>@endforeach</div><button class="mt-4 min-h-12 w-full rounded-2xl bg-indigo-600 px-5 text-sm font-black text-white">Lưu thiết lập phân bổ</button></div></details>
</form></details>

@if($savedScope)
<section class="rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm sm:p-5">
<div class="flex items-center justify-between gap-3"><div><p class="text-[11px] font-black uppercase tracking-[.14em] text-slate-400">Tổng quan phân bổ</p><h2 class="mt-1 text-lg font-black">{{ $productAllocationCards->count() }} sản phẩm trúng thầu</h2></div></div>
<div class="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><div class="relative"><input type="search" data-product-allocation-search placeholder="Tìm sản phẩm..." class="h-11 w-full rounded-xl border border-slate-200 px-3 pr-10 text-sm"><button type="button" data-product-allocation-clear class="absolute right-1 top-1 hidden h-9 w-9 rounded-lg text-slate-400" aria-label="Xóa tìm kiếm">×</button></div><button type="button" data-incomplete-toggle aria-pressed="false" class="min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-xs font-black text-slate-700">Chưa phân bổ hết</button></div>
<p data-product-allocation-empty class="mt-3 hidden rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Không có sản phẩm phù hợp bộ lọc.</p>
<div class="mt-3 grid gap-3 md:grid-cols-2" data-product-allocation-list>@foreach($productAllocationCards as $product)<article data-product-allocation-card data-name="{{ str($product->medicine_name.' '.$product->active_ingredient.' '.$product->concentration)->lower() }}" data-incomplete="{{ $product->pwa_fully_allocated ? '0' : '1' }}" class="rounded-2xl border {{ $product->pwa_fully_allocated ? 'border-emerald-200 bg-emerald-50/40' : 'border-rose-200 bg-rose-50/30' }} p-4"><div class="flex items-start justify-between gap-2"><h3 class="font-black">{{ $product->medicine_name }}</h3>@if($product->pwa_fully_allocated)<span class="shrink-0 rounded-full bg-emerald-100 px-2 py-1 text-[11px] font-bold text-emerald-700">Đã phân bổ hết</span>@else<span class="shrink-0 rounded-full bg-rose-100 px-2 py-1 text-[11px] font-bold text-rose-700">Phân bổ chưa hết</span>@endif</div><div class="mt-3 grid grid-cols-3 gap-2 text-xs"><div class="rounded-xl bg-slate-50 p-2"><span class="block text-slate-500">SL trúng thầu</span><b class="mt-1 block">{{ number_format((float)$product->quantity,0,',','.') }}</b></div><div class="rounded-xl bg-slate-50 p-2"><span class="block text-slate-500">Đã phân bổ</span><b class="mt-1 block">{{ number_format((float)$product->pwa_allocated_quantity,0,',','.') }}</b></div><div class="rounded-xl {{ $product->pwa_fully_allocated ? 'bg-emerald-100' : 'bg-amber-50' }} p-2"><span class="block text-slate-500">Còn lại</span><b class="mt-1 block">{{ number_format((float)$product->pwa_remaining_quantity,0,',','.') }}</b></div></div></article>@endforeach</div>
</section>

<details class="rounded-[24px] border border-slate-200 bg-white shadow-sm"><summary class="flex min-h-16 cursor-pointer list-none items-center justify-between gap-3 p-4 sm:p-5"><div><p class="text-[11px] font-black uppercase tracking-[.14em] text-slate-400">Bệnh viện nhận phân bổ</p><h2 class="mt-1 text-lg font-black">{{ $hospitalCards->count() }} bệnh viện</h2></div><span>⌄</span></summary><div class="border-t border-slate-100 p-4 sm:p-5"><input type="search" data-hospital-search placeholder="Tìm bệnh viện..." class="h-11 w-full rounded-xl border px-3">
<div class="mt-3 grid gap-3 md:grid-cols-2">@foreach($hospitalCards as $hospital)<article data-hospital-card data-name="{{ str($hospital->name)->lower() }}" class="rounded-2xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><h3 class="truncate font-black">{{ $hospital->name }}</h3><p class="mt-1 text-xs text-slate-500">{{ $hospital->pwa_allocated_products }}/{{ $hospital->pwa_product_count }} sản phẩm đã phân bổ</p></div>@if($hospital->pwa_allocated_products===0)<span class="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-500">Chưa phân bổ</span>@endif</div><div class="mt-3 flex flex-wrap gap-2"><a href="{{ route('client.pharma.bid-awards.allocation.hospital',[$scope,$hospital->id]) }}" class="inline-flex min-h-11 flex-1 items-center justify-center rounded-xl bg-slate-950 px-3 text-xs font-black text-white active:scale-[.985]">Nhận phân bổ số lượng</a>@if($hospital->pwa_allocated_products>0)<a href="{{ route('client.pharma.bid-awards.allocation.hospital.policy',[$scope,$hospital->id]) }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-emerald-200 bg-emerald-50 px-3 text-xs font-black text-emerald-700">CSKD {{ $hospital->pwa_policy_products }}/{{ $hospital->pwa_allocated_products }}</a>@endif</div></article>@endforeach</div></div></details>
@endif
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const filter=(i,s)=>document.querySelector(i)?.addEventListener('input',e=>{const v=e.target.value.toLocaleLowerCase('vi');document.querySelectorAll(s).forEach(x=>x.classList.toggle('hidden',!x.dataset.name.includes(v)))});filter('[data-province-search]','[data-province-card]');filter('[data-facility-search]','[data-facility-card]');filter('[data-hospital-search]','[data-hospital-card]');const ps=document.querySelector('[data-product-allocation-search]'),pc=document.querySelector('[data-product-allocation-clear]'),pt=document.querySelector('[data-incomplete-toggle]'),pe=document.querySelector('[data-product-allocation-empty]');let incompleteOnly=false;const applyProducts=()=>{const q=(ps?.value||'').toLocaleLowerCase('vi');let visible=0;document.querySelectorAll('[data-product-allocation-card]').forEach(card=>{const show=card.dataset.name.includes(q)&&(!incompleteOnly||card.dataset.incomplete==='1');card.classList.toggle('hidden',!show);if(show)visible++});pe?.classList.toggle('hidden',visible!==0);pc?.classList.toggle('hidden',!ps?.value);pt?.setAttribute('aria-pressed',incompleteOnly?'true':'false');pt?.classList.toggle('bg-rose-50',incompleteOnly);pt?.classList.toggle('border-rose-200',incompleteOnly);pt?.classList.toggle('text-rose-700',incompleteOnly)};ps?.addEventListener('input',applyProducts);pc?.addEventListener('click',()=>{ps.value='';applyProducts();ps.focus()});pt?.addEventListener('click',()=>{incompleteOnly=!incompleteOnly;applyProducts()});const f=document.getElementById('distribution-setup-form'),r=document.querySelector('[data-review-list]'),n=document.querySelector('[data-review-count]');const sync=()=>{const a=[...f.querySelectorAll('input[name="facility_ids[]"]:checked')];r.innerHTML='';a.forEach(cb=>{const src=cb.closest('[data-facility-card]'),x=src.cloneNode(true);x.removeAttribute('data-facility-card');x.removeAttribute('data-name');const i=x.querySelector('input');i.removeAttribute('name');i.setAttribute('data-review-checkbox','');i.checked=true;x.className='flex min-h-12 items-start gap-2 rounded-xl bg-slate-50 p-2.5';r.append(x)});n.textContent=a.length+' bệnh viện'};f.querySelectorAll('input[name="facility_ids[]"]').forEach(x=>x.addEventListener('change',sync));r.addEventListener('change',e=>{if(!e.target.matches('[data-review-checkbox]'))return;const x=f.querySelector('input[name="facility_ids[]"][value="'+e.target.value+'"]');if(x){x.checked=e.target.checked;sync()}})});</script>
@endsection
