@extends('ClientPortal::layouts.application')
@section('title','Phân bổ cho bệnh viện')
@section('content')
<div class="mx-auto w-full max-w-4xl space-y-4 px-3 py-4 sm:px-5"><a href="{{ route('client.pharma.bid-awards.allocation',$scope) }}" class="inline-flex min-h-11 items-center text-sm font-bold text-slate-600">← Danh sách bệnh viện</a>
<section class="rounded-[28px] bg-slate-950 p-5 text-white"><p class="text-[11px] font-black uppercase tracking-[.18em] text-slate-300">Hospital Allocation</p><h1 class="mt-1 text-xl font-black">{{ $hospital->name }}</h1><p class="mt-2 text-sm text-slate-300">Cập nhật số lượng theo từng sản phẩm KQLCNT.</p></section>
@if(session('success'))<div class="rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('client.pharma.bid-awards.allocation.hospital.store',[$scope,$hospital->id]) }}" class="space-y-3">@csrf
@foreach($products as $product)@php($row=$allocations->get($product->id))<article class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex items-start justify-between gap-3"><div><h2 class="font-black">{{ $product->medicine_name }}</h2><p class="text-xs text-slate-500">{{ $product->active_ingredient }} {{ $product->concentration }}</p></div><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">SL trúng {{ number_format((float)$product->quantity,0,',','.') }}</span></div><label class="mt-3 block text-xs font-bold text-slate-600">Số lượng bệnh viện này<input inputmode="decimal" name="quantities[{{ $product->id }}]" value="{{ old('quantities.'.$product->id,$row ? number_format((float)$row->allocated_quantity,0,',','.') : '') }}" placeholder="Nhập số lượng" data-quantity-input class="mt-1.5 h-12 w-full rounded-xl border border-slate-200 px-3 text-base"></label></article>@endforeach
<div class="sticky bottom-3 flex gap-2"><button class="min-h-12 flex-1 rounded-2xl bg-slate-950 px-5 text-sm font-black text-white shadow-lg">Lưu phân bổ</button>@if($canManageCommercialPolicy && $allocations->isNotEmpty())<a href="{{ route('client.pharma.bid-awards.allocation.hospital.policy',[$scope,$hospital->id]) }}" class="inline-flex min-h-12 items-center rounded-2xl bg-emerald-600 px-4 text-sm font-black text-white shadow-lg">Thiết lập CSKD</a>@endif</div></form></div>
<script>document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-quantity-input]').forEach(input=>{const format=()=>{const digits=input.value.replace(/\D/g,'');input.value=digits?Number(digits).toLocaleString('vi-VN'):''};input.addEventListener('input',format);format()})});</script>
@endsection