@extends('ClientPortal::layouts.application')
@section('title','Chi tiết phiếu nhập')
@section('app-name', $applicationPresentation['name'] ?? $application['name'])
@section('app-subtitle','Workspace Pharma dành cho User')
@section('app-dashboard-route', route('client.pharma.dashboard'))
@section('content')
@php $money=fn($v)=>number_format((float)$v,0,',','.').' đ'; $labels=['draft'=>'Nháp','posted'=>'Đã ghi sổ','cancelled'=>'Đã hủy']; @endphp
<div class="min-w-0 space-y-4 pb-24 xl:pb-8">
<section class="rounded-[1.75rem] bg-slate-950 px-5 py-5 text-white shadow-sm sm:px-7"><a href="{{ route('client.pharma.inventory.receipts') }}" class="text-sm font-bold text-slate-300">← Phiếu nhập kho</a><div class="mt-4 flex flex-wrap items-center justify-between gap-3"><div><p class="text-[11px] font-black uppercase tracking-[0.16em] text-slate-400">Receipt detail · Read only</p><h1 class="mt-1 text-2xl font-black">{{ $receipt->number }}</h1></div><span class="rounded-full bg-white/10 px-3 py-1.5 text-xs font-black">{{ $labels[$receipt->status] ?? $receipt->status }}</span></div></section>
<section class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">@foreach([['Ngày nhập',$receipt->receipt_date?->format('d/m/Y')],['Nhà cung cấp',$receipt->supplier_name],['Số hóa đơn',$receipt->invoice_number ?: '—'],['Ngày hóa đơn',$receipt->invoice_date?->format('d/m/Y') ?: '—']] as [$label,$value])<div class="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><p class="mt-2 font-black text-slate-950">{{ $value }}</p></div>@endforeach</section>
<section class="space-y-3 xl:hidden">@foreach($receipt->items as $item)<article class="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="font-black">{{ $item->medicine?->name }}</h2><p class="mt-1 text-xs text-slate-500">Lô {{ $item->batch_number }} · HSD {{ $item->expiry_date?->format('d/m/Y') }}</p><div class="mt-3 flex justify-between text-sm"><span>SL <b>{{ number_format((float)$item->quantity,3,',','.') }}</b></span><span class="font-black">{{ $money($item->unit_price_ex_vat) }}</span></div></article>@endforeach</section>
<section class="hidden overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm xl:block"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs font-black uppercase text-slate-500"><tr><th class="px-4 py-3">Thuốc</th><th class="px-4 py-3">Số lô</th><th class="px-4 py-3">Hạn dùng</th><th class="px-4 py-3 text-right">Số lượng</th><th class="px-4 py-3 text-right">Giá nhập</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($receipt->items as $item)<tr><td class="px-4 py-3 font-bold">{{ $item->medicine?->name }}</td><td class="px-4 py-3">{{ $item->batch_number }}</td><td class="px-4 py-3">{{ $item->expiry_date?->format('d/m/Y') }}</td><td class="px-4 py-3 text-right">{{ number_format((float)$item->quantity,3,',','.') }}</td><td class="px-4 py-3 text-right font-bold">{{ $money($item->unit_price_ex_vat) }}</td></tr>@endforeach</tbody></table></section>
@if($receipt->notes)<section class="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-black uppercase text-slate-500">Ghi chú</p><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $receipt->notes }}</p></section>@endif
</div>
@endsection
