@extends('ClientPortal::layouts.application')
@section('title', isset($receipt) ? 'Sửa phiếu nhập kho' : 'Thêm phiếu nhập kho')
@section('app-name', $applicationPresentation['name'] ?? $application['name'])
@section('app-subtitle','Workspace Pharma dành cho User')
@section('app-dashboard-route', route('client.pharma.dashboard'))
@section('hide-application-header', true)
@section('hide-mobile-navigation', true)
@section('content')
@php
$editing = isset($receipt);
$selectedSupplier = $editing ? $suppliers->firstWhere('name', $receipt->supplier_name) : null;
$persistedItems = $editing ? $receipt->items->map(fn($item) => [
    'medicine_id'=>(int)$item->medicine_id,'batch_number'=>$item->batch_number,
    'expiry_date'=>$item->expiry_date?->format('Y-m-d'),'quantity'=>(float)$item->quantity,
    'unit_price_ex_vat'=>(float)$item->unit_price_ex_vat,'invoice_unit_price_ex_vat'=>$item->invoice_unit_price_ex_vat !== null ? (float)$item->invoice_unit_price_ex_vat : null,
])->values()->all() : [];
$initialItems = collect(old('items', $persistedItems));
$receiptVatRate = old('vat_rate', $editing ? (float) ($receipt->items->first()?->vat_rate ?? 5) : 5);

@endphp
<div class="min-w-0 space-y-4 pb-8">
<section class="rounded-[1.75rem] bg-slate-950 px-5 py-5 text-white shadow-sm sm:px-7">
<a href="{{ route('client.pharma.inventory.receipts') }}" class="inline-flex min-h-10 items-center text-sm font-bold text-slate-300">← Phiếu nhập kho</a>
<p class="mt-2 text-[11px] font-black uppercase tracking-[0.16em] text-slate-400">Receipt · Draft authoring</p>
<h1 class="mt-1 text-2xl font-black">{{ $editing ? 'Sửa phiếu nhập' : 'Thêm phiếu nhập' }}</h1>
<p class="mt-1.5 text-sm text-slate-300">Lưu nháp không làm thay đổi tồn kho. Chỉ phiếu được ghi sổ mới cộng số lượng vào kho.</p>
</section>
@if($errors->any())<section class="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{{ $errors->first() }}</section>@endif
<form method="POST" action="{{ $editing ? route('client.pharma.inventory.receipts.update',$receipt) : route('client.pharma.inventory.receipts.store') }}" class="space-y-4" id="receipt-draft-form">@csrf @if($editing) @method('PUT') @endif
<section class="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm">
<div class="mb-3"><h2 class="font-black text-slate-950">Thông tin nhập kho</h2><p class="mt-1 text-xs text-slate-500">Thông tin tiếp nhận hàng và nhà cung cấp.</p></div>
<div class="grid gap-3 md:grid-cols-2">
<x-pwa-date name="receipt_date" label="Ngày nhập *" :value="old('receipt_date', $editing ? $receipt->receipt_date?->format('Y-m-d') : now()->toDateString())" required />
<label class="text-sm font-bold text-slate-700">Nhà cung cấp *<div class="relative mt-1.5" data-receipt-combobox><input type="search" autocomplete="off" data-combobox-search value="{{ $suppliers->firstWhere('id', (int) old('supplier_id', $selectedSupplier?->id))?->name ?? '' }}" placeholder="Tìm tên nhà cung cấp / MST..." class="h-12 w-full rounded-2xl border border-slate-300 bg-white px-4 pr-10 text-sm font-semibold outline-none focus:border-slate-950 focus:ring-2 focus:ring-slate-100"><button type="button" data-combobox-clear aria-label="Xóa nhà cung cấp" class="absolute right-2 top-1.5 hidden h-9 w-9 items-center justify-center rounded-xl text-lg font-black text-slate-400 hover:bg-slate-100">×</button><input type="hidden" name="supplier_id" data-combobox-value value="{{ old('supplier_id', $selectedSupplier?->id) }}"><div data-combobox-results class="absolute left-0 right-0 top-[calc(100%+6px)] z-[90] hidden max-h-72 overflow-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">@foreach($suppliers as $supplier)<button type="button" data-combobox-option data-value="{{ $supplier->id }}" data-label="{{ $supplier->name }}" data-search="{{ mb_strtolower($supplier->name.' '.($supplier->tax_code ?? '')) }}" class="block w-full rounded-xl px-3 py-3 text-left text-sm hover:bg-slate-100"><strong class="block font-bold text-slate-900">{{ $supplier->name }}</strong>@if($supplier->tax_code)<small class="mt-0.5 block text-xs text-slate-500">MST {{ $supplier->tax_code }}</small>@endif</button>@endforeach</div></div></label>
</div>
<div class="my-4 border-t border-slate-100"></div>
<div class="flex items-center justify-between gap-3">
<div><h2 class="font-black text-slate-950">Thông tin hóa đơn</h2><p class="mt-1 text-xs text-slate-500">Dữ liệu chứng từ để đối chiếu, không thay thế Giá nhập / Giá vốn.</p></div>
<button type="button" id="toggle-receipt-invoice" aria-expanded="false" class="inline-flex min-h-10 shrink-0 items-center rounded-xl border border-slate-300 bg-white px-3 text-xs font-black text-slate-700">Hiện</button>
</div>
<div id="receipt-invoice-fields" class="mt-3 hidden">
<div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
<label class="text-sm font-bold text-slate-700">Số hóa đơn<input name="invoice_number" value="{{ old('invoice_number', $editing ? $receipt->invoice_number : '') }}" maxlength="100" class="mt-1.5 h-12 w-full rounded-2xl border border-slate-300 px-3 font-normal"></label>
<label class="text-sm font-bold text-slate-700">Ký hiệu hóa đơn<input name="invoice_symbol" value="{{ old('invoice_symbol', $editing ? $receipt->invoice_symbol : '') }}" maxlength="100" placeholder="VD: 1C26TAA" class="mt-1.5 h-12 w-full rounded-2xl border border-slate-300 px-3 font-normal"></label>
<x-pwa-date name="invoice_date" label="Ngày hóa đơn" :value="old('invoice_date', $editing ? ($receipt->invoice_date?->format('Y-m-d') ?? now()->toDateString()) : now()->toDateString())" />
<label class="text-sm font-bold text-slate-700">VAT %<input type="number" step="0.01" min="0" max="100" name="vat_rate" value="{{ $receiptVatRate }}" required class="mt-1.5 h-12 w-full rounded-2xl border border-slate-300 px-3 font-normal"></label>
</div>
<p class="mt-2 text-xs text-slate-500">Một phiếu nhập chỉ áp dụng một mức VAT cho toàn bộ hàng nhập.</p>
</div>
</section>
<section class="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm">
<div class="flex items-center justify-between gap-3"><div><h2 class="font-black text-slate-950">Hàng nhập</h2><p class="mt-1 text-xs text-slate-500">Thuốc + số lô + hạn dùng không được trùng trong cùng phiếu.</p></div><button type="button" id="add-receipt-item" class="min-h-10 rounded-xl border border-slate-300 px-3 text-sm font-black">+ Thêm dòng</button></div>
<div id="receipt-items" class="mt-4 space-y-3"></div>
</section>
<section class="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><label class="text-sm font-bold text-slate-700">Ghi chú<textarea name="notes" rows="3" maxlength="2000" class="mt-1.5 w-full rounded-2xl border border-slate-300 p-3 font-normal">{{ old('notes', $editing ? $receipt->notes : '') }}</textarea></label></section>
<div class="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><a href="{{ route('client.pharma.inventory.receipts') }}" class="inline-flex min-h-12 items-center justify-center rounded-2xl border border-slate-300 bg-white px-5 text-sm font-black">Hủy</a><button class="inline-flex min-h-12 items-center justify-center rounded-2xl bg-slate-950 px-5 text-sm font-black text-white">{{ $editing ? 'Lưu thay đổi' : 'Lưu nháp' }}</button></div>
</form>
<template id="receipt-item-template"><article class="receipt-item rounded-2xl border border-slate-200 bg-slate-50 p-3">
<div class="receipt-item-summary flex items-center justify-between gap-3">
<div class="min-w-0"><p class="receipt-item-summary-name truncate text-sm font-black text-slate-950">Sản phẩm mới</p><p class="receipt-item-summary-meta mt-0.5 truncate text-xs text-slate-500">Chưa nhập thông tin lô</p></div>
<button type="button" class="toggle-receipt-item inline-flex min-h-10 shrink-0 items-center rounded-xl border border-slate-300 bg-white px-3 text-xs font-black text-slate-700" aria-expanded="true">Ẩn</button>
</div>
<div class="receipt-item-editor mt-3 border-t border-slate-200 pt-3">
<div class="grid gap-3 md:grid-cols-2 xl:grid-cols-12">
<label class="text-xs font-bold text-slate-600 xl:col-span-3">Thuốc *<div class="relative mt-1" data-receipt-combobox><input type="search" autocomplete="off" data-combobox-search placeholder="Tìm tên thuốc / mã thuốc / hoạt chất..." class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3 pr-9 text-sm font-semibold outline-none focus:border-slate-950 focus:ring-2 focus:ring-slate-100"><button type="button" data-combobox-clear aria-label="Xóa thuốc" class="absolute right-1.5 top-1 hidden h-9 w-9 items-center justify-center rounded-lg text-lg font-black text-slate-400 hover:bg-slate-100">×</button><input type="hidden" data-field="medicine_id" data-combobox-value><div data-combobox-results class="absolute left-0 right-0 top-[calc(100%+6px)] z-[90] hidden max-h-72 min-w-[320px] overflow-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-2xl">@foreach($medicines as $medicine)<button type="button" data-combobox-option data-value="{{ $medicine->id }}" data-label="{{ $medicine->name }}" data-reference-cost="{{ $canViewCosts && $referenceCosts->has($medicine->id) ? number_format((float) $referenceCosts->get($medicine->id), 0, ',', '.') : '' }}" data-search="{{ mb_strtolower(($medicine->medicine_code ?? '').' '.$medicine->name.' '.($medicine->active_ingredients ?? '')) }}" class="block w-full rounded-xl px-3 py-3 text-left text-sm hover:bg-slate-100"><strong class="block font-bold text-slate-900">{{ $medicine->name }}</strong><small class="mt-0.5 block text-xs text-slate-500">{{ $medicine->medicine_code }}@if($medicine->unit) · {{ $medicine->unit }}@endif</small></button>@endforeach</div></div></label>
<label class="text-xs font-bold text-slate-600 xl:col-span-2">Số lô *<input data-field="batch_number" required maxlength="100" class="mt-1 h-11 w-full rounded-xl border border-slate-300 bg-white px-2 font-normal"></label>
<x-pwa-date name="" label="Hạn dùng *" data-field="expiry_date" required wrapper-class="xl:col-span-2" />
<label class="text-xs font-bold text-slate-600">Số lượng *<input type="text" inputmode="decimal" data-number-display data-scale="3" required class="mt-1 h-11 w-full rounded-xl border border-slate-300 bg-white px-2 text-right font-normal tabular-nums" placeholder="0"><input type="hidden" data-field="quantity" data-number-value></label>
<label class="text-xs font-bold text-slate-600 xl:col-span-2"><span class="flex items-center justify-between gap-2"><span>Giá nhập / Giá vốn *</span>@if($canViewCosts)<span class="font-medium text-slate-500">Giá vốn TB: <strong data-reference-cost-label class="text-slate-800">—</strong></span>@endif</span><input type="text" inputmode="decimal" data-number-display data-scale="4" required class="mt-1 h-11 w-full rounded-xl border border-slate-300 bg-white px-2 text-right font-normal tabular-nums" placeholder="0"><input type="hidden" data-field="unit_price_ex_vat" data-number-value></label>
<label class="text-xs font-bold text-slate-600 xl:col-span-2">Giá xuất HĐ chưa VAT<input type="text" inputmode="decimal" data-number-display data-scale="4" class="mt-1 h-11 w-full rounded-xl border border-slate-300 bg-white px-2 text-right font-normal tabular-nums" placeholder="0"><input type="hidden" data-field="invoice_unit_price_ex_vat" data-number-value></label>
</div><div class="mt-2 flex justify-end"><button type="button" class="remove-receipt-item min-h-10 rounded-xl px-3 text-sm font-bold text-rose-600">Xóa dòng</button></div>
</div></article></template>
</div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const box=document.getElementById('receipt-items'),tpl=document.getElementById('receipt-item-template'),add=document.getElementById('add-receipt-item'),invoiceToggle=document.getElementById('toggle-receipt-invoice'),invoiceFields=document.getElementById('receipt-invoice-fields');let next=0;
invoiceToggle?.addEventListener('click',()=>{const open=invoiceToggle.getAttribute('aria-expanded')==='true';invoiceToggle.setAttribute('aria-expanded',open?'false':'true');invoiceToggle.textContent=open?'Hiện':'Ẩn';invoiceFields?.classList.toggle('hidden',open);});
const summary=(article)=>{const search=article.querySelector('[data-combobox-search]'),batch=article.querySelector('[data-field="batch_number"]'),expiry=article.querySelector('[data-field="expiry_date"]'),qty=article.querySelector('[data-field="quantity"]'),name=article.querySelector('.receipt-item-summary-name'),meta=article.querySelector('.receipt-item-summary-meta');name.textContent=search?.value||'Sản phẩm mới';const parts=[];if(batch?.value)parts.push('Lô '+batch.value);if(expiry?.value){const p=expiry.value.split('-');parts.push('HSD '+(p.length===3?[p[2],p[1],p[0]].join('/'):expiry.value));}if(qty?.value)parts.push('SL '+qty.value.replace('.',','));meta.textContent=parts.length?parts.join(' · '):'Chưa nhập thông tin lô';};
const setOpen=(article,open)=>{const editor=article.querySelector('.receipt-item-editor'),toggle=article.querySelector('.toggle-receipt-item');editor.classList.toggle('hidden',!open);toggle.setAttribute('aria-expanded',open?'true':'false');toggle.textContent=open?'Ẩn':'Sửa';};
const closeOthers=(current)=>box.querySelectorAll('.receipt-item').forEach(article=>{if(article!==current)setOpen(article,false);});
const wireCombobox=(root)=>{const search=root.querySelector('[data-combobox-search]'),value=root.querySelector('[data-combobox-value]'),results=root.querySelector('[data-combobox-results]'),clear=root.querySelector('[data-combobox-clear]'),options=[...root.querySelectorAll('[data-combobox-option]')];const norm=s=>(s||'').toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');const filter=()=>{const q=norm(search.value.trim());options.forEach(o=>o.classList.toggle('hidden',!!q&&!norm(o.dataset.search).includes(q)));results.classList.remove('hidden');clear.classList.toggle('hidden',!search.value);clear.classList.toggle('flex',!!search.value);};search.addEventListener('focus',filter);search.addEventListener('input',()=>{value.value='';filter();summary(root.closest('.receipt-item'));});options.forEach(o=>o.addEventListener('click',()=>{search.value=o.dataset.label;value.value=o.dataset.value;const article=root.closest('.receipt-item'),costLabel=article?.querySelector('[data-reference-cost-label]');if(costLabel)costLabel.textContent=o.dataset.referenceCost?o.dataset.referenceCost+' đ':'—';results.classList.add('hidden');clear.classList.remove('hidden');clear.classList.add('flex');if(article)summary(article);}));clear.addEventListener('click',()=>{search.value='';value.value='';const article=root.closest('.receipt-item'),costLabel=article?.querySelector('[data-reference-cost-label]');if(costLabel)costLabel.textContent='—';clear.classList.add('hidden');clear.classList.remove('flex');if(article)summary(article);search.focus();filter();});document.addEventListener('click',e=>{if(!root.contains(e.target))results.classList.add('hidden');});};
document.querySelectorAll('[data-receipt-combobox]').forEach(wireCombobox);
const wireNumber=(display)=>{const value=display.parentElement.querySelector('[data-number-value]'),scale=Number(display.dataset.scale||0);const sync=()=>{let raw=display.value.replace(/\s/g,'').replace(/\./g,'').replace(',', '.').replace(/[^0-9.]/g,'');const parts=raw.split('.');const integer=(parts.shift()||'').replace(/^0+(?=\d)/,'')||'0';const decimal=parts.join('').slice(0,scale);value.value=integer+(decimal?'.'+decimal:'');display.value=Number(integer).toLocaleString('vi-VN')+(decimal?','+decimal:'');const article=display.closest('.receipt-item');if(article)summary(article);};display.addEventListener('input',sync);display.addEventListener('blur',sync);};
const append=(item=null)=>{const index=next++,node=tpl.content.cloneNode(true),article=node.querySelector('.receipt-item');article.querySelectorAll('[data-field]').forEach(el=>el.name='items['+index+']['+el.dataset.field+']');article.querySelectorAll('[data-receipt-combobox]').forEach(wireCombobox);article.querySelectorAll('[data-number-display]').forEach(wireNumber);article.querySelectorAll('[data-field="batch_number"],[data-field="expiry_date"]').forEach(el=>el.addEventListener('input',()=>summary(article)));article.querySelector('.toggle-receipt-item').addEventListener('click',()=>{const open=article.querySelector('.toggle-receipt-item').getAttribute('aria-expanded')==='true';if(open)setOpen(article,false);else{closeOthers(article);setOpen(article,true);}});article.querySelector('.remove-receipt-item').addEventListener('click',()=>{if(box.children.length>1)article.remove();});box.appendChild(node);if(item){['batch_number','expiry_date'].forEach(key=>{const el=article.querySelector('[data-field="'+key+'"]');if(el)el.value=item[key]??'';});const med=article.querySelector('[data-field="medicine_id"]');const option=med?.closest('[data-receipt-combobox]')?.querySelector('[data-combobox-option][data-value="'+item.medicine_id+'"]');if(option)option.click();[['quantity',item.quantity],['unit_price_ex_vat',item.unit_price_ex_vat],['invoice_unit_price_ex_vat',item.invoice_unit_price_ex_vat]].forEach(([key,val])=>{const hidden=article.querySelector('[data-field="'+key+'"]'),display=hidden?.parentElement.querySelector('[data-number-display]');if(display){display.value=String(val??'').replace('.',',');display.dispatchEvent(new Event('input'));}});summary(article);setOpen(article,false);}else{closeOthers(article);setOpen(article,true);}return article;};
add.addEventListener('click',()=>{append();box.lastElementChild?.scrollIntoView({behavior:'smooth',block:'nearest'});});const initial=@json($initialItems);if(initial.length)initial.forEach(item=>append(item));else append();});
</script>
@endsection
