@extends('ClientPortal::layouts.application')
@section('title','Bảng Giá') @section('app-name','Mua sắm công') @section('app-dashboard-route',route('client.muasamcong.dashboard'))
@section('content')
<div class="space-y-5"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Excel qua Queue</p><h1 class="mt-1 text-2xl font-bold">Bảng Giá</h1><p class="mt-1 text-sm text-slate-600">Chọn sản phẩm và cấu hình do Admin thiết lập. PWA không cần chỉnh cấu trúc Excel.</p></div>
@if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('status') }}</div>@endif
<div class="flex gap-2"><a href="{{ route('client.muasamcong.price-list',['source'=>'synced']) }}" class="rounded-xl px-4 py-2 text-sm font-bold {{ $source==='synced'?'bg-slate-900 text-white':'border bg-white' }}">Dữ liệu đồng bộ</a><a href="{{ route('client.muasamcong.price-list',['source'=>'wishlist']) }}" class="rounded-xl px-4 py-2 text-sm font-bold {{ $source==='wishlist'?'bg-rose-600 text-white':'border bg-white' }}">♥ Wishlist</a></div>
<form method="POST" action="{{ route('client.muasamcong.price-list.store') }}" class="space-y-4">@csrf<input type="hidden" name="source" value="{{ $source }}"><div class="rounded-2xl border bg-white p-4"><label class="text-xs font-bold uppercase text-slate-500">Cấu hình xuất</label><select name="profile_id" required class="mt-2 w-full rounded-xl border px-3 py-3">@forelse($profiles as $p)<option value="{{ $p->id }}">{{ $p->name }}{{ $p->is_default?' · Mặc định':'' }}</option>@empty<option value="">Admin chưa tạo cấu hình Bảng Giá</option>@endforelse</select></div>
<div class="space-y-2">@forelse($items as $item)@php($isWish=$source==='wishlist')<label class="flex gap-3 rounded-2xl border bg-white p-4 shadow-sm"><input type="checkbox" name="selected_ids[]" value="{{ $isWish?$item->id:$item->source_id }}" class="mt-1 h-5 w-5 shrink-0"><div class="min-w-0"><p class="font-bold text-slate-900">{{ $isWish?$item->medicine_name:$item->ten_thuoc }}</p><p class="mt-1 text-sm text-slate-500">{{ $isWish?$item->active_ingredient:$item->ten_hoat_chat }}</p>@if(!$isWish)<p class="mt-1 text-sm font-semibold">{{ number_format((float)$item->don_gia,0,',','.') }} đ</p>@endif</div></label>@empty<div class="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">Không có dữ liệu.</div>@endforelse</div>
@if($profiles->isNotEmpty()&&$items->count())<div class="sticky bottom-20 z-10 rounded-2xl border bg-white/95 p-3 shadow-lg backdrop-blur"><button class="w-full rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white">Xuất Excel qua Queue</button></div>@endif</form>
@if($items->hasPages())<div>{{ $items->links() }}</div>@endif
<div><h2 class="mb-3 text-lg font-bold">Lịch sử xuất gần đây</h2><div class="space-y-2">@forelse($exports as $e)<div class="rounded-2xl border bg-white p-4" data-export-id="{{ $e->id }}"><div class="flex justify-between gap-3"><div><p class="font-bold">{{ $e->file_name?:'Bảng Giá đang tạo' }}</p><p class="text-xs text-slate-500">{{ $e->created_at->format('d/m/Y H:i') }} · {{ $e->source==='wishlist'?'Wishlist':'Đã đồng bộ' }}</p></div><span class="export-status rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{{ $e->status }}</span></div>@if($e->status==='completed')<div class="mt-3 flex flex-wrap gap-2"><a href="{{ route('client.muasamcong.price-list.download',$e) }}" class="rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white">Tải Excel</a><button type="button" data-share="{{ route('client.muasamcong.price-list.share',$e) }}" class="share-export rounded-xl border px-3 py-2 text-xs font-bold">↗ Chia sẻ / Copy</button><form method="POST" action="{{ route('client.muasamcong.price-list.email',$e) }}" class="flex gap-1">@csrf<input type="email" name="email" required placeholder="Email nhận file" class="min-w-0 rounded-xl border px-2 py-2 text-xs"><button class="rounded-xl border px-3 py-2 text-xs font-bold">Gửi email</button></form></div>@elseif($e->status==='failed')<p class="mt-2 text-xs text-red-600">{{ $e->error_message }}</p>@endif</div>@empty<p class="text-sm text-slate-500">Chưa có lịch sử xuất.</p>@endforelse</div></div></div>
<script>document.querySelectorAll('.share-export').forEach(b=>b.addEventListener('click',async()=>{try{const r=await fetch(b.dataset.share,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())}}),d=await r.json();if(navigator.share)await navigator.share({title:'Bảng Giá Mua sắm công',url:d.url});else if(navigator.clipboard){await navigator.clipboard.writeText(d.url);alert('Đã copy link tải Bảng Giá.')}else prompt('Copy link:',d.url)}catch(e){if(e?.name!=='AbortError')alert('Không thể chia sẻ file.')}}));</script>
@endsection
