<?php

return [
    'name' => 'Request',
    'type' => 'domain',
    'enabled' => false,
    'default_enabled' => false,
    'depends' => ['Admin', 'Auth', 'User', 'Role', 'Shared'],
    'permissions_required' => true,
    'permissions' => [
        'request.dashboard.view',
        'request.group.view',
        'request.group.create',
        'request.group.update',
        'request.group.archive',
        'request.type.view',
        'request.type.create',
        'request.type.delete',
        'request.type.update',
        'request.type.audience.manage',
        'request.type.publish',
        'request.type.retire',
        'request.type.import',
        'request.type.export',
        'request.instance.view-own',
        'request.instance.view-participant',
        'request.instance.view-all',
        'request.instance.create',
        'request.instance.update-own',
        'request.instance.submit',
        'request.instance.cancel-own',
        'request.instance.cancel-any',
        'request.instance.delete',
        'request.task.view',
        'request.task.decide',
        'request.task.reassign',
        'request.comment.create',
        'request.attachment.upload',
        'request.attachment.download',
        'request.audit.view',
        'request.report.view',
        'request.export',
        'request.operation.view',
        'request.operation.retry',
        'request.operation.delete',
    ],
    'permissions_by_guard' => [
        'web' => [
            'client.request.access',
            'client.request.overview.view',
            'client.request.create.view',
            'client.request.mine.view',
            'client.request.inbox.view',
            'client.request.processed.view',
            'request.instance.view-own',
            'request.instance.view-participant',
            'request.instance.create',
            'request.instance.update-own',
            'request.instance.submit',
            'request.instance.cancel-own',
            'request.task.view',
            'request.task.decide',
            'request.comment.create',
            'request.attachment.upload',
            'request.attachment.download',
        ],
    ],
    'tables' => [
        'request_groups',
        'request_types',
        'request_type_versions',
        'request_type_audiences',
        'request_stage_definitions',
        'request_audit_events',
        'request_outbox_messages',
        'request_idempotency_keys',
        'request_instances',
        'request_payload_revisions',
        'request_runs',
        'request_tasks',
        'request_task_candidates',
        'request_decisions',
        'request_comments',
        'request_attachments',
        'request_export_jobs',
        'request_notification_deliveries',
    ],
];
